<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm =  $this->frm_search;
?>
<title><?php echo $tr->translate("PRODUCTBOOKING");?></title>
<script type="text/javascript">
dojo.ready(function(){
});
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
 <div class="blog_form_title">
 	<h4><i class="fa fa-book" aria-hidden="true"></i> <?php echo $tr->translate("PRODUCTBOOKING")?></h4>
 </div>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'booking','controller'=>'productbooking','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
  <table>
  	<tr>
  		<td><?php echo $frm->getElement("search_text");?></td>
  		<td><?php echo $tr->translate("Booking From")?></td>
  		<td><?php echo $frm->getElement('from_book_date');?></td>
  		<td><?php echo $tr->translate("To Booking")?></td>
  		<td><?php echo $frm->getElement('to_book_date');?></td>
  		<td> <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
  	</tr>
  </table>
  
  
  
</form>
<?php echo $this->list;?>
