<title>About Us</title>
<div class="message-shadow"></div>
<div class="clearfix"></div>
<section class="content">
    <div class="container">
        <div class="inner-page">
            <div class="col-md-12 padding-none">       
                <?php foreach ($this->showdata as $row){ ?>
                	<h4 style="background:#e3c4d4;background: linear-gradient(to bottom, #ffffff 0%,#e3c4d4 100%);padding:10px;color:red; " class="margin-bottom-25 margin-top-none"><strong>ABOUT </strong><span style="text-transform: uppercase;">US</span></h4>
                	<!-- <h5 style="background:#e3c4d4;background: linear-gradient(to bottom, #ffffff 0%,#e3c4d4 100%);padding:10px; "> <?php //echo $row['title']?></h5> -->
                	 <div class="row" align="justify">
                	 	<?php echo $row['description']?> 
                	 </div>
                <?php }?>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <!--container ends--> 
</section>
<!--content ends-->
