<title>City Tour Detail</title>
<div class="clearfix"></div>
<section class="content">
    <div class="container">
		<div class="inner-page">
            <div class="row padding-bottom-40">
                <div class="col-lg-7 col-md-8 col-xs-12 left-content padding-left-none xs-padding-bottom-40 sm-padding-bottom-40"> 
                    <!--OPEN OF SLIDER-->
                    <div class="slider">
                        <div class="flexslider flexslider2">
                        <div style="overflow: hidden; position: relative;" class="flex-viewport"><ul style="width: 800%; transition-duration: 0s; transform: translate3d(-1530px, 0px, 0px);" class="slides item">
                        	<?php foreach ($this->photo as $row){?>
                        		<li style="float: left; display: block; width: 765px;" aria-hidden="true" class="clone"> <img draggable="false" width="675px" src="<?php echo $this->baseUrl()."/images/location/".$row['pic_title'];?>"> </li>
                        	<?php }?>
                        	
                        	 <?php if(!empty($this->alllocation))foreach($this->alllocation as $location){?>
                        	  <?php $pic=Application_Model_DbTable_DbFrontend::getPicCityTourByLocation($location['id']);?>
		                    	<li style="float: left; display: block; width: 765px;" aria-hidden="true" class="clone"> <img draggable="false" width="675px" src="<?php echo $this->baseUrl()."/images/location/".$pic['pic_title'];?>"> </li>
		                    <?php }?>	
                            </ul>
                        </div>
                            <ul class="flex-direction-nav">
                            	<li><a class="flex-prev" href="#"></a></li><li><a class="flex-next" href="#"></a></li>
                            </ul></div>
                    </div>
                    <div style="clear:both;"></div>
                    <?php if(!empty($this->alllocation))foreach($this->alllocation as $location){?>
                    	
                    	<h3 style="background: red; font-size: 14px;padding:5px 10px; color: #fff;"><?php echo $location['location_name'];?></h3>
                    	<p><?php echo $location['note'];?></p>
                    
                    <?php }?>
                    
                    <!--CLOSE OF SLIDER--> 
                    <!--Slider End--> 
                    
                </div>
                
                <div class="col-lg-5 col-md-4 right-content padding-right-none xs-padding-left-none sm-padding-left-none">
                    <div class="right_site_job">
                        <div class="job sm-padding-bottom-40 xs-padding-bottom-40 xs-padding-top-10">
                            <h2><?php echo $this->row['location_name'];?></h2>
                            <p align="justify"><?php echo $this->row['note'];?></p>
                        </div>
                        <div class="project_details">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
            <div class="container">
                </div>
            </div>
        </div>     
    </div>
    <!--container ends--> 
</section>