<title>DRIVING LICENSE TRANSFER</title>
<style>
	.note ul{list-style-type: none;}
</style>
<section class="content">
	<div class="container">
		<div class="inner-page row">
			<div class="row note">
				<h6><b>DRIVING LICENSE TRANSFER</b></h6>
				<p><b>Lyna-CarRental.Com</b> offers license transfer service from your national driving license to Cambodian driving license and also renew of your expired Cambodian driving license. The application process will take only 1 minute; a provisional one will be issued to allow the applicant to drive. The original driving license will be issued within 30 days.</p>
				<ul>
					<li><b>1.	Transferring to Cambodian Driving License.</b></li>
					<li> 
						<ul>
							<li><b>Documents required:</b></li>
							<li>1.	Original valid passport</li>
							<li>2.	A copy of valid visa entry to Cambodia</li>
							<li>3.	6 photos of size 4x6</li>
							<li>4.	Certificate of current address in Cambodia from authority (to be facilitated by Lyna-CarRental.Com)</li>
							<li>5.	A Valid Original National Driving License or International License (to be returned in one week) <br /><span style="font-size: 13px;padding-left:20px;font-style: italic;">*If the above Original Driving License is not in English, a certificate of recognition from the relevant Embassy is required, and the applicant shall responsible for the process.</span></li>
							<li>6.  Price: USD 60</li>
						</ul>
					</li>
					<li><b>2.	Renew of Cambodian Driving License.</b>
						<ul>
							<li><b>Documents required:</b></li>
							<li>1.	Original valid passport or Cambodian National ID Card</li>
							<li>2.	A Valid visa entry to Cambodia (for foreigner)</li>
							<li>3.	6 photos of size 4x6</li>
							<li>4.	The original expired Cambodian Driving License</li>
							<li>5.	Price: USD 40</li>
						</ul>
					</li>
				</ul>
				
				For more information, please contact Lyna-CarRental.Com at <a href="mail:info@lyna-carrental.com">info@lyna-carrental.com</a> Hotline: +855(0) 12 55 42 47
                12 92 45 17 | 92 14 30 14
			 </div>
		</div>
	</div>
</section>
