<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();

$session_lang=new Zend_Session_Namespace('lang');
$currentlang = $session_lang->lang_id;

$home_article = json_decode($this->home_article['value'],true);
$db = new Application_Model_DbTable_DbGlobalSelect();
$facebook = $db->getWebsiteSetting('facebook');

$homecategory = $db->getWebsiteSetting("homecategorycontent");
$lastestart="";
$cateinfo='';
if (!empty($homecategory['value'])){
	$cateinfo = $db->getCategoryByID($homecategory['value']);
	$lastestart = $db->getArcticleByCateLastesArticle($homecategory['value']);
}
?>

<title><?php echo $tr->translate("COMPANY_NAME");?></title>

<!-- Start Banner Carousel -->
<div class="banner-outer">
  <div class="banner-slider">
  <?php if(!empty($this->slides)) foreach($this->slides as $ss){?>
    <div class="slide1" style="background: url(<?php echo $this->baseUrl()."/images/slide/".$ss; ?>) no-repeat center top / cover; display: block;     background-size: 100%;">
      <div class="container">
        <div class="content animated fadeInRight">
        </div>
      </div>
    </div>
    <?php }?>
  </div>
</div>
<!-- End Banner Carousel --> 


<!-- Start Our Importance Section -->
<section class="our-impotance padding-lg">
  <div class="container">
  	<?php if(!empty($this->announcement)){?> 
	<div id="announcementanimation" class="col-sm-12"  style="visibility: hidden;" >
			<div class="maqueefecture">
				<div class="row">
					<div class="col-sm-3 bracks" style="">
						<div class="brack">
							<p><?php echo $tr->translate("ANNOUNCEMENT");?></p>
						</div>
						<div class="cornerhome"></div>
					</div>
					<div class="col-sm-9 title_fectuer" >
					
						<div class="marquee">
						<?php foreach($this->announcement as $rs){?>
							<a href="<?php echo $this->baseUrl()."/page/index?article=".$rs['alias_article'].".html"; ?>"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $rs['title']." :";?></a>
							<span><?php echo strip_tags($rs['description']); ?></span>
						<?php }?>
						</div>
					</div>
					
				</div>
			</div>
	</div>
<?php }?>	
  	 
    <div class="col-sm-9">
		<div class="welcome-blog">
		<?php if (!empty($this->homearticle)){?>
		
				<div class="home-title">
					<h4><?php echo $this->homearticle['title'];?></h4>
				</div>
				<?php echo $this->homearticle['description'];?>
			
		  </div>
		  <?php }?>
	  </div>
	  <!-- Start Right Column -->
		<div class="col-sm-3">
		  <div class="home-blog-right">
		  	<?php if(!empty($this->menuright)){?>
		  	<div class="menu-second">
		  		<h3><?php echo $tr->translate("INFORMATION");?></h3>
			  		<ul class="sidebar-menu">
						<?php  foreach($this->menuright as $menu){ $checksub = $db->checkSubMenuRight($menu['id']);?>
							<li>
								<a href="<?php echo $this->baseUrl()."/page/index?param=".$menu['alias_menu'].".html";?>">
								  <span><?php echo $menu['title']?></span>
								  <?php if(!empty($checksub)){?>
								  <i class="fa fa-angle-left pull-right"></i>
								  <?php }?>
								</a>
								<?php echo $db->getSubMenuRight($this->baseUrl(), $menu['id']); ?>
							</li>
						<?php }?>
					</ul>
		  	</div>
		  	<?php }?>
		    <?php if (!empty($lastestart)){?>
			<div class="recent-post">
			  <h3><?php echo empty($cateinfo['title'])?$tr->translate("LASTEST_ARTICLE"):$cateinfo['title']." ".$tr->translate("NEW");?></h3>
			  <ul>
			    <?php foreach ($lastestart as $rs){?>
				<li class="clearfix"> 
					<a href="<?php echo $this->baseUrl()."/page/index?article=".$rs['alias_article'].".html"; ?>">
				  		<div class="img-block">
					  		<?php if(!empty($rs['image_feature'])){?>
								<img src="<?php echo $this->baseUrl()."/images/article/".$rs['image_feature'];?>" alt="<?php echo $rs['title'];?>" class="img-responsive"/>
							<?php }else{?>
								<img src="<?php echo $this->baseUrl()."/images/noimage.jpg";?>" alt="<?php echo $rs['title'];?>" class="img-responsive"/>
							<?php }?>
						</div>
						  <div class="detail">
							<h4><?php echo $rs['title'];?></h4>
							<p><span class="icon-date-icon ico"></span><span><?php echo date("d M",strtotime($rs['create_date']));?></span> <?php echo date("Y",strtotime($rs['create_date']));?></p>
					  </div>
				  	</a> 
				 </li>
				 <?php }?>
			  </ul>
			</div>
			<?php }?>
			<?php if (!empty($facebook['value'])){?>
			<div class="facebookpage">
			  <h3><?php echo $tr->translate("FACEBOOK");?></h3>
			  <div class="fb-page" data-href="<?php echo $facebook['value'];?>" data-tabs="timeline" data-width="280" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="<?php echo $facebook['value'];?>" class="fb-xfbml-parse-ignore"><a href="<?php echo $facebook['value'];?>">Facebook</a></blockquote></div>
			</div>
			<?php }?>
		  </div>
		</div>
		<!-- End Right Column --> 
	 </div>
	</section>
	<!-- End Our Importance Section --> 


<!-- Start logos Section -->

<section class="logos">
  <div class="container">
  	<div class="col-sm-12 partner_logo">
  		<div class="row">
			<div class="col-sm-3  ">
				<div class="brackpartner">
					<p><?php echo $tr->translate("OUR_PARTNER");?></p>
					<div class="cornerhome partner"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-sm-12">
	    <ul class="owl-carousel clearfix">
	    <?php if(!empty($this->partner)) foreach($this->partner as $par){?>
	      <li><a href="#"><img src="<?php echo $this->baseUrl()."/images/slide/partner/".$par; ?>" class="img-responsive" alt=""></a></li>
	    <?php }?>
	    </ul>
    </div>
  </div>
</section>

<!-- End logos Section --> 
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/js/jquery.marquee.min.js"></script>
<script type="text/javascript">
		jQuery(document).ready(function(){
			<?php if(!empty($this->announcement)){?> 
			jQuery('.marquee').marquee({
			//speed in milliseconds of the marquee
			duration: 20000,
			//gap in pixels between the tickers
			gap: 50,
			//time in milliseconds before the marquee will start animating
			delayBeforeStart: 0,
			//'left' or 'right'
			direction: 'left',
			//true or false - should the marquee be duplicated to show an effect of continues flow
			duplicated: true,
			pauseOnHover: true
			});
			   // visibility: hidden;
			jQuery("#announcementanimation").css("visibility","initial");
			<?php }?>
		});
	   </script> 
