<?php $baseUrl = $this->baseUrl();?>
<style>
#signup:hover{
color:blue;}
legend{color:red;}
</style>
<script src="<?php echo $baseUrl;?>/ckeditor/ckeditor.js"></script>
	<script src="<?php echo $baseUrl;?>/ckeditor/samples/samples.js"></script>
	<link rel="stylesheet" href="<?php echo $baseUrl;?>/ckeditor/samples/sample.css">
	<link rel="stylesheet" href="<?php echo $baseUrl;?>/ckeditor/samples/neo.css">
<?php $form = $this->frmbooking;?>
<section class="content">
    <div class="container">
        <div class="inner-page inventory-listing">
            <div class="row"> 
            <div class="clearfix"></div>
            <div class="tab-pane" id="step4" style="margin-top: -30px;">
                <div class="clearfix" style="margin-top: 0px"></div>
                    <form action="" method="post" id="signups">
                    	<div class="col-md-6">
                    	<fieldset style="margin-top: 24px;"><legend><strong>Customer</strong> Info</legend>
			             <div id="signup_section" style="background: #FFC100;padding: 10px 17px 16px 0px;border-radius: 5px;color: black;font-weight: 800;">
                         <div class="select-wrapper clearfix">
                              <div class="col-md-6">
                                   <div class="my-dropdown make-dropdown">
                                          First Name :
                                          <?php echo $form->getElement('first_name');?>
                                   </div>
                               </div>
                               <div class="col-md-6">
                                    <div class="my-dropdown make-dropdown">
                                        Last Name : 
                                        <?php echo $form->getElement('last_name');?>
                                    </div>
                               </div>
                          </div>
                          <div class="select-wrapper clearfix">
		                       <div class="col-md-6">
		                            <div class="my-dropdown make-dropdown">
		                                Occupation : 
		                                <input type="text" name="occupation" style="width:100%; height:40px;">
		                            </div>
		                        </div>
		                        <div class="col-md-6">
		                            <div class="my-dropdown make-dropdown">
		                                Gender : 
		                                <?php echo $form->getElement('gender');?>
		                            </div>
		                         </div>
		                   </div>
                           <div class="select-wrapper clearfix">
                           		<div class="col-md-6">
                                    <div class="my-dropdown make-dropdown">
                                        Cell Phone : 
                                        <?php echo $form->getElement('phone');?>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="my-dropdown make-dropdown">
                                        E-mail : 
                                        <?php echo $form->getElement('email');?>
             							<div id='email_availability_result' style="position: absolute;right: 0px;"></div>
                                    </div>
                                </div>
                            </div>
                            </div>
                            </fieldset>
                            </div>
                            <div class="col-md-6">
                            <fieldset style="margin-top: 24px;"><legend><strong>Credit Card</strong> Info</legend>
							<div id="signup_section" style="background: #FFC100;padding: 10px 17px 16px 0px;border-radius: 5px;color: black;font-weight: 800;">		
                            <div class="select-wrapper clearfix">
                                <div class="col-md-6">
		                            <div class="my-dropdown make-dropdown">
		                                 Card Name: 
		                                 <?php echo $form->getElement('card_name');?>
		                            </div>
		                        </div>
		                        <div class="col-md-6">
		                            <div class="my-dropdown make-dropdown">
		                                 Card No.:
		                                 <input name="card_id" type="text" style="width: 100%;height:40px; padding:1px" class="credit_card_number" pattern="\d*" x-autocompletetype="cc-number" placeholder="Credit Card Number" required> </p>
		                            </div>
		                        </div>
		                    </div>
		                    <div class="select-wrapper clearfix">
		                        <div class="col-md-6">
		                            <div class="my-dropdown make-dropdown">
		                                Security Code/CVV: 
		                                <input style="width: 100%; padding:1px;height:40px" name="secu_code" id=secu_code" type="text" class="credit_card_cvc" pattern="\d*" x-autocompletetype="cc-csc" placeholder="Security Code/CVV" required  autocomplete="off">
		                            </div>
		                        </div>
		                        <div class="col-md-6">
		                            <div class="my-dropdown make-dropdown">
		                                Expiration Date: 
		                                <input type="text" style="width: 100%;height:40px" name="card_exp_date" class="credit_card_expiry" pattern="\d*" x-autocompletetype="cc-exp" placeholder="Expires MM / YY" required maxlength="9"> </p>
		                            </div>
		                        </div>
		                    </div>
		                    <div class="select-wrapper clearfix" id="ws_union" style="display: none;background: rgb(255, 193, 0) none repeat scroll 0% 0%;padding: 10px 0px 16px;border-radius: 5px;color: rgb(255, 255, 255);font-weight: 800;margin-bottom:10px">
		                        <div class="col-md-6">
		                            <div class="my-dropdown make-dropdown">
		                                MTCN Code No.:
		                                <input class="number" name="code_num" style="width: 100%;height:40px; padding:1px;" type="text" placeholder="10-Digit MTCN No." data-formance_length="10">
		                            </div>
		                        </div>
		                                    
		                    </div>
                        </div>
                        </fieldset>
                        </div>
                        <div class="col-md-12" style="clear: both;">
                        <fieldset style="margin-top: 24px;"><legend><strong>Payment</strong> Info</legend>
							<div id="signup_section" style="background: #FFC100;padding: 10px 17px 16px 0px;border-radius: 5px;color: black;font-weight: 800;">		
                           
		                    <div class="select-wrapper clearfix">
		                        <div class="col-md-3">
		                            <div class="my-dropdown make-dropdown">
		                                Amount In US$ (50%): 
		                                <input style="width: 100%; padding:1px;height:40px" name="amount_book" id="amount_book" type="text" class="number" placeholder="Amount Book" required  autocomplete="off">
		                            </div>
		                        </div>
		                        <div class="col-md-3">
		                            <div class="my-dropdown make-dropdown">
		                                Amount In US$ (100%): 
		                                <input type="text" style="width: 100%;padding:1px;height:40px" name="amount" class="number" placeholder="Amount Full" required > </p>
		                            </div>
		                        </div>
		                        <div class="col-md-3">
		                            <div class="my-dropdown make-dropdown">
		                                Service Charge (3%):
		                                <input class="number" name="service_charge" style="width: 100%;padding:1px;height:40px; padding:1px;" type="text" placeholder="Service Charge(3%)">
		                            </div>
		                        </div>
		                        
		                        <div class="col-md-3">
		                            <div class="my-dropdown make-dropdown">
		                                Net Total In US$:
		                                <input class="number" name="total" style="width: 100%;padding:1px;height:40px; padding:1px;" type="text" placeholder="Total in US$">
		                            </div>
		                        </div>
		                                    
		                    </div>
		                    <div class="select-wrapper clearfix">
		                        <div class="col-md-12">
		                            <div class="my-dropdown make-dropdown">
		                            	Purposes:
		                            	<textarea id="editor" rows="" cols="" name="purpose">
		                            	</textarea>
		                            	
		                            </div>
		                        </div>
		                        
		                                    
		                    </div>
                                  
                            <div class="select-wrapper clearfix">
                                <div class="col-md-2"></div>
                                <div class="col-md-8" style="text-align: center;margin-top: 10px">
                                    <div class="my-dropdown make-dropdown">
                                        <button type="reset" name="reset">Reset</button>
                                        <button type="button" name="signup" onClick="formValidate();">Pay Finish</button>
                                    </div>
                                </div>
                                <div class="col-md-2"></div>
                            </div>
                        </div>
                        </fieldset>
                        </div>
                    </form>
                </div>
            </div>
        </div>
   </div>
</section>

			                    	
			                    	
			                    	
<script>

function signUp(){
	$('#signup_section').css("display", "block");
	$('#login_section').css("display", "none");
}
function logIn(){
	$('#signup_section').css("display", "none");
	$('#login_section').css("display", "block");
}

form_valid = 0;
function checkUserName(type){
	var checking_html = '<img src="<?php echo $this->baseUrl();?>/images/checkloading.gif" />';
	var available = '<img  src="<?php echo $this->baseUrl();?>/images/apply2.png" />';
	var unavailable = '<img title="User Name not available!" style="cursor:pointer" src="<?php echo $this->baseUrl();?>/images/cross.png" />';
	var emilunavailable = '<img title="Email not available!" style="cursor:pointer" src="<?php echo $this->baseUrl();?>/images/cross.png" />';
	var not_valid = '<img alt="Email not Valid!" title="Email not valid!" style="cursor:pointer" src="<?php echo $this->baseUrl();?>/images/none.png" />';
	var url = "<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'check-username-available'));?>";
	if(type==1){
		var user_name = $('#s_user_name').val();
		$('#username_availability_result').html(checking_html);
	}else{
		var user_name = $('#email').val();
		$('#email_availability_result').html(checking_html);
	}
	$.ajax({
        url: url,
        type: "post",
        data: {'user_name':user_name,'type':type},
        success: function(data){
            val = $.parseJSON(data);
			if(val==1){
				if(type==1){
					$('#username_availability_result').html(unavailable);
				}else{
					$('#email_availability_result').html(emilunavailable);
					$("#email").css("border", "1px solid red"); 
				}
				form_valid=1;
			}else{
				if(type==1){
					$('#username_availability_result').html(available);
				}else{
					var re = /^(([^<>()[\]\.,;:\s@\"]+(\.[^<>()[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i;
					email_validate = re.test(user_name);
					if(email_validate==true){
						$('#email_availability_result').html(available);
						form_valid=0;
					}else{
						$('#email_availability_result').html(not_valid);
						$("#email").css("border", "1px solid red"); 
						form_valid=1;
					}
					
				}
			}
        },
        error:function(e){
           // alert(e);
        }
    });
}
function loginValidate(){
	user_name =  $("#user_name").val();
	password = $("#password").val();
	if(user_name==""){ 
        $("#user_name").css("border", "1px solid red"); 
        validate=1;
    } else {
		$("#user_name").css("border", "1px solid #E4E4E4");
		validate=0;
	}
	if(password=="") {  
        $("#password").css("border", "1px solid red"); 
        validate=1;
    } else {
		$("#password").css("border", "1px solid #E4E4E4");
		validate=0;
	}

	if(validate == 1){
		return false;
	}else{
		//alert(1);
		//$('#signup').submit();
		document.getElementById("login").submit();
	}
}

function formValidate(){
	user_name =  $("#s_user_name").val();
	email =  $("#email").val();
	password = $("#s_password").val();
	first_name = $("#first_name").val();
	last_name= $("#last_name").val();
	phone = $("#phone").val();
	if(user_name==""){ 
        $("#s_user_name").css("border", "1px solid red"); 
        form_valid=1;
    } else {
		$("#s_user_name").css("border", "1px solid #E4E4E4");
	}
    if(email==""){ 
        $("#email").css("border", "1px solid red"); 
        form_valid=1;
    } else {
		$("#email").css("border", "1px solid #E4E4E4");
	}
    if(password=="") {  
        $("#s_password").css("border", "1px solid red"); 
        form_valid=1;
    } else {
		$("#s_password").css("border", "1px solid #E4E4E4");
	}
    if(first_name=="") {  
        $("#first_name").css("border", "1px solid red"); 
        form_valid=1;
    } else {
		$("#first_name").css("border", "1px solid #E4E4E4");
	}
    if(last_name=="") {  
        $("#last_name").css("border", "1px solid red"); 
        form_valid=1;
    } else {
		$("#last_name").css("border", "1px solid #E4E4E4");
	}
    if(phone=="") {  
        $("#phone").css("border", "1px solid red"); 
        form_valid=1;
    } else {
		$("#phone").css("border", "1px solid #E4E4E4");
	}
	if(form_valid==1){
		return false;
	}else{
		//alert(1);
		//$('#signup').submit();
		document.getElementById("signups").submit();
	}
}
$(function() {
    
$( "#dob" ).datepicker({ changeMonth: true,changeYear: true});
    $( "#dob" ).change(function() {
      $( "#dob" ).datepicker( "option","dateFormat", "dd-mm-yy" );
    });
    //checkSite();
  });
</script>
<script>
	initSample();
</script>
 <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/js/js-ui/jquery-ui.css">
<!--   <script src="//code.jquery.com/jquery-1.10.2.js"></script> -->
  <script src="<?php echo $this->baseUrl();?>/js/js-ui/jquery-ui.js"></script>
  
  <script src="<?php echo $this->baseUrl();?>/js/form-validate/scale.fix.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/form-validate/jquery.formance.min.js" /></script>
<script src="<?php echo $this->baseUrl();?>/js/form-validate/awesome_form.js"></script>