<title>Prayer List</title>
<div class="clearfix"></div>
<section class="content">
    <div class="container">
    	<h5 > 
    	<?php //echo $this->prayerrow['title'];?></h5>
    	<h4 style="background:#e3c4d4;background: linear-gradient(to bottom, #ffffff 0%,#e3c4d4 100%);padding:10px;color:red; " class="margin-bottom-25 margin-top-none"><strong>PRAYER </strong><span style="text-transform: uppercase;">LIST</span></h4>
    		<?php 
	    		echo $this->prayerrow['descript'];
			?>
    </div>
</section>
