<title>Our Service Detail</title>
<div class="message-shadow"></div>
<div class="clearfix"></div>
<section class="content">
    <div class="container">
		<div class="inner-page">
            <div class="row padding-bottom-40">
                <div class="col-lg-7 col-md-8 col-xs-12 left-content padding-left-none xs-padding-bottom-40 sm-padding-bottom-40"> 
                    <!--OPEN OF SLIDER-->
                    <div class="slider">
                    	<img style="margin-bottom:10px;" draggable="false" src="<?php echo $this->baseUrl()."/images/".$this->row['photo'];?>" width="100%" alt="Portfolio Image 2"> 
                        <img style="margin-bottom:10px;" draggable="false" src="<?php echo $this->baseUrl()."/images/".$this->row['photo'];?>" alt="Portfolio Image" width="100%" >
                        <img style="margin-bottom:10px;" draggable="false" src="<?php echo $this->baseUrl()."/images/".$this->row['photo1'];?>" alt="Portfolio Image 2" width="100%">
                        <img style="margin-bottom:10px;" draggable="false" src="<?php echo $this->baseUrl()."/images/".$this->row['photo2'];?>" alt="Portfolio Image" width="100%">   
                    </div>
                    
                    <!--CLOSE OF SLIDER--> 
                    <!--Slider End--> 
                    
                </div>
                <div class="col-lg-5 col-md-4 right-content padding-right-none xs-padding-left-none sm-padding-left-none">
                    <div class="right_site_job">
                        <div class="job sm-padding-bottom-40 xs-padding-bottom-40 xs-padding-top-10">
                            <h2><?php echo $this->row['service_title'];?></h2>
                            <p align="justify"><?php echo $this->row['description'];?></p>
                        </div>
                        <div class="project_details">
                            <h2>Service Fee($)</h2>
                            <ul class="margin-bottom-none">
                                <li><i class="fa fa-check-circle"></i><?php echo $this->row['price'];?></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="project_wrapper clearfix margin-top-30">
                    <h4 class="related_project_head margin-top-10 padding-bottom-15 margin-top-none">Related Services</h4>
                    <div class="related_post margin-top-30 clearfix">
                       <?php foreach ($this->showdata AS $row){?>
                        <div style="visibility: visible; animation-name: fadeInLeft;" class="col-lg-3 col-md-3 col-sm-6 col-xs-12 scroll_effect fadeInLeft animated">
                            <div style="height:220px;" class="car-block margin-bottom-10">
                            	<a href="<?php echo $this->baseUrl();?>/index/servicedetail/id/<?php echo $row['id'];?>">
	                                <div class="img-flex"> 
		                                <span class="align-center">
		                                	<i class="fa fa-3x fa-youtube-play"></i>
		                                </span> 
		                                <img src="<?php echo $this->baseUrl()."/images/".$row['photo'];?>" alt="" class="img-responsive">
	                                </div>
	                                <div class="car-block-bottom">
	                                    <h2 style="font-size:14px;"><?php echo $row['service_title'];?></h2>
	                                </div>
                                </a> 
                             </div>
                        </div>
                        <?php }?>
                    </div>
                </div>
            </div>
        </div>     
    </div>
    <!--container ends--> 
</section>
<!--content ends-->