<title>Our Service</title>
<div class="clearfix"></div>
<?php 
	$db = new Application_Model_DbTable_DbGlobal();
	$instruction = "serviceinstruction";
	$rows = $db->getAllParameter($instruction);
?>
<section class="content">
    <div class="container">
         <h4 style="background:#e3c4d4;background: linear-gradient(to bottom, #ffffff 0%,#e3c4d4 100%);padding:10px;color:red; " class="margin-bottom-25 margin-top-none"><strong>OUR </strong><span style="text-transform: uppercase;">Services</span></h4>
         <?php //echo $rows;?> 
</div>
</section>
<section class="content">
    <div class="container">
    <div class="car_listings boxed boxed_left col-md-9 col-lg-push-3 col-md-push-3">
      <div class="inner-page portfolio-container row">
    	  <div id="MixItUp22776A" class="portfolioContainer portfolio_2">
    	  	<?php foreach ($this->showdata as $row){ ?>
	                <div style="display: inline-block;" class="col-md-4 suv hardtop mix margin-bottom-50">
	                    <div class="box clearfix"> 
	                    	<a class="fancybox" href="servicedetail/id/<?php echo $row['id'];?>">
	                    		<img class="image" src="<?php echo $this->baseUrl()."/images/".$row['photo'];?>" alt="">
	                    	</a>
	                        <div class="padding-top-25 padding-bottom-10">
	                            <h2 align="center"><a style="    font-weight: 500; font-size:14px; color: #0015FF;" href="<?php echo $this->url(array('module'=>'default','controller'=>"index",'action'=>'servicedetail','id'=>$row['id']),null,true); ?>"><?php echo $row['service_title']; ?></a></h2>
<!-- 	                            <span>Rating *****</span> -->
	                            <div id="dv1"></div>
                    			<div style="clear:both;"></div>
	                             </div>
	                        <p><?php //echo substr($row['description'],0, 250);?> </p>
	                        <span style="clear: both;"></span>
	                    </div>
	                </div>
             <?php }?>
           </div>
    	</div>
    	</div>
    	<div class="col-md-3 col-sm-12 col-lg-pull-9 col-md-pull-9 left-sidebar" style=" border:1px solid #ccc;padding:10px;text-align:justify;">
            	<?php echo $rows;?> 
            </div>
    </div>
</section>