<title>Terms & Conditions</title>
<section class="content">
	<div class="container">
		<div class="inner-page row">
			<div class="row">
				<div class="car_listings boxed boxed_left col-md-9 col-lg-push-3 col-md-push-3"><!-- start right -->
					<div class="blog-content">
                    <div class="post-entry clearfix">
					<div class="col-lg-12">
					   <?php if(!empty($this->rows)) foreach($this->rows as $rows){?>    
					        <blockquote><?php echo $rows['title'];?></blockquote>
					        <p><?php echo $rows['description'];?></p>        
					   <?php }?>
					</div>
				   </div>
				   </div>
					<div class="clearfix"></div>
				</div>
				<div class=" col-md-3 col-sm-12 col-lg-pull-9 col-md-pull-9 left-sidebar">
			         <div class="left_inventory">
				               <div class="side-content row">
		                            <div class="list col-md-12 col-sm-3 padding-bottom-50">
		                                <ul>
						                    <li id="home-active" class="active"><a href="<?php echo $this->baseUrl();?>">HOME</a></li>
					                            <li id="about-active"><a href="<?php echo $this->baseUrl()?>/index/about">About Us </a></li>
					                            <li id="booking-active"><a href="<?php echo $this->baseUrl()?>/index/contact">Contact Us </a></li>
					                            <li id="service-active"><a href="<?php echo $this->baseUrl()?>/index/fqa">FAQs</a></li>
					                            <li id="job-active"><a href="<?php echo $this->baseUrl()?>/index/job">Job Vacancies</a>
					                            <li id="contact-active"><a href="<?php echo $this->baseUrl()?>/index/termcondition">Terms & Conditions</a></li>
					                            <li id="contact-active"><a href="<?php echo $this->baseUrl()?>/index/policy">Privacy Policy</a></li>
						                </ul>
		                            </div>
	                        	</div>
			         </div>
			    </div>
			 </div>
		</div>
	</div>
</section>