<title>City Tour Package</title>
<div class="clearfix"></div>
<?php 
	$db = new Application_Model_DbTable_DbGlobal();
	$instruction = "productinstruction";
	$rows = $db->getAllParameter($instruction);
	
?>
<div class="clearfix"></div>
<section class="content">
    <div class="container">
         <?php //echo $rows;?> 
    </div>
</section>
<section class="message-wrap margin-bottom-20">
    <div class="container">
        <div class="row">
            <h2 class="col-lg-9 col-md-8 col-sm-12 col-xs-12 xs-padding-left-15" style="color:red;"><strong>City Tour Service</strong> Booking<span class="alternate-font"></span></h2>
            <div class="col-lg-3 col-md-4 col-sm-12 col-xs-12 xs-padding-right-15"> </div>
        </div>
    </div>
    <div class="message-shadow"></div>
</section>
<section class="content">
    <div class="container">
    
    <div class="car_listings boxed boxed_left col-md-9 col-lg-push-3 col-md-push-3 margin-bottom-10">
	      <div class="inner-page portfolio-container row">
	    	  <div id="MixItUp22776A" class="portfolioContainer portfolio_2">
	    	  	<?php $is_set=1;$normal_set=1;
	    	  	 foreach ($this->tourlocation as $row){ ?>
	    	  	 <?php if($row['is_package']==1 AND $is_set==1){ $is_set=0;?>
	    	  	 <section style="background:#F0F0F0;">
				    <div class="container">
				        <div class="row">
				            <h4 class="col-lg-9 col-md-8 col-sm-12 col-xs-12 xs-padding-left-15" style="color:red;"><strong>Package Tour</strong><span class="alternate-font"></span></h4>
				            <div class="col-lg-3 col-md-4 col-sm-12 col-xs-12 xs-padding-right-15"> </div>
				        </div>
				    </div>
				    <div class="message-shadow"></div>
				</section>
				<?php }?>
				<?php if($row['is_package']==0 AND $normal_set==1){ $normal_set=0;?>
	    	  	 <section style="background:#F0F0F0;margin-bottom: 10px;">
				    <div class="container">
				        <div class="row">
				            <h4 class="col-lg-9 col-md-8 col-sm-12 col-xs-12 xs-padding-left-15" style="color:red;"><strong>Normal Tour</strong><span class="alternate-font"></span></h4>
				            <div class="col-lg-3 col-md-4 col-sm-12 col-xs-12 xs-padding-right-15"> </div>
				        </div>
				    </div>
				    <div class="message-shadow"></div>
				</section>
				<?php }?>
	
		                <div style="display: inline-block;" class="col-md-4 suv hardtop mix margin-bottom-50">
		                    <div class="box clearfix" style="text-align:justify;"> 
		                    	<a class="fancybox" href="<?php echo $this->url(array('module'=>'default','controller'=>"index",'action'=>'citytourbooking','id'=>$row['id']),null,true); ?>">
		                         <?php $pic=Application_Model_DbTable_DbFrontend::getPicCityTourByLocation($row['id']);?>
		                        <img class="image" src="<?php echo $this->baseUrl()."/images/location/".$pic['pic_title'];?>" alt=""></a>
		                        <div class="padding-top-25 padding-bottom-10">
		                            <h2 style="text-align: center; font-size: 16px;" ><a target="_blank" title="click here to detail" href="<?php echo $this->url(array('module'=>'default','controller'=>"index",'action'=>'citytourdetail','id'=>$row['id']),null,true); ?>"><?php echo $row['location_name'];?></a></h2>
	<!-- 	                            <span>Rating *****</span> -->
		                            <div id="dv1"></div>
	                    			<div style="clear:both;"></div>
		                        </div>
		                        <p><?php echo substr($row['note'],0, 250);?></p>
		                        <div style="text-align: center; border-bottom: none;">
		                        	<input  type="button"  value="Book Now"" label="Book Now" onclick="window.location = '<?php echo $this->url(array('module'=>'default','controller'=>"index",'action'=>'getcitytourpackageid','package_id'=>$row['id']),null,true); ?>';"/><br />
		                        </div>
		                        <span style="clear: both;"></span>
		                    </div>
		                </div>
	             <?php }?>
	           </div>
	    	</div>
    	</div>
    	<div class="col-md-3 col-sm-12 col-lg-pull-9 col-md-pull-9 left-sidebar" style=" border:1px solid #ccc;padding:10px;">
            	<?php echo $rows;?> 
        </div>
    	
    	
    </div>
</section>