<title>Vehicles List</title>
<style>
.inventory .title {
    position: initial;}
</style>
<?php 
	$db = new Application_Model_DbTable_DbGlobal();
	$instruction = "carrentalinstruction";
	$rows = $db->getAllParameter($instruction);
	//$rows = explode(",", $rows);
	
?>
<div class="clearfix"></div>
<section class="content">
    <div class="container">
         <?php //echo $rows;?> 
    </div>
</section>
<section class="message-wrap">
    <div class="container">
        <div class="row">
            <h2 class="col-lg-9 col-md-8 col-sm-12 col-xs-12 xs-padding-left-15" style="color:red;"><strong>VEHICLES</strong> Rental<span class="alternate-font"></span></h2>
            <div class="col-lg-3 col-md-4 col-sm-12 col-xs-12 xs-padding-right-15"> <a href="<?php echo $this->url(array("module"=>"default","controller"=>"index","action"=>"booking"));?>" class="default-btn pull-right action_button lg-button">Book Now</a> </div>
        </div>
    </div>
    <div class="message-shadow"></div>
</section>
<section class="content">
    <div class="container">
    	<div class="car_listings boxed boxed_left col-md-9 col-lg-push-3 col-md-push-3 margin-bottom-10">
	    	<div class="pricing_wrapper layout-4 clearfix">
	                <?php if(!empty($this->rows))foreach ($this->rows as $row){ ?>
	                <div class="col-md-4 col-sm-6 col-xs-12 padding-right-5 padding-left-5 margin-top-10">
	                    <div class="pricing_table">
	                        <div class="pricing-header" style="background: #FF0300">
	                            <h4><a style="color:#fff;" target="_blank" href="<?php echo $this->baseUrl()."/index/vehicle/id/".$row['id'];?>"><?php echo $row["make"]." ".$row["model"]." ".$row["sub_model"];?></a></h4>
	                        </div>
	                        <div class="main_pricing" style="background: #fff;">
	                           <a  target="_blank" href="<?php echo $this->baseUrl()."/index/vehicle/id/".$row['id'];?>"><img style="border:none;padding-top:5px;" src="<?php echo $this->baseUrl()."/images/vehicle/".$row['img_front_right'];?>" alt="preview" /></a>
	                        	<div style="clear:both;"></div>
	                        </div>
	                        <div style="clear:both;"></div>
	                        <div class="category_pricing">
	                            <ul>
				                       <li>Ref:	<?php echo $row['reffer'];?></li>
				                       <?php $rowprice = Application_Model_DbTable_DbGlobal::getVehiceRankingDay($row["id"]);
				                       if(!empty($rowprice)) foreach($rowprice As $pric){?>
			                           		<li><?php echo $pric["package_name"];?>: $ <?php echo number_format($pric["price"],2);?> / Day</li>
			                           <?php }?>
			                     </ul>
	                        </div>
	                        <div class="price-footer padding-vertical-15">
	                            <form method="post" action="#">
	                                <input  type="button"  value="Book Now" label="Book Now" onclick="window.location = '<?php echo $this->url(array('module'=>'default','controller'=>"index",'action'=>'booking'),null,true); ?>';"/>
	                            </form>
	                        </div>
	                    </div>
	                </div>
	                <?php }?>
	                <div style="clear: both;"></div>
	            </div>
            </div>
            <div class="col-md-3 col-sm-12 col-lg-pull-9 col-md-pull-9 left-sidebar margin-top-10" style=" border:1px solid #ccc;padding:10px;">
            	<?php echo $rows;?> 
            </div>
    </div>
</section>