<title>GuestBook</title>
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	//echo $this->headTitle($tr->translate('ADD_HOLIDAY'));
?>	
<?php  $row= $this->row;?>
<script>
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea")
</script>
<form  id='add_techer' action="<?php echo $this->url(array('module'=>'other','controller'=>'guestbook','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post"
 enctype="application/x-www-form-urlencoded">
 <script type="dojo/method" event="onSubmit">	
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="45%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend align="center" ><strong><?php echo $tr->translate("Guestbook");?></strong></legend>
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td>Name<input type="hidden" name="id" id="id" value="<?php echo $row['id'];?>"/></td>
							<td><input dojoType="dijit.form.ValidationTextBox" class="fullside"  id="name" name="name" value="<?php echo $row['name'];?>" type="text" /></td>
						</tr>
						<tr>
							<td>Subject</td>
							<td><input dojoType="dijit.form.ValidationTextBox" class="fullside"  id="subject" name="subject" value="<?php echo $row['subject'];?>" type="text" /></td>
						</tr>
						<tr>
							<td>E-mail</td>
							<td><input dojoType="dijit.form.ValidationTextBox" class="fullside"  id="email" name="email" value="<?php echo $row['email'];?>" type="text" /></td>
						</tr>
						<tr>
							<td>Website </td>
							<td><input dojoType="dijit.form.ValidationTextBox" class="fullside"  id="website" name="website" value="<?php echo $row['website'];?>" type="text"/></td>
						</tr>
						<tr>
							<td colspan="2">Comments</td>
						</tr>
						<tr>
						  <td valign="top" colspan="2">
								<textarea tabindex="21" dojoType="dijit.form.SimpleTextarea" class="fullside" style="width: 502px;min-height: 35px;height: 249px;" id="comment" name="comment" /><?php echo $row['comment'];?></textarea>
						    </td>
						</tr>
						<tr>
							<td>date</td>
							<td><input tabindex="20"  name="date" id="date" dojoType="dijit.form.DateTextBox"  class="fullside" value="<?php echo $row['date'];?>" type="text" /></td>
						</tr>
						<tr>
							<td>Status</td>
										<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true"  class="fullside">
											    <option value="1" label="Active">Active</option>
											    <option value="0" label="Deactive">Deactive</option>
											</select>
										</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
									<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<?php $base_url = Application_Form_FrmMessage::getUrl("/"); ?>
<script src="<?php echo $base_url;?>js/moment.min.js"  type="text/javascript">

</script>
