<title>GuestBook</title>
<style>
  a{ color: #000;}
</style>
<table width="100%" border='1' style="border:1px solid #ccc; border-collapse:collapse;">
	  <tr>
	    <th class="tdheader header">No.</th>
	    <th class="tdheader header">Name</th>
	    <th class="tdheader header">Subject</th>
	    <th class="tdheader header">E-mail </th>
	    <th class="tdheader header">Website</th>
	    <th class="tdheader header">Comments</th>
	    <th class="tdheader header">Date </th>
	    <th class="tdheader header">Status</th>
	    <th class="tdheader header">Delete</th>
	  </tr>
	  <?php 
	  $imgnone = $this->baseUrl()."/images/icon/apply2.png";
	  $imgntow = $this->baseUrl()."/images/icon/cross.png";
		if(!empty($this->row))foreach ($this->row as $key =>$row){
			if ($row['status']==1){
			     $img="<img src='".$imgnone."'/>";	
			}else{
		         $img="<img src='".$imgntow."'/>";
			} 
	 ?>
	  <tr align="center">
	  	<td style="border:1px solid #ccc;padding:1px;" align="center"><?php echo $key+1;?></td>
	  	<td style="border:1px solid #ccc;padding:1px;text-align:left;">&nbsp;<a href="<?php echo $this->baseUrl().'/other/guestbook/edit/id/'.$row['id'];?>"><?php echo $row['name'];?></a></td>
	  	<td style="border:1px solid #ccc;padding:1px;text-align:left;">&nbsp;<a href="<?php echo $this->baseUrl().'/other/guestbook/edit/id/'.$row['id'];?>"><?php echo substr($row['subject'],0,20);?></a></td>
	    <td style="border:1px solid #ccc;padding:1px;text-align:left;">&nbsp;<a href="<?php echo $this->baseUrl().'/other/guestbook/edit/id/'.$row['id'];?>"><?php echo $row['email'];?></a></td>
	  	<td style="border:1px solid #ccc;padding:1px;text-align:left;">&nbsp;<a href="<?php echo $this->baseUrl().'/other/guestbook/edit/id/'.$row['id'];?>"><?php echo substr($row['website'],0,15);?></a></td>
	  	<td style="border:1px solid #ccc;padding:1px;text-align:left;">&nbsp;<a href="<?php echo $this->baseUrl().'/other/guestbook/edit/id/'.$row['id'];?>"><?php echo substr($row['comment'],0,50);?></a><span style="clear: both;"></span></td>
	    <td style="border:1px solid #ccc;padding:1px;text-align:left;">&nbsp;<a href="<?php echo $this->baseUrl().'/other/guestbook/edit/id/'.$row['id'];?>"><?php echo $row['date'];?></a></td>
	  	<td style="border:1px solid #ccc;padding:1px;"><?php echo $img;?></td>
	  	<td style="border:1px solid #ccc;padding:1px;"><a href="<?php echo $this->baseUrl().'/other/guestbook/delete/id/'.$row['id'];?>">Delete</a></td>
	  </tr>
	  <?php 
		}
		?>
</table>