<?php 
   $tr = Application_Form_FrmLanguages::getCurrentlanguage();
   echo $this->headTitle($tr->translate("BOOKING"));
   $rows_owner= $this->rows_owner;
   $rows_cus=$this->rows_cus;
?>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
require(["dijit/form/CheckBox","dijit/Dialog"]);

dojo.ready(function(){
});
function setAgreementRef(){
	lastagreement = dijit.byId('lastagreement').get('value');
	prefix_code=dijit.byId('prefix_code').get('value');
	release_date = dijit.byId("agreement_date").get('value');
	 var a = new Date(release_date);
	 mm = a.getMonth()+1;
	
	 var dd = a.getDate();
	  if(dd<10){
	   dd = "0"+dd;
	 }
	  if(mm<10){
	   mm = "0"+mm;
	 }
	 var y = a.getYear();
	 var agreement_code = prefix_code+'-'+ y + '-'+ mm + '-'+dd+'-'+lastagreement ;
	 dijit.byId('agreement_code').attr('value',agreement_code);
}
	var url_owner = "<?php echo $this->url(array('module'=>'agreement','controller'=>'index','action'=>'get-row-owner'));?>";
	function getOwner(){
       name_id=dijit.byId('owner_name').get('value');
       if(name_id==''){
    	   dijit.byId('position').attr('value','');
		   dijit.byId('id_card').attr('value','');
		   dijit.byId('hand_phone').attr('value','');
		   dijit.byId('email').attr('value','');
		   dijit.byId('hotline').attr('value','');
       }else{
		dojo.xhrPost({
		     url: url_owner, 
		     content : { 
		     'owner_name':dijit.byId('owner_name').get('value'),
		  }, 
		  handleAs:"json",
		  load: function(data) {
			  //alert(data);
		   dijit.byId('position').attr('value',data.position);
		   dijit.byId('id_card').attr('value',data.id_card);
		   dijit.byId('hand_phone').attr('value',data.hand_phone);
		   dijit.byId('email').attr('value',data.email);
		   dijit.byId('hotline').attr('value',data.hotline);
		  },
		  error: function(err) {
		   alert(err);
		  alert("Your message could not be sent, please try again!.");         
		  }
		 });
       }
	}
var url_customer = "<?php echo $this->url(array('module'=>'agreement','controller'=>'index','action'=>'get-booking'));?>";
function getBookingInfo(){
        booking_id=dijit.byId('booking_id').get('value');
		dojo.xhrPost({
		     url: url_customer, 
		     content : { 
		     "booking_id":booking_id,
		  }, 
		  handleAs:"json",
		  load: function(data) {
			dijit.byId("customer_id").attr("value",data.customer_id);
			dijit.byId('incep_date').attr('value',data.pickup_date);
			dijit.byId('return_date').attr('value',data.return_date);
			dijit.byId('return_time').attr('value',data.return_time);

			dijit.byId('first_name').attr('value',data.first_name);
			dijit.byId('last_name').attr('value',data.last_name);
			
			dijit.byId('gender').attr('value',data.sex);
			dijit.byId('dob').attr('value',data.dob);
			dijit.byId('pob').attr('value',data.pob);
			dijit.byId('nationality').attr('value',data.nationality);
			dijit.byId('company').attr('value',data.company_name);

			calCulateDay();
			getBookingVehicleDetail(booking_id);
		  },
		  error: function(err) {
		  	alert("Your message could not be sent, please try again!.");         
		  }
		 });
}
var url_vehicle = "<?php echo $this->url(array('module'=>'agreement','controller'=>'index','action'=>'get-vehiclebooking'));?>";
function getBookingVehicleDetail(booking_id){
		dojo.xhrPost({
		     url: url_vehicle, 
		     content : { 
		     "booking_id":booking_id,
		  }, 
		  handleAs:"json",
		  load: function(data) {
			 dijit.byId('vehicle_ref_no').attr('value',data.item_id);
			 dijit.byId('price_day').attr('value',data.price);
			 //dijit.byId('vat').attr('value',parseInt(data.VAT));
			
			 dijit.byId('total_vat').attr('value',parseInt(data.VAT));
			 dijit.byId('discount_value').attr('value',data.discount);
			 dijit.byId('amount_price').attr('value',data.total);

			 dijit.byId('paid_amount').attr('value',data.total_paymented);
			 dijit.byId('amount_f_d').attr('value',parseInt(data.refund_deposit));
			 grandTotal();
		  },
		  error: function(err) {
		  	alert("Your message could not be sent, please try again!.");         
		  }
		 });
	}
function grandTotal(){
	dijit.byId('due_amount').attr('value','');
	rentalfee = dijit.byId('amount_price').get('value');
	amount_f_d=dijit.byId('amount_f_d').get('value');
	longdast=dijit.byId('longdast').get('value');
	if(isNaN(longdast)){
		longdast=0;
	}
	fixeddiscount_value = dijit.byId("discount_value").get('value');
	if(isNaN(fixeddiscount_value)){
		fixeddiscount_value=0;
	}
	discount_percent = dijit.byId("discount_percent").get('value');
	if(isNaN(discount_percent)){
		discount_percent=0;
	}
    /////////////////
	sunday_price = dijit.byId("sunday_price").get('value');
	if(isNaN(sunday_price)){
		sunday_price=0;
	}
	airport_price = dijit.byId("airport_price").get('value');
	if(isNaN(airport_price)){
		airport_price=0;
	}
	dropairport_price = dijit.byId("dropairport_price").get('value');
	if(isNaN(dropairport_price)){
		dropairport_price=0;
	}

	item_1 = dijit.byId("item_1").get('value');
	if(isNaN(item_1)){
		item_1=0;
	}
	
	item_2 = dijit.byId("item_2").get('value');
	if(isNaN(item_2)){
		item_2=0;
	}
	item_3 = dijit.byId("item_3").get('value');
	if(isNaN(item_3)){
		item_3=0;
	}
	///////////////
	grand_total = sunday_price+airport_price+dropairport_price+item_1+item_2+item_3+(rentalfee+amount_f_d+longdast-fixeddiscount_value)-(rentalfee*discount_percent/100);
	dijit.byId('grand_total').attr('value',grand_total);
	paid_amount = dijit.byId('paid_amount').get('value');
	deu_total = grand_total-paid_amount;
	dijit.byId('due_amount').attr('value',deu_total);
}

function calCulateDay(){
			incep_date = dijit.byId('incep_date').get('value');
			return_date = dijit.byId('return_date').get('value');
		    oneDay = 24*60*60*1000;
			day=return_date - incep_date;
		    total_duration = Math.round(day/oneDay)+1;
			dijit.byId('period').attr('value',total_duration);
			period_value=dijit.byId('period').get('value');
			if(period_value<0){
				alert('Please checked day again !');
				dijit.byId('period').attr('value','0');
				dijit.byId('incep_date').attr('value',return_date);
			}
	}
	function CalculateDate(){
		amount_day = dijit.byId('period').get('value');
		if(isNaN(amount_day)){
			dijit.byId('period').focus();
		}
		if(amount_day==''){
			dijit.byId('period').focus();
		}
		
		else{
			start_date = dijit.byId("incep_date").value;
			var a = new Date(start_date);
				var mm = a.getMonth() + 1;
			var dd = a.getDate()+parseInt(amount_day);
			 if(dd<10){
				 dd = "0"+dd;
			}
			 if(mm<10){
				 mm = "0"+mm;
			}
			var y = a.getFullYear();
			var return_date = y + '-'+ mm + '-'+dd ;
			dijit.byId('return_date').attr('value',return_date);
	   }
		   
	}
	function priceDay(){
		period=dijit.byId('period').get('value');
		price_day=dijit.byId('price_day').get('value');
		if(period==0 || price_day==0){
			dijit.byId('period').focus();
		}
		amount_price=period*price_day;
		dijit.byId('amount_price').attr('value',amount_price);
		depositPrice();
	}
	function depositPrice(){
		total_vat=dijit.byId('total_vat').get('value');
		amount_price=dijit.byId('amount_price').get('value');
		//period_dolla=dijit.byId('period_dolla').get('value');
		deposit=dijit.byId('deposit').get('value');
		total_net_pay=total_vat+amount_price+deposit;
		dijit.byId('total_net_pay').attr('value',total_net_pay);
	}
</script>
<form id='add_season'  action="<?php echo $this->url(array('module'=>'agreement','controller'=>'index','action'=>'add')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
	<div >
		<table  width="100%" style="background:#D6E5F8;">
			<tr>
				<td width="30%" valign="top">
						<fieldset style="border:1px solid #FFF; "><legend align="center" ><strong>I.Party A (Ownder of The Vehicle)</strong></legend>
						<table>
							<tr >
							
								<td width="100px">Name</td>
								<td><select name="owner_name" id="owner_name" dojoType="dijit.form.FilteringSelect" class="fullside" onchange="getOwner();">
									    <option value="">---ជ្រើសរើសឈ្មោះ---</option>
									    <?php foreach ($rows_owner As  $rs){?>
									    <option value="<?php echo $rs['id'];?>"><?php echo $rs['owner_name'];?></option>
									    <?php }?>
									</select>
								</td>
							</tr>
							<tr>
								<td>Position</td>
								<td><input dojoType="dijit.form.ValidationTextBox" required="required" type="text" name="position" id="position" class="fullside" /></td>
							</tr>
							<tr>
								<td >ID Card</td>
								<td><input dojoType="dijit.form.NumberTextBox" required="required" type="text" class="fullside" id="id_card" name="id_card"></td>
							</tr>
							<tr>
								<td>Hand Phone</td>
								<td><input dojoType="dijit.form.ValidationTextBox"  type="text" class="fullside" id="hand_phone" name="hand_phone"></td>
							</tr>
							<tr>
								<td>E-mail</td>
								<td><input dojoType="dijit.form.ValidationTextBox"  type="text" name="email" id="email" class="fullside" /></td>
							</tr>
							<tr>
								<td>Insurance Hotline</td>
								<td><input dojoType="dijit.form.ValidationTextBox"  type="text" class="fullside" id="hotline" name="hotline"></td>
							</tr>
							</table>
							</fieldset>
							<fieldset style="border:1px solid #FFF; "><legend align="center" ><strong>II. Party B (Renter) And (Requiredment)</strong></legend>
								<table>
										<tr>
											<td>Booking Number</td>
											<td><select name="booking_id" id="booking_id" dojoType="dijit.form.FilteringSelect" class="fullside" class="fullside" onchange="getBookingInfo();">
												   <option value=''>---Selected Booking Number---</option>
												   <?php foreach ($this->rsbooking as $rs){?>
												    <option value="<?php echo $rs['id'];?>"><?php echo $rs['booking_no'];?></option>
												    <?php }?>
												</select>
											</td>
										</tr>
										<tr>
											<td>First Name</td>
											<td><input dojoType="dijit.form.ValidationTextBox"   type="text" name="first_name" id="first_name" class="fullside"></td>
										</tr>
										<tr>
											<td>Last Name</td>
											<td><input dojoType="dijit.form.ValidationTextBox"   type="text" name="last_name" id="last_name" class="fullside"></td>
										</tr>
										<tr>
											<td>Gender</td>
											<td>
												<select name="gender" id="gender" dojoType="dijit.form.FilteringSelect" class="fullside"  >
													<option value="1">Male</option>
													<option value="2">Female</option>
												</select>
											</td>
										</tr>
										<tr>
											<td>Date of Birth</td>
											<td><input dojoType="dijit.form.DateTextBox"   type="text" name="dob" id="dob" class="fullside"></td>
										</tr>
										<tr>
											<td>Place of Birth</td>
											<td><input dojoType="dijit.form.ValidationTextBox"   type="text" name="pob" id="pob" class="fullside"></td>
										</tr>
										<tr>
											<td>Nationality</td>
											<td><input dojoType="dijit.form.ValidationTextBox"   type="text" name="nationality" id="nationality" class="fullside"></td>
										</tr>
									    <tr>
											<td>Company/Org</td>
											<td><input dojoType="dijit.form.ValidationTextBox"   type="text" name="company" id="company" class="fullside"></td>
										</tr>
<tr>
											<td>Witness Name</td>
											<td><input dojoType="dijit.form.ValidationTextBox"   type="text" name="witness" id="witness" class="fullside"></td>
										</tr>
										<tr>
											<td colspan="2" align="center" ><input dojoType="dijit.form.CheckBox" type="checkbox" checked="checked" id="passport" name="passport" />&nbsp;Passport&nbsp;&nbsp;&nbsp;&nbsp;
											<input dojoType="dijit.form.CheckBox" type="checkbox" id="idcard" name="idcard" checked="checked" />&nbsp;ID Card&nbsp;&nbsp;&nbsp;&nbsp;
											<input dojoType="dijit.form.CheckBox" type="checkbox" id="familybook" name="familybook" checked="checked" />&nbsp;Family Book&nbsp;&nbsp;&nbsp;&nbsp;</td>
										</tr>
						</table>
					</fieldset>
				</td>
				<td valign="top">
				<fieldset style="border:1px solid #FFF; "><legend align="center" ><strong>Reservation Infomation</strong></legend>
					<table style="margin: 0 auto; width:100%; white-space: nowrap;" cellspacing="2"  >
					    <tr>
							<td>Vehicle Ref No</td>
							<td>
							    <select name="vehicle_ref_no"  id="vehicle_ref_no" dojoType="dijit.form.FilteringSelect" class="fullside"  >
								    <?php foreach ($rows=$this->row_vehicle as $rs ){?>
								    <option value="<?php echo $rs['id'];?>"><?php echo $rs['reffer'];?></option>
								    <?php }?>
								</select>
							</td>
						</tr>
						<tr>
							<td >Inception Date</td>
							<td><input dojoType="dijit.form.DateTextBox"  type="text"  id="incep_date" class="fullside"  name="incep_date" value="now" onchange="calCulateDay();"></td>
						</tr>
						<tr>	
							<td >Return Date</td>
							<td ><input dojoType="dijit.form.DateTextBox"  type="text" class="fullside" name="return_date" id="return_date" value="now" onchange="calCulateDay();"></td>
						</tr>
						<tr>
							<td >Return Time</td>
							<td ><input dojoType="dijit.form.ValidationTextBox" type="text" class="fullside" id="return_time" name="return_time"></td>
						</tr>
						<tr>
							<td >Amount Day</td>
							<td ><input dojoType="dijit.form.NumberTextBox" required="true" type="text" class="fullside" id="period" name="period" value='' onkeyup="CalculateDate();"  ></td>
						</tr>
						<tr>
							<td>Price/Day($)</td>
							<td><input  dojoType="dijit.form.NumberTextBox" required="true" type="text" class="fullside" name="price_day" id="price_day" onkeyup="priceDay();" /></td>
						</tr>
<!-- 						<tr> -->
<!-- 							<td>VAT(%)</td> -->
<!-- 							<td> -->
<!-- 		                        <select name="vat" id="vat" dojoType="dijit.form.FilteringSelect" class="fullside"> -->
								    <?php //if(!empty($this->rs_tax))foreach ($this->rs_tax as $key=> $row){?>
												<option value="<?php //echo $row['id'];?>"><?php //echo $row['title'];?></option>
									<?php //}?>
<!-- 								</select>					 -->
<!-- 							</td> -->
<!-- 						</tr> -->
						<tr>
							<td>Total VAT($)</td>
							<td><input dojoType="dijit.form.NumberTextBox"  type="text" name="total_vat" class="fullside" id="total_vat" value="" onkeyup="priceDay();"></td>
						</tr>	
						</table>
						</fieldset>
						<fieldset style="border:1px solid #FFF; white-space: nowrap; ">
							<legend align="center" ><strong>Other Fee Charge</strong></legend>
							<table>
									<tr>
										<td>Extra Charge Sunday</td>
										<td><input dojoType="dijit.form.NumberTextBox" onkeyup="grandTotal();" type="text" class="fullside" id="sunday_price" name="sunday_price"  /></td>
										<td style="padding-right: 5px;padding-left: 5px;">Remarks</td>
										<td><input dojoType="dijit.form.TextBox"  type="text" class="fullside" name="sunday_remark" value="" /></td>
									</tr>
									<tr>
										<td>Pickup Airport</td>
										<td><input dojoType="dijit.form.NumberTextBox" onkeyup="grandTotal();"  type="text" class="fullside" id="airport_price" name="airport_price"  /></td>
										<td style="padding-right: 5px;padding-left: 5px;">Remarks</td>
										<td><input dojoType="dijit.form.TextBox"  type="text" class="fullside" name="airport_remark" value="" /></td>
									</tr>
									<tr>
										<td>Drop of Airport</td>
										<td><input dojoType="dijit.form.NumberTextBox" onkeyup="grandTotal();"  type="text" class="fullside" id="dropairport_price" name="dropairport_price"  /></td>
										<td style="padding-right: 5px;padding-left: 5px;">Remarks</td>
										<td><input dojoType="dijit.form.TextBox"  type="text" class="fullside" name="dropairport_remark" value="" /></td>
									</tr>
									<tr>
										<td>Item 1</td>
										<td><input dojoType="dijit.form.NumberTextBox" onkeyup="grandTotal();" type="text" class="fullside" id="item_1" name="item_1"  /></td>
										<td style="padding-right: 5px;padding-left: 5px;">Remarks</td>
										<td><input dojoType="dijit.form.TextBox"  type="text" class="fullside" name="item_1remark" value="" /></td>
									</tr>
									<tr>
										<td>Item 2</td>
										<td><input dojoType="dijit.form.NumberTextBox" onkeyup="grandTotal();" type="text" class="fullside" id="item_2" name="item_2"  /></td>
										<td style="padding-right: 5px;padding-left: 5px;">Remarks</td>
										<td><input dojoType="dijit.form.TextBox"  type="text" class="fullside" name="item_2remark" value="" /></td>
									</tr>
									<tr>
										<td>Item 3</td>
										<td><input dojoType="dijit.form.NumberTextBox" onkeyup="grandTotal();" type="text" class="fullside" id="item_3" name="item_3"  /></td>
										<td style="padding-right: 5px;padding-left: 5px;">Remarks</td>
										<td><input dojoType="dijit.form.TextBox"  type="text" class="fullside" name="item_3remark" value="" /></td>
									</tr>
								</table>
						</fieldset>
						<fieldset style="border:1px solid #FFF; white-space: nowrap; ">
					<legend align="center" ><strong>Rental Period Information</strong></legend>
					<table>
							<tr>
								<td colspan="4">&nbsp;</td>
							</tr>
							<tr>
								<td style="color: red">Retal Fee($)</td>
								<td><input dojoType="dijit.form.NumberTextBox"  type="text" class="fullside" id="amount_price" name="amount_price" onkeyup="grandTotal();" /></td>
								<td style="padding-right: 5px;padding-left: 5px;">Remarks</td>
								<td><input dojoType="dijit.form.TextBox"  type="text" class="fullside" name="remarks" value="" /></td>
							</tr>	
							<tr>
								<td style="color: red">Discount Amount($)</td>
								<td><input dojoType="dijit.form.NumberTextBox" onkeyup="grandTotal();" type="text"  id="discount_value" name="discount_value" class="fullside"></td>
								<td style="padding-right: 5px;padding-left: 5px;">Discount(%)</td>
								<td><input onkeyup="grandTotal();" name="discount_percent" id="discount_percent" dojoType="dijit.form.NumberTextBox" class="fullside" >
								</td>
							</tr>
							<tr>
								<td style="color: red">Refundable Deposit($)</td>
								<td><input dojoType="dijit.form.NumberTextBox" onkeyup="grandTotal();" type="text" class="fullside" id="amount_f_d" name="amount_f_d"></td>
								<td style="padding-right: 10px;padding-left: 10px;">Remarks</td>
								<td><input dojoType="dijit.form.TextBox"  type="text" class="fullside" name="remarks"  value="" /></td>
							</tr>
							<tr>
								<td style="color: red">Long DAST($)</td>
								<td><input dojoType="dijit.form.NumberTextBox" onkeyup="grandTotal();" type="text" class="fullside" name="longdast" id="longdast" onkeyup="depositPrice();" value="0" /></td>
								<td style="padding-right: 10px;padding-left: 10px;">Remarks</td>
								<td><input dojoType="dijit.form.TextBox"  type="text" class="fullside" name="remarks"  value="" /></td>
							</tr>
							<tr>
								<td>Grand Total($)</td>
								<td>
								    <input dojoType="dijit.form.NumberTextBox"  type="text"  id="grand_total" name="grand_total" class="fullside" readonly="readonly">
								</td>
								<td>VAT No(Owner)</td>
								<td>
								    <input dojoType="dijit.form.TextBox"  type="text"  id="vat_owner" name="vat_owner" class="fullside" >
								</td>
								
							</tr>	
							<tr>
								<td>Paid Amount($)</td>
								<td>
								    <input dojoType="dijit.form.NumberTextBox" onkeyup="grandTotal();"  type="text"  id="paid_amount" name="paid_amount" class="fullside" >
								</td>
								<td>VAT No(Customer)</td>
								<td>
								    <input dojoType="dijit.form.TextBox"  type="text"  id="vat_customer" name="vat_customer" class="fullside" >
								</td>
							</tr>	
							<tr>
								<td>Due Amount($)</td>
								<td>
								    <input dojoType="dijit.form.NumberTextBox"  type="text"  id="due_amount" name="due_amount" class="fullside" readonly="readonly">
								</td>
							</tr>				
							
						</table>
					</fieldset>
				</td>
				<td valign="top"  width="30%">
				<fieldset style="border:1px solid #FFF; "><legend align="center" ><strong>Agreement Information</strong></legend>
								<table width="100%" style="white-space: nowrap;">
										 <tr>
												<td width="100px">Agreement Date</td>
												<td align="right">
													<input onchange="setAgreementRef();" dojoType="dijit.form.DateTextBox" value="<?php echo date("Y-m-d");?>"  type="text" class="fullside" id="agreement_date" name="agreement_date" >
												</td>
											</tr>
											<tr>
												<td>Agreement Ref</td>
												<td align="right">
												<input type="hidden" dojoType="dijit.form.TextBox" name="customer_id" id="customer_id" value="" />
												 <input type="hidden" dojoType="dijit.form.TextBox" name="prefix_code" id="prefix_code" value="<?php echo $this->prefixed;?>" />
												<input type="hidden" dojoType="dijit.form.TextBox" name="lastagreement" id="lastagreement" value="<?php echo $this->lastagreement;?>" />
													<input readonly="readonly" dojoType="dijit.form.TextBox" value="<?php echo $this->agreement_ref;?>"  type="text" class="fullside" id="agreement_code" name="agreement_code" >
												</td>
											</tr>
																
									</table>
						</fieldset>
					<fieldset style="border:1px solid #FFF; "><legend align="center" ><strong>Special Notices</strong></legend>
								<table width="100%">
										 <tr>
												<td width="60%">
												2. Articles &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input style="width: 90px;" dojoType="dijit.form.TextBox"  type="text" class="fullside" id="article" name="article" value="11 th">
												</td>
												<td align="right">
													<span>To &nbsp;&nbsp;&nbsp;</span><input style="width: 90px;" dojoType="dijit.form.TextBox"  type="text" class="fullside" name="toart1_id"  value="33 rd" />
												</td>
											</tr>
											<tr>
												<td width="50%">
													4. No Driver &nbsp;&nbsp;<input style="width: 90px;" dojoType="dijit.form.TextBox"  type="text" class="fullside" id="art2_id" name="art2_id" value="13 th">
												</td>
												<td align="right"> 
													To &nbsp;&nbsp;&nbsp;<input style="width: 90px;" dojoType="dijit.form.TextBox"  type="text" class="fullside" name="toart2_id"  value="15 th" />
												</td>
											</tr>
											<tr>
												<td width="50%" align="center">
													&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input style="width: 90px;" dojoType="dijit.form.TextBox"  type="text" class="fullside" id="art3_id" name="art3_id" value="16 th">
												</td>
												<td align="right"> 
													To &nbsp;&nbsp;&nbsp;<input style="width: 90px;" dojoType="dijit.form.TextBox"  type="text" class="fullside" name="toart3_id"  value="17 th"/>
												</td>
											</tr>	
											<tr>
												<td colspan="2">&nbsp;</td>
											</tr>
											<tr>
												<td colspan="2">&nbsp;</td>
											</tr>					
									</table>
						</fieldset>
						<fieldset style="border:1px solid #FFF; "><legend align="center" ><strong>Service Include</strong></legend>
						<table width="100%">
							<tr>
								<td width="50%" colspan="2">Regular Maintenance</td>							
								<td width="50%" colspan="2">
									<select name="regular_maintanance" id="regular_maintanance" dojoType="dijit.form.FilteringSelect" class="fullside" >
									<option value="1">Yes</option>
									<option value="0">No</option>
									</select>
								</td>
							</tr>
							<tr>
								<td width="50%" colspan="2">Unlimited Mileage</td>
								<td width="50%" colspan="2"><select name="unlimited_mileage" id="unlimited_mileage" dojoType="dijit.form.FilteringSelect" class="fullside" >
								    <option value="1">Yes</option>
								    <option value="0">No</option>
									</select>
								</td>
							</tr>
							<tr>
								<td width="50%" colspan="2">Repair/Spare Parts</td>
								<td width="50%" colspan="2"><select name="repair_spare_part" id="repair_spare_part" dojoType="dijit.form.FilteringSelect" class="fullside" >
								    <option value="1">Yes</option>
								    <option value="0">No</option>
									</select>
								</td>
							</tr>
							<tr>
								<td width="50%" colspan="2">Insurance Coverage</td>
								<td width="50%" colspan="2"><select name="insurance_coverage" id="insurance_coverage" dojoType="dijit.form.FilteringSelect" class="fullside" >
								    <option value="1">Yes</option>
								    <option value="0">No</option>
									</select>
								</td>
					
							</tr>
							<tr>
								<td width="50%" colspan="2">Fuel</td>
								<td width="50%" colspan="2"><select name="fuel" id="fuel" dojoType="dijit.form.FilteringSelect" class="fullside" >
								    <option value="1">Yes</option>
								    <option value="0">No</option>
									</select>
								</td>
					
							</tr>
							<tr>
								<td width="50%" colspan="2">Fuel Full Tank</td>
								<td width="40%" colspan="2"><select name="fuel_full_tank" id="fuel_full_tank" dojoType="dijit.form.FilteringSelect" class="fullside" >
								    <option value="0">No</option>
								    <option value="1">Yes</option>								    
									</select>
								</td>				
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr><td></td></tr>
					</table>
					</fieldset>
				</td>
			</tr>
			<tr>
				<td colspan="3" align="center" >
					<input dojoType="dijit.form.Button" type="submit" id="btn_save_close" name="btn_save_close" label="Save&Close"  value="submit" >									
					<input dojoType="dijit.form.Button" type="submit" id="btn_save_new" name="save_new" label="Save&New"  value="submit" >									
					<!-- <input dojoType="dijit.form.Button" type="button" name="btn_save_close" label="Print Agreement"  value="submit" onclick="showReciept();" >	 -->								
				</td>
			</tr>
			
		</table>	
	</div>
</form>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog"  id="pop_make" style="width:100%" >
	<div id="divPrint" class="print">
	<div class="wrapper">
    <style type="text/css">
		.wrapper{width:1000px; height:auto; font-family:Calibri; font-weight: 600;}
		.wrapper tr{height: 22px;}
        .bhar{font-size: 24px;}
		td.border {
			border-bottom: 1px dashed cadetblue;
			border-top: none;
			border-left: none;
			border-right: none;
		}
		div #rpt_print{font-size:12px !important; margin:0 auto;}
		.style{
				line-height: 20px;font-size: 11px !important;
				font-family: 'Khmer OS Battambang';
			}
			th{padding: 5px;}
			.color{ color: #023FB3;}
			.fontsize14{font-size: 14px;}
		 
		 .fontsize{ font-size:10px !important; margin:0 auto;}
	</style>
        <table width="100%" style="border-collapse:collapse;font-size: 12px;margin-top:10px;float: left;">
            <tr height="20">
				<td colspan="8" style="text-align:center; font-size: 16px;"><strong><span class="bhar">V</span>EHICLE&nbsp;<span class="bhar">R</span>ENTAL&nbsp; <span class="bhar">A</span>GREEMENT &nbsp;</strong></td>
			</tr>
			<tr >
			    <td colspan="8" class="fontsize14"><strong>I. Party A(Hereinafter refers to as the "Vehicle Owner")</strong></td>
			</tr>
			<tr>
			    <td>Name:</td><td style="color:#023FB3;">Lyna Tan</td>
			    <td>Title:</td><td class="color">Director General/Founder</td>
			    <td>Sex:</td><td class="color">Female</td>
			    <td>Nationality:</td><td class="color">Cambodian</td>
			</tr>
        </table >
        <table width="100%" style="border-collapse:collapse;font-size: 12px;margin-top:10px;" border="1">
            <tr>
			     <td colspan="7" class="fontsize14">&nbsp;<strong>II. Party B(Hereinafter refers to as the "Vehicle Renter")</strong></td>
			</tr>
			<tr>
				  <td colspan="2" style="text-align: center;">&nbsp;&nbsp;Renter Information </td>
				  <td colspan="2" style="text-align: center;">Local Address Information</td>
				  <td colspan="2" style="text-align: center;">International Address Infomation</td>
				  <td rowspan="8" align="right" valign="top"><div style="width:90px; height: 120px; border: 1px solid #000;"></div></td>
			</tr>
			<tr>
				  <td >&nbsp;Mr</td><td class="color">&nbsp;Mr Ma Hea</td>
				  <td >&nbsp;Adress</td><td class="color">&nbsp;18ABE, Street 460,</td>
				  <td>&nbsp;Adress</td><td class="color">&nbsp;18ABE, Street 460,</td>
			</tr>
			<tr>
				  <td >&nbsp;Title:</td><td class="color">&nbsp;Teacher of IT</td>
				  <td >&nbsp;Town/City:</td><td class="color">&nbsp;Phnom Penh</td>
				  <td>&nbsp;Town/City:</td><td class="color">&nbsp;Phnom Penh</td>
			</tr>
			<tr>
				  <td >&nbsp;DOB:</td><td class="color">&nbsp;02 September 1973</td>
				  <td >&nbsp;Province:</td><td class="color">&nbsp;Phnom Penh</td>
				  <td>&nbsp;State:</td><td class="color">&nbsp;Phnom Penh</td>
			</tr>
			<tr>
				  <td >&nbsp;POB:</td><td class="color">&nbsp;Svay Rieng Province</td>
				  <td >&nbsp;Zip Code:</td><td class="color">&nbsp;855</td>
				  <td>&nbsp;Zip Code:</td><td class="color">&nbsp;855</td>
			</tr>
			<tr>
				  <td >&nbsp;Nat:</td><td class="color">&nbsp;Cambodian</td>
				  <td >&nbsp;HP No:</td><td class="color">&nbsp;012554247</td>
				  <td>&nbsp;HP No:</td><td class="color">&nbsp;012554247</td>
			</tr>
			<tr>
				  <td >&nbsp;Org/Co:</td><td class="color">&nbsp;Un. Of Svay Rieng</td>
				  <td >&nbsp;E-mail:</td><td class="color">&nbsp;info@lyna-carrental.com</td>
				  <td>&nbsp;E-mail:</td><td class="color">&nbsp;info@lyna-carrental.com</td>
			</tr>
			<tr>
				  <td >&nbsp;</td><td class="color">&nbsp;</td>
				  <td >&nbsp;Website:</td><td class="color">&nbsp;www.lyna-CarRental.Com</td>
				  <td>&nbsp;Website:</td><td class="color">&nbsp;www.lyna-CarRental.com</td>
			</tr>
        </table>
        <div style="margin-top: 10px; border: 1px solid #000;">
         <table width="100%"  style="border-collapse:collapse;font-size: 12px;margin-top:10px;"  >
            <tr>
			     <td colspan="8" class="fontsize14">&nbsp;<strong>III. Documents Deposit</strong></td>
			</tr>
			<tr>
				  <td >&nbsp;1. Original Passport:
				       <label class="color">&nbsp;Yes</label>
				  </td>
				  <td >&nbsp;No.:</td><td class="color">&nbsp;KHM-12-00008987</td>
				  <td style="text-align: right;">&nbsp;Date Of Issue:</td><td class="color">&nbsp;12 July 2011</td>
				  <td style="text-align: right;">&nbsp;Date Of Expire:</td><td class="color">&nbsp;12 July 2015</td>
			</tr>
			<tr>
				  <td>&nbsp;2. Visa :
				       <label class="color">Yes</label>
				  </td>
				  <td>&nbsp;No.:</td><td class="color">&nbsp;KHM-12-00008987</td>
				  <td style="text-align: right;">&nbsp;Date Of Issue:</td><td class="color">&nbsp;12 July 2011</td>
				  <td style="text-align: right;">&nbsp;Date Of Expire:</td><td class="color">&nbsp;12 July 2015</td>
			</tr>
			<tr>
				  <td>&nbsp;3. Original ID Card :
				       <label class="color">Yes</label>&nbsp;
				  </td>
				  <td >&nbsp;No.:</td><td class="color">&nbsp;KHM-12-00008JHK-099</td>
				  <td style="text-align: right;">&nbsp;Date Of Issue:</td><td class="color">&nbsp;12 July 2011</td>
				  <td style="text-align: right;">&nbsp;Date Of Expire:</td><td class="color">&nbsp;12 July 2015</td>
			</tr>
			<tr>
				  <td >&nbsp;4. Family Book : No
				  </td>
				  <td >&nbsp;No.:</td><td class="color">&nbsp;KHM-12-00008JHK-099</td>
				  <td style="text-align: right;">&nbsp;Date Of Issue:</td><td class="color">&nbsp;12 July 2011</td>
				  <td style="text-align: right;">&nbsp;Date Of Expire:</td><td class="color">&nbsp;12 July 2015</td>
			</tr>
        </table>
        <table width="100%" style="border-collapse:collapse;font-size: 12px;margin-top:10px;" border="1" >
            <tr>
                <td colspan="7" class="fontsize14"><strong>&nbsp;IV. Vehicle Information</strong></td>
            </tr>
            <tr>
                <td>&nbsp;Vehicle ID: </td><td style="color: red;">&nbsp;2012</td>
                <td>&nbsp;Color: </td><td style="color: red;">&nbsp;Gray</td>
                <td>&nbsp;No of seats: </td><td style="color: red;">&nbsp;Gray</td>
                <td rowspan="5" width="180px">
                	<div style="width: 100%;border: 1px solid #000;"></div>
                	<div style="width: 100%;border: 1px solid #000;"></div>
                </td>
            </tr>
            <tr>
                <td>&nbsp;Year: </td><td style="color: red;">&nbsp;SSK 17" Touch Screen</td>
                <td>&nbsp;Engine No: </td><td style="color: red;">&nbsp;3S-5656-989-098</td>
                <td>&nbsp;Transmission: </td><td style="color: red;">&nbsp;3S-5656-989-098</td>
            </tr>
            <tr>
                <td>&nbsp;Make: </td><td style="color: red;">&nbsp;5-Year Child</td>
                <td>&nbsp;Chassis No: </td><td style="color: red;">&nbsp;None</td>
                <td>&nbsp;Type: </td><td style="color: red;">&nbsp;None</td>
            </tr>
            <tr>
                <td>&nbsp;Model: </td><td style="color: red;">&nbsp;5-Year Child</td>
                <td>&nbsp;Frame No</td><td style="color: red;">&nbsp;None</td>
                <td colspan="2"></td>
            </tr>
            <tr>
                <td>&nbsp;Submodel: </td><td style="color: red;">&nbsp;5-Year Child</td>
                <td>&nbsp;Plate No</td><td style="color: red;">&nbsp;None</td>
                <td colspan="2"></td>
            </tr>
        </table>
        <table width="100%" style="border-collapse:collapse;font-size: 12px;margin-top:10px;" >
            <tr>
                <td colspan="8" class="fontsize14"><strong>&nbsp;V. Rental Period Information and Payment Mode(All the related payment must be paid in advance)</strong></td>
            </tr>
            <tr style="text-align:center;">
                <th colspan="2" class="bordertd">&nbsp;Rental Period Information</th>
                <th class="bordertd">&nbsp;Items Description</th>
                <th class="bordertd">&nbsp;Day<sup>2</sup> </th>
                <th class="bordertd">&nbsp;Month<sup>2</sup></th>
                <th class="bordertd">&nbsp;U Price</th>
                <th class="bordertd">&nbsp;Total</th>
                <th class="bordertd">&nbsp;Remarks</th>
            </tr>
            <?php  for($i=1;$i<4;$i++){?>
            <tr>
                <td class="bordertd">&nbsp;The period of : </td>
                <td class="bordertd" style="color: red;">&nbsp;10day(s)</td>
                <td class="bordertd">&nbsp;<?php echo $i?>. Child Car Seat Rental </td>
                <td style="color: red;"class="bordertd">&nbsp;5</td>
                <td style="color: red;"class="bordertd">&nbsp;X</td>
                <td style="color: red;"class="bordertd">&nbsp;$5.00</td>
                <td style="color: red;"class="bordertd">&nbsp;$25.00</td>
                <td class="bordertd">&nbsp;</td>
            </tr>
            <?php }?>
            <tr>
                <td >&nbsp; </td>
                <td ></td>
                <td >&nbsp; </td>
                <td style="color: red;"class="bordertd" colspan="2">&nbsp;&nbsp;&nbsp;Sub Total:</td>
                <td style="color: red;background: rgb(212, 210, 210)"class="bordertd">&nbsp;$15.00</td>
                <td style="color: red;background: rgb(212, 210, 210)"class="bordertd">&nbsp;$975.00</td>
                <td class="bordertd">&nbsp;</td>
            </tr>
            <tr>
                <td >&nbsp; </td>
                <td ></td>
                <td >&nbsp; </td>
                <td style="color: red;" class="bordertd" colspan="2">&nbsp;&nbsp;&nbsp;Grand Total:</td>
                <td style="color: red;background: rgb(212, 210, 210)"class="bordertd">&nbsp;$15.00</td>
                <td style="color: red;background: rgb(212, 210, 210)"class="bordertd">&nbsp;$975.00</td>
                <td class="bordertd">&nbsp;</td>
            </tr>
        </table>
        </div>
        <div>
         <table style="width: 100%;" cellspacing="25">
            <tr >
                <td style="width:33%;color: rgb(28, 108, 198);font-weight: bold;">Renter's</td>
                <td style="width:33%;color: rgb(28, 108, 198);text-align:center;font-weight: bold;">Owner's Witness</td>
                <td style="font-weight: bold;text-align:center;">Agreement date:<font color="red">15 July 2012</font></td>
            </tr>
             <tr height="60">
                <td style="color: rgb(28, 108, 198);font-weight: bold;border-top: 1px solid rgb(28, 108, 198);"> Signature/Name of Renter</td>
                <td style="color: rgb(28, 108, 198);text-align:center;font-weight: bold;border-top: 1px solid rgb(28, 108, 198);">Signature/Name</td>
                <td style="text-align:center;color: rgb(28, 108, 198);font-weight: bold;border-top: 1px solid rgb(28, 108, 198);">Signature/Name of Owner <br/> LYNA TAN(Mrs)</td>
            </tr>
         </table>
       </div>
	</div>
	</div>
	<input type="button" value="បោះពុម្ព" label="បោះពុម្ព" id="print" dojoType="dijit.form.Button" 
				   iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="doPrint();"/>
</div>
</div>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}

function showReciept(){
	//var client_id = dijit.byId('owner_name').get('value');
	//if(client_id==""){
	//	alert("No Result To Show! Please Choose Client and Try again");
//	}else{
// 		var client_name = dijit.byId('client_id').attr('displayedValue');
// 		var arrays = client_name.split(',');
		
// 		for(var i=0;i<1;i++){
// 			document.getElementById('lbl_group_member').innerHTML = arrays[0];
// 		}
		//document.getElementById('lbl_cus_name').innerHTML = dijit.byId('owner_name').attr('displayedValue');
		//document.getElementById('lbl_reciept_no').innerHTML = dijit.byId('reciept_no').attr('displayedValue');
// 		document.getElementById('lbl_group_code').innerHTML = dijit.byId('client_code').attr('displayedValue');
//		document.getElementById('lbl_loan_number').innerHTML = dijit.byId('loan_number').attr('displayedValue');
//		document.getElementById('lbl_branch_id').innerHTML = dijit.byId('branch_id').attr('displayedValue');
//		document.getElementById('lbl_co_id').innerHTML = dijit.byId('co_id').attr('displayedValue');
//		document.getElementById('lbl_collect_date').innerHTML = dijit.byId('collect_date').attr('displayedValue');
//		document.getElementById('lbl_priciple_amount').innerHTML = dijit.byId('priciple_amount').attr('displayedValue');
//		document.getElementById('lbl_os_amount').innerHTML = dijit.byId('os_amount').attr('displayedValue');
//		document.getElementById('lbl_total_interest').innerHTML = dijit.byId('total_interest').attr('displayedValue');
//	 	document.getElementById('lbl_penalize_amount').innerHTML = dijit.byId('penalize_amount').attr('displayedValue');
//	 	document.getElementById('lbl_total_payment').innerHTML = dijit.byId('total_payment').attr('displayedValue');
//	 	document.getElementById('lbl_note').innerHTML = dijit.byId('note').attr('displayedValue');
//	 	document.getElementById('lbl_service_charge').innerHTML = dijit.byId('service_charge').attr('displayedValue');
//	 	document.getElementById('lbl_amount_receive').innerHTML = dijit.byId('amount_receive').attr('displayedValue');
//	 	document.getElementById('lbl_amount_return').innerHTML = dijit.byId('amount_return').attr('displayedValue');
	//	dijit.byId('frm_client').show();
		//submitData();
		dijit.byId('pop_make').show();
	//}
}
</script>