<title>Edit Location Type</title>
<form id='add_locationtype' action="<?php echo $this->url(array('module'=>'location','controller'=>'locationtype','action'=>'edit')); ?>" enctype="application/x-www-form-urlencoded" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table  width="450px" style="margin:0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend ><strong>Edit Location Type</strong></legend>
					<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
							<td valign="top">Location Type<input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="id" name="id" value="<?php echo $this->row['id'];?>" type="hidden"></td>
							<td valign="top" ><input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="loation_type" name="loation_type" value="<?php echo $this->row['title'];?>" type="text"></td>
						</tr>
						<tr>
							<td valign="top">Status</td>
							<td valign="top"><select name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside">
								  <option value="1" <?php if($this->row['status']==1){echo'selected="selected"';}?>>Active</option>
								  <option value="0" <?php if($this->row['status']==0){echo'selected="selected"';}?>>Deactive</option>
								</select>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
							<input type="reset" label="Clear" dojoType="dijit.form.Button" 
								 iconClass="dijitIconClear" /> 
							<input type="submit" value="SAVE_NEW" label="Edit" id="save_new" dojoType="dijit.form.Button" name="save_new"
								 iconClass="dijitEditorIcon dijitEditorIconSave"/> 
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>