<title>Add Rank Day</title>
<script>
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.CheckBox");
</script>
<form id="add_province" action="<?php echo $this->url(array('module'=>'other','controller'=>'day','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>
	<table cellspacing="20" style="margin: 0 auto; width: 600px">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong>Add Rank Day</strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table style="margin: 0 auto; width:100%;" cellspacing="10">
									<tr>
										<td>Package Day Name</td>
										<td><input dojoType="dijit.form.ValidationTextBox" class="fullside" required="true" id="package_day" name="package_day" value="" type="text"></td>
									</tr>
									<tr>
										<td>From Amount Day</td>
										<td><input dojoType="dijit.form.NumberTextBox" required="true" class="fullside" id="from_amount" name="from_amount" value="" type="text"></td>
									</tr>
									<tr>
										<td>To Amount Day</td>
										<td><input dojoType="dijit.form.NumberTextBox" required="true" class="fullside" id="to_amount" name="to_amount" value="" type="text"></td>
									</tr>
									<tr>
										<td>Is More Than</td>
										<td><input onclick="CheckIsMore();" dojoType="dijit.form.CheckBox" class="fullside" id="is_morethan" name="is_morethan" value="" type="text"></td>
									</tr>
									<tr>
										<td>More Than</td>
										<td><input dojoType="dijit.form.NumberTextBox" readonly="readonly" class="fullside" id="morethan_amount" name="morethan_amount" value="" type="text"></td>
									</tr>
									<tr>
										<td>Status</td>
										<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true" missingMessage="Invalid Module!" class="fullside">
											    <option value="1" label="Active">Active</option>
											    <option value="0" label="Deactive">Deactive</option>
											</select>
										</td>
									</tr>
									<tr>
										<td colspan="2" align="center">
											<input type="reset" value="សំអាត" label="Clear"dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
											<input type="submit" value="save_close" name="save_close" label="Save&Close" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
											<input type="submit" value="save_new" name="save_new" label="Save&New" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>
<script>
function CheckIsMore(){
	if(dijit.byId('is_morethan').checked){
		dijit.byId('from_amount').attr('value',0);
		dijit.byId('from_amount').set('readOnly',true);
		dijit.byId('to_amount').attr('value',0);
		dijit.byId('to_amount').set('readOnly',true);
		dijit.byId('morethan_amount').set('readOnly',false);
		}else{
			dijit.byId('from_amount').set('readOnly',false);
			dijit.byId('to_amount').set('readOnly',false);
			dijit.byId('morethan_amount').attr('value',0);
			dijit.byId('morethan_amount').set('readOnly',true);
		}
}
</script>