<!DOCTYPE html>
<html>
<head>
      <style>
            .wrapp{width: 100%;height: 100%;}
			table tr td input {
			    height: 0px !important;
				}
			.bordertd{border: 1px solid #000;}
			.bhar{font-size: 18px;}
      </style>
</head>
<body>
     <div class="wrapp" style="width: 21cm;height:29.7cm; margin: 0 auto;padding:0.5cm; border:1px dotted #000;">
        <table width="100%" style="border-collapse:collapse;font-size: 12px;margin-top:10px;float: left;">
            <tr height="20">
				<td colspan="8" style="text-align:center;"><strong><span class="bhar">C</span>HILD&nbsp;<span class="bhar">C</span>AR&nbsp; <span class="bhar">S</span>EAT &nbsp;<span class="bhar">R</span>ENTAL &nbsp;<span class="bhar">A</span>GREEMENT&nbsp;</strong></td>
			</tr>
			<tr >
			    <td colspan="8"><strong>I. Party A(Hereinafter refers to as Owner of the Child Car Seat)</strong></td>
			</tr>
			<tr>
			    <td>Name:</td><td style="color:red;">Lyna Tan</td>
			    <td>Title:</td><td style="color:red;">Director General/Founder</td>
			    <td>Sex:</td><td style="color:red;">Female</td>
			    <td>Nationality:</td><td style="color:red;">Cambodian</td>
			</tr>
        </table >
        <table width="100%" style="border-collapse:collapse;font-size: 12px;margin-top:10px;">
            <tr>
			     <td colspan="6">&nbsp;<strong>II. Party B(Hereinafter refers to as Renter)</strong></td>
			</tr>
			<tr>
				  <td colspan="2" style="text-align: center;">&nbsp;&nbsp;Renter Information </td>
				  <td colspan="2" style="text-align: center;">Local Address Information</td>
				  <td colspan="2" style="text-align: center;">International Address Infomation</td>
			</tr>
			<tr>
				  <td >&nbsp;Mr</td><td style="color:red;">&nbsp;Mr Ma Hea</td>
				  <td >&nbsp;Adress</td><td style="color:red;">&nbsp;18ABE, Street 460,</td>
				  <td>&nbsp;Adress</td><td style="color:red;">&nbsp;18ABE, Street 460,</td>
			</tr>
			<tr>
				  <td >&nbsp;Title:</td><td style="color:red;">&nbsp;Teacher of IT</td>
				  <td >&nbsp;Town/City:</td><td style="color:red;">&nbsp;Phnom Penh</td>
				  <td>&nbsp;Town/City:</td><td style="color:red;">&nbsp;Phnom Penh</td>
			</tr>
			<tr>
				  <td >&nbsp;DOB:</td><td style="color:red;">&nbsp;02 September 1973</td>
				  <td >&nbsp;Province:</td><td style="color:red;">&nbsp;Phnom Penh</td>
				  <td>&nbsp;State:</td><td style="color:red;">&nbsp;Phnom Penh</td>
			</tr>
			<tr>
				  <td >&nbsp;POB:</td><td style="color:red;">&nbsp;Svay Rieng Province</td>
				  <td >&nbsp;Zip Code:</td><td style="color:red;">&nbsp;855</td>
				  <td>&nbsp;Zip Code:</td><td style="color:red;">&nbsp;855</td>
			</tr>
			<tr>
				  <td >&nbsp;Nat:</td><td style="color:red;">&nbsp;Cambodian</td>
				  <td >&nbsp;HP No:</td><td style="color:red;">&nbsp;012554247</td>
				  <td>&nbsp;HP No:</td><td style="color:red;">&nbsp;012554247</td>
			</tr>
			<tr>
				  <td >&nbsp;Org/Co:</td><td style="color:red;">&nbsp;Un. Of Svay Rieng</td>
				  <td >&nbsp;E-mail:</td><td style="color:red;">&nbsp;info@lyna-carrental.com</td>
				  <td>&nbsp;E-mail:</td><td style="color:red;">&nbsp;info@lyna-carrental.com</td>
			</tr>
			<tr>
				  <td >&nbsp;</td><td style="color:red;">&nbsp;</td>
				  <td >&nbsp;Website:</td><td style="color:red;">&nbsp;www.lyna-CarRental.Com</td>
				  <td>&nbsp;Website:</td><td style="color:red;">&nbsp;www.lyna-CarRental.com</td>
			</tr>
        </table>
        <div style="margin-top: 10px;">
         <table width="100%"  style="border-collapse:collapse;font-size: 12px;margin-top:10px;"  >
            <tr>
			     <td colspan="8">&nbsp;<strong>III. Documents Deposit</strong></td>
			</tr>
			<tr>
				  <td >&nbsp;1. Original Passport:
				       &nbsp;<input type="checkbox" name="year" value="checked">Yes
				       &nbsp;&nbsp;<input type="checkbox" name="year" value="checked">No
				  </td>
				  <td >&nbsp;No.:</td><td style="color:red;">&nbsp;KHM-12-00008987</td>
				  <td style="text-align: right;">&nbsp;Date Of Issue:</td><td style="color:red;">&nbsp;12 July 2011</td>
				  <td style="text-align: right;">&nbsp;Date Of Expire:</td><td style="color:red;">&nbsp;12 July 2015</td>
			</tr>
			<tr>
				  <td >&nbsp;2. Visa :
				       &nbsp;<input type="checkbox" name="vyes" value="checked">Yes
				       &nbsp;&nbsp;<input type="checkbox" name="vno" value="checked">No
				  </td>
				  <td >&nbsp;No.:</td><td style="color:red;">&nbsp;KHM-12-00008987</td>
				  <td style="text-align: right;">&nbsp;Date Of Issue:</td><td style="color:red;">&nbsp;12 July 2011</td>
				  <td style="text-align: right;">&nbsp;Date Of Expire:</td><td style="color:red;">&nbsp;12 July 2015</td>
			</tr>
			<tr>
				  <td >&nbsp;3. Original ID Card :
				       &nbsp;<input type="checkbox" name="oyes" value="checked">Yes
				       &nbsp;&nbsp;<input type="checkbox" name="ono" value="checked">No
				  </td>
				  <td >&nbsp;No.:</td><td style="color:red;">&nbsp;KHM-12-00008JHK-099</td>
				  <td style="text-align: right;">&nbsp;Date Of Issue:</td><td style="color:red;">&nbsp;12 July 2011</td>
				  <td style="text-align: right;">&nbsp;Date Of Expire:</td><td style="color:red;">&nbsp;12 July 2015</td>
			</tr>
			<tr>
				  <td >&nbsp;4. Family Book :
				       &nbsp;<input type="checkbox" name="fyes" value="checked">Yes
				       &nbsp;&nbsp;<input type="checkbox" name="fno" value="checked">No
				  </td>
				  <td >&nbsp;No.:</td><td style="color:red;">&nbsp;KHM-12-00008JHK-099</td>
				  <td style="text-align: right;">&nbsp;Date Of Issue:</td><td style="color:red;">&nbsp;12 July 2011</td>
				  <td style="text-align: right;">&nbsp;Date Of Expire:</td><td style="color:red;">&nbsp;12 July 2015</td>
			</tr>
        </table>
        <table width="100%" style="border-collapse:collapse;font-size: 12px;margin-top:10px;" >
            <tr>
                <td colspan="6"><strong>&nbsp;IV. Child Car Seat Information</strong></td>
            </tr>
            <tr>
                <td>&nbsp;Year of Product: </td><td style="color: red;">&nbsp;2012</td>
                <td>&nbsp;Color: </td><td style="color: red;">&nbsp;Gray</td>
                <td rowspan="2" style="text-align: center;border:1px solid #000;" >&nbsp;Comes into effect front:<font color="red">&nbsp;12 July 2011</font></td>
            </tr>
            <tr>
                <td>&nbsp;Make/Model: </td><td style="color: red;">&nbsp;SSK 17" Touch Screen</td>
                <td>&nbsp;Serial No.: </td><td style="color: red;">&nbsp;3S-5656-989-098</td>
            </tr>
            <tr>
                <td>&nbsp;Size: </td><td style="color: red;">&nbsp;5-Year Child</td>
                <td>&nbsp;Others(specify): </td><td style="color: red;">&nbsp;None</td>
                <td  style="text-align: center;border:1px solid #000;">&nbsp;Expected date/time of return:<font color="red">&nbsp;12 July 2012, 5:00 AM/PM.</font></td>
            </tr>
        </table>
        <table width="100%" style="border-collapse:collapse;font-size: 12px;margin-top:10px;" >
            <tr>
                <td colspan="8"><strong>&nbsp;V. Rental Period Information and Payment Mode(All the related payment must be paid in advance)</strong></td>
            </tr>
            <tr style="text-align:center;">
                <th colspan="2" class="bordertd">&nbsp;Rental Period Information</th>
                <th class="bordertd">&nbsp;Items Description</th>
                <th class="bordertd">&nbsp;Day<sup>2</sup> </th>
                <th class="bordertd">&nbsp;Month<sup>2</sup></th>
                <th class="bordertd">&nbsp;U Price</th>
                <th class="bordertd">&nbsp;Total</th>
                <th class="bordertd">&nbsp;Remarks</th>
            </tr>
            <?php  for($i=1;$i<4;$i++){?>
            <tr>
                <td class="bordertd">&nbsp;The period of : </td>
                <td class="bordertd" style="color: red;">&nbsp;10day(s)</td>
                <td class="bordertd">&nbsp;<?php echo $i?>. Child Car Seat Rental </td>
                <td style="color: red;"class="bordertd">&nbsp;5</td>
                <td style="color: red;"class="bordertd">&nbsp;X</td>
                <td style="color: red;"class="bordertd">&nbsp;$5.00</td>
                <td style="color: red;"class="bordertd">&nbsp;$25.00</td>
                <td class="bordertd">&nbsp;</td>
            </tr>
            <?php }?>
            <tr>
                <td >&nbsp; </td>
                <td ></td>
                <td >&nbsp; </td>
                <td style="color: red;"class="bordertd" colspan="2">&nbsp;&nbsp;&nbsp;Sub Total:</td>
                <td style="color: red;background: rgb(212, 210, 210)"class="bordertd">&nbsp;$15.00</td>
                <td style="color: red;background: rgb(212, 210, 210)"class="bordertd">&nbsp;$975.00</td>
                <td class="bordertd">&nbsp;</td>
            </tr>
            <tr>
                <td >&nbsp; </td>
                <td ></td>
                <td >&nbsp; </td>
                <td style="color: red;" class="bordertd" colspan="2">&nbsp;&nbsp;&nbsp;Grand Total:</td>
                <td style="color: red;background: rgb(212, 210, 210)"class="bordertd">&nbsp;$15.00</td>
                <td style="color: red;background: rgb(212, 210, 210)"class="bordertd">&nbsp;$975.00</td>
                <td class="bordertd">&nbsp;</td>
            </tr>
        </table>
        </div>
        <div>
         <table style="width: 100%;" cellspacing="25">
            <tr >
                <td style="width:33%;color: rgb(28, 108, 198);font-weight: bold;">Renter's</td>
                <td style="width:33%;color: rgb(28, 108, 198);text-align:center;font-weight: bold;">Owner's Witness</td>
                <td style="font-weight: bold;text-align:center;">Agreement date:<font color="red">15 July 2012</font></td>
            </tr>
             <tr height="60">
                <td style="color: rgb(28, 108, 198);font-weight: bold;border-top: 1px solid rgb(28, 108, 198);"> Signature/Name of Renter</td>
                <td style="color: rgb(28, 108, 198);text-align:center;font-weight: bold;border-top: 1px solid rgb(28, 108, 198);">Signature/Name</td>
                <td style="text-align:center;color: rgb(28, 108, 198);font-weight: bold;border-top: 1px solid rgb(28, 108, 198);">Signature/Name of Owner <br/> LYNA TAN(Mrs)</td>
            </tr>
         </table>
       </div>
     </div>
</body>
</html>