<!DOCTYPE html>
<html>
<head>
   <style type="text/css">
      .wrapp{ width: 100%; height: 100%;}
      .h_left{width:40%;float:left;}
      .h_right{width:40%;float:right;}
      .conten{margin-top:20px;}
      table tr .totalbr{
			border: 1px solid #000;
		}		
    </style>
</head>
<body>
  <div class="wrapp" style="width: 21cm;height:29.7cm; margin: 0 auto;padding:0.5cm; border:1px dotted #000;">
    <div class="header">
         <h1 style=" text-align:center;height:40px; font-size:16px; font-family:'Khmer MEF2'">វិក័យប័ត្រ  INVOICE</h1>
    </div>
    <div class="header_tow">
           <table id="exportExcel" style="border-collapse:collapse;font-size: 12px;"  bordercolor="black" width="100%">
				    <tbody>
					<tr>
						<th>
							<table style="border-collapse:collapse;font-size: 12px; width:70% ;text-align: left; border:1px solid #000;padding:5px;" cellpadding="5 ">
								<tr><td colspan="2" style="border-bottom:1px solid #ccc;text-align: left;background-color:  rgb(27, 86, 227);color:rgb(254, 250, 250);"><strong>&nbsp;Customer</strong></td></tr>
						        <tr><td >&nbsp;Mrs. Chris Denogales :</td><td>......Alibarbar............</td></tr>
						        <tr><td >&nbsp;Demogalesphoto </td><td>......Alibarbar............</td> </tr>
						        <tr><td >&nbsp;Mrs. Chris Denogales :</td><td>......Alibarbar............</td></tr>
					            <tr><td >&nbsp;Demogalesphoto </td><td>......Alibarbar............</td> </tr>
					            <tr><td >&nbsp;Mrs. Chris Denogales :</td><td>......Alibarbar............</td></tr>
				       	 	</table>
				        </th>
						<th>
							<table style="border-collapse:collapse;font-size: 12px;float: right;text-align: left; width:70% ;" align="center" >
						        <tr><td >QUOTE ID:</td><td style="border: 1px solid #000;">......Alibarbar............</td></tr>
						        <tr><td > CUSTOMER ID </td><td style="border: 1px solid #000;">......Alibarbar............</td> </tr>
						        <tr><td >VALID UNITIL :</td><td style="border: 1px solid #000;">......Alibarbar............</td></tr>
					            <tr><td > Plate No </td><td style="border: 1px solid #000;">......Alibarbar............</td> </tr>
					            <tr><td >Ref. No. :</td><td style="color: red;">......Alibarbar............</td></tr>
				       	 	</table>
						</th>
					</tr>
				    <tr >
				    </tr>
				   </tbody>
			</table>
    </div>
   
    <div class="conten">
     <hr size="3" style="background:#000;" />
        <table style="border-collapse:collapse;font-size: 12px;margin-top:10px;float: left;"   bordercolor="black" width="100%">
		  <tr  >
		     <th rowspan="2" class="totalbr">No</th>
		     <th rowspan="2" class="totalbr" >Items Description</th> 
		     <th colspan="2" class="totalbr">Period Of Invoice</th>
		     <th colspan="2" class="totalbr">Price In US$</th>
		     <th rowspan="2" class="totalbr">Remarks</th>
		  </tr>
		  <tr >
		     <th class="totalbr">From</th>
		     <th class="totalbr">To</th>
		     <th class="totalbr">U Price</th>
		     <th class="totalbr">Total</th>
		  </tr>
		  <?php  for($i=1;$i<10;$i++){?>
		  <tr>
		     <td class="totalbr">&nbsp;<?php echo $i;?></td>
		     <td class="totalbr">&nbsp;Vehicle Rental</td>
		     <td style="color:red" class="totalbr">&nbsp;27 Novermber 12</td>
		     <td style="color:red" class="totalbr">&nbsp;27 Novermber 12</td>
		     <td style="color:red" class="totalbr">&nbsp;$30.00</td>
		     <td style="color:red" class="totalbr">&nbsp;$150.00</td>
		     <td class="totalbr">&nbsp;Appear only when selected!</td>
		  </tr>
		  <?php }?>
		  <tr>
			  <td ></td>
			  <td></td>
			  <td></td>
			  <td class="totalbr">&nbsp;Sub Total:</td>
			  <td style="color:red;"class="totalbr">&nbsp;$30.00</td>
			  <td style="color:red;"class="totalbr">&nbsp;$150.00</td>
			  <td class="totalbr">&nbsp;</td>
		  </tr>
		  <tr>
			  <td ></td>
			  <td></td>
			  <td></td>
			  <td class="totalbr">&nbsp;Discount %:</td>
			  <td style="color:red;"class="totalbr">&nbsp;$30.00</td>
			  <td style="color:red;"class="totalbr">&nbsp;$150.00</td>
			  <td class="totalbr">&nbsp;</td>
		  </tr>
		  <tr>
			  <td ></td>
			  <td></td>
			  <td></td>
			  <td class="totalbr">&nbsp;VAT(10%):</td>
			  <td style="color:red;"class="totalbr">&nbsp;$30.00</td>
			  <td style="color:red;"class="totalbr">&nbsp;$150.00</td>
			  <td class="totalbr">&nbsp;</td>
		  </tr>
		  <tr>
			  <td ></td>
			  <td></td>
			  <td></td>
			  <td class="totalbr">&nbsp;Net Pay:</td>
			  <td style="color:red;"class="totalbr">&nbsp;$30.00</td>
			  <td style="color:red;"class="totalbr">&nbsp;$150.00</td>
			  <td class="totalbr">&nbsp;</td>
		  </tr>
	   </table>
    </div>
    <div>
         <table style="width: 100%;" cellspacing="25">
            <tr >
                <td style="width:33%;color: rgb(28, 108, 198);font-weight: bold;">Renter's</td>
                <td style="width:33%;color: rgb(28, 108, 198);text-align:center;font-weight: bold;">Owner's Witness</td>
                <td style="font-weight: bold;text-align:center;">Agreement date:<font color="red">15 July 2012</font></td>
            </tr>
             <tr height="60">
                <td style="color: rgb(28, 108, 198);font-weight: bold;border-top: 1px solid rgb(28, 108, 198);"> Signature/Name of Renter</td>
                <td style="color: rgb(28, 108, 198);text-align:center;font-weight: bold;border-top: 1px solid rgb(28, 108, 198);">Signature/Name</td>
                <td style="text-align:center;color: rgb(28, 108, 198);font-weight: bold;border-top: 1px solid rgb(28, 108, 198);">Signature/Name of Owner <br/> LYNA TAN(Mrs)</td>
            </tr>
         </table>
    </div>
  </div>
</body>

</html>