<?php $tr=Application_Form_FrmLanguages::getCurrentlanguage();
 echo '<title>'. $tr->translate("Edit Stuff").'</title>';
 $status_view=$this->status_view;
 $row_stuff=$this->row_stuff;
 $rows_detail=$this->rows_detail;
?>
<form id="add_location" action="<?php echo $this->url(array('module'=>'stuff','controller'=>'index','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				 if(dijit.byId('record_row').get('value')==''){
                    alert('Can not submit without record !');
                    return false;
                 }
				loading();
				return true;
			} else {
				return false;
			}
	</script>
	<div class="clearfix"></div>
	<div class="row">
      	<div class="col-md-12 col-xs-12 forms_padding">
          	<div class="x_panel">
              <div class="x_title">
                 <h2><i class="fa  fa-edit" aria-hidden="true"></i> <?php echo $tr->translate('Edit Stuff')?></h2>
                 <ul class="nav navbar-right panel_toolbox">
	                  <li>
	                   	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	                   </li>
	               	</ul>
               		<div class="clearfix"></div>
         	 	</div>
	       		<div class="x_content">
	       			<div class="form-group">
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Equipment Name')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                    	<input dojoType="dijit.form.ValidationTextBox" class="fullside" required="true" id="Eq_name" name="Eq_name" value="<?php echo $row_stuff['equipment_name']?>" type="text">
	                   		<input type="hidden" name="id" value="<?php echo $row_stuff['id']?>"/>
	                   </div>
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Reference No')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                    	<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="Referent" name="Referent" value="<?php echo $row_stuff['reference_no']?>" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Year')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                    	<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="year" name="year" value="<?php echo $row_stuff['year']?>" type="text">
	                   </div>
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Color')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                   		<input dojoType="dijit.form.ValidationTextBox" class="fullside"  id="color" name="color" value="<?php echo $row_stuff['color']?>" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Make/Model')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                    	<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="model" name="model" value="<?php echo $row_stuff['model']?>" type="text">
	                   </div>
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Size')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                   		<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="size" name="size" value="<?php echo $row_stuff['size']?>" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Serial No')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                    	<input dojoType="dijit.form.ValidationTextBox" class="fullside"  id="serial_no" name="serial_no" value="<?php echo $row_stuff['serial_no']?>" type="text">
	                   </div>
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Other(specify)')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                   		<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="other" name="other" value=""<?php echo $row_stuff['other']?>" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Telephone Number')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                    	<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="telephone_num" name="telephone_num" value="<?php echo $row_stuff['telephone_num']?>" type="text">
	                   </div>
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Cell Phone Serial No')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                   		<input dojoType="dijit.form.ValidationTextBox" class="fullside"  id="cell_phone" name="cell_phone" value="<?php echo $row_stuff['cell_phone']?>" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Url')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                    	<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="Url" name="Url" value="<?php echo $row_stuff['url']?>" type="text">
	                   </div>
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Type')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                   		<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="type" name="type" value="<?php echo $row_stuff['type'];?>" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Sim Card Serial No')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                    	<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="sim_card" name="sim_card" value="<?php echo $row_stuff['sim_card']?>" type="text">
	                   </div>
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('STATUS')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                   		<select name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true"  class="fullside">
							     <?php foreach ($status_view as $rs){?>
								    <option value="<?php echo $rs['key_code'];?>" <?php if ($row_stuff['status']==$rs['key_code']){echo 'selected="selected"';}?> label="<?php echo $rs['name_en'];?>"><?php echo $rs['name_en'];?></option>
							    <?php }?>
							</select>
	                   </div>
	                </div>
	                 <div class="title_form_blog">
	               		<h4><i class="fa  fa-file" aria-hidden="true"></i> <?php echo $tr->translate("Photo")?></h4>
	              	 </div>
	              	 <div class="form-group">
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Front Veiw')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                   		<input name="old_front_Veiw" value="<?php echo $row_stuff['photo_front']?>" type="hidden">
							<img src="<?php echo $this->baseUrl()."/images/product/".$row_stuff['photo_front'];?>" height="30px"/>
	                    	<input id="front_Veiw" name="front_Veiw" value="" type="file">
	                   </div>
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Front Right Veiw')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                   		<input name="old_Front_Right" value="<?php echo $row_stuff['photo_front_right']?>" type="hidden">
							<img src="<?php echo $this->baseUrl()."/images/product/".$row_stuff['photo_front_right'];?>" height="30px"/>
	                   		<input id="Front_Right" name="Front_Right" value="" type="file">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Front Left Veiw')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                   		<input name="old_front_left" value="<?php echo $row_stuff['photo_front_left']?>" type="hidden">
							<img src="<?php echo $this->baseUrl()."/images/product/".$row_stuff['photo_front_left'];?>" height="30px"/>
	                    	<input id="front_left" name="front_left" value="" type="file">
	                   </div>
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Rear Left Veiw')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                   		<input name="old_rear_left" value="<?php echo $row_stuff['photo_rear_left']?>" type="hidden">
						    <img src="<?php echo $this->baseUrl()."/images/product/".$row_stuff['photo_rear_left'];?>" height="30px"/>
	                   		<input id="rear_left" name="rear_left" value="" type="file">
	                   </div>
	                </div>
	                <div class="form-group">
	                	<div style="clear: both;"></div>
						<input type="hidden" dojoType="dijit.form.TextBox" id="record_row" name="record_row" />
						<div  id="store_record"></div>
						<input iconClass="dijitIconClear" type="button" onClick="addPockage();" label="Add Record Photo" dojoType="dijit.form.Button"/>
	                </div>
	                <div class="form-group text-center">
					    	 <input type="reset" value="clear" label="<?php echo $tr->translate('CLEAR');?>"dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
							 <input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
					    </div>
	       		</div>
	       	</div>
	     </div>
	</div>
</form>
<script type="text/javascript">
dojo.require("dijit.form.NumberTextBox");
dojo.require("dojo.NodeList-manipulate");

dojo.require("dojo.html");
require(["dojo/ready"], function(ready){
	ready(function(){
		addNewRecord();
		//initList();
	});
});
province_option = '<?php echo $this->pro_option;?>';
function addNewRecord(){
	dojo.query("#store_record").append('');
	tmp='<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#store_record").append(tmp);
	thead='<th><?php echo $tr->translate('Amount Day');?></th>';
	thead+='<th><?php echo $tr->translate('PRICE');?></th>';
	thead+='<th><?php echo $tr->translate('Extra Price');?></th>';
	thead+='<th><?php echo $tr->translate('NOTE');?></th>';
	thead+='<th><?php echo $tr->translate('DELETE');?></th>';
	fund_title=1;
	dojo.query("#head_title").append(thead);	
	dijit.byId('record_row').attr('value','');
	initList();
}
r=0;
function addPockage(){
	r++;
	tmp='<tr style="border:1px solid #ccc; font-size:12px;" id="row_guide'+r+'">'
	tmp+="</tr>";
		dojo.query("#t_amountmoneytype").append(tmp);
		
	temp='<td><select style="width:260px;"  id="package_id'+r+'" name="package_id'+r+'" dojoType="dijit.form.FilteringSelect" onchange="getLocation('+r+')">'+province_option+'</select></td>';
	temp+='<td><input style="width:260px;" dojoType="dijit.form.NumberTextBox" class="fullside" required="true" name="price_'+r+'" id="price_'+r+'" value="" type="text"></td>';
	temp+='<td><input style="width:260px;" dojoType="dijit.form.NumberTextBox" class="fullside" required="true" name="extracharge_'+r+'" id="extracharge_'+r+'" value="" type="text"></td>';
	temp+='<td><input style="width:260px;" dojoType="dijit.form.TextBox" class="fullside" name="note_'+r+'" id="note_'+r+'" value="" type="text"></td>';
	temp+='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="/lyna/trunk/public/images/Delete_16.png"></td>';
	
	dojo.html.set(dojo.byId("row_guide"+r),temp, {
	    parseContent: true,
	});
	if(dijit.byId("record_row").get('value')!="") {
		var ids = dijit.byId("record_row").value;
		dijit.byId("record_row").attr('value',ids+','+r);
	} else { dijit.byId("record_row").attr('value',r);}
}
///
r=0;
function initList(){
	<?php foreach ($rows_detail As $rs){?>
	r++;
	tmp='<tr style="border:1px solid #ccc; font-size:12px;" id="row_guide'+r+'">'
	tmp+="</tr>";
		dojo.query("#t_amountmoneytype").append(tmp);
		
	temp='<td><select style="width:260px;"  id="package_id'+r+'" name="package_id'+r+'" dojoType="dijit.form.FilteringSelect" onchange="getLocation('+r+')">'+province_option+'</select></td>';
	temp+='<td><input style="width:260px;" dojoType="dijit.form.NumberTextBox" class="fullside" required="true" name="price_'+r+'" id="price_'+r+'" value="" type="text"></td>';
	temp+='<td><input style="width:260px;" dojoType="dijit.form.NumberTextBox" class="fullside" required="true" name="extracharge_'+r+'" id="extracharge_'+r+'" value="" type="text"></td>';
	temp+='<td><input style="width:260px;" dojoType="dijit.form.TextBox" class="fullside" name="note_'+r+'" id="note_'+r+'" value="" type="text"></td>';
	temp+='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
	
	dojo.html.set(dojo.byId("row_guide"+r),temp, {
	    parseContent: true,
	});
	if(dijit.byId("record_row").get('value')!="") {
		var ids = dijit.byId("record_row").value;
		dijit.byId("record_row").attr('value',ids+','+r);
	} else { dijit.byId("record_row").attr('value',r);}
	   // alert(r);
	    dijit.byId('package_id'+r).attr('value',<?php echo $rs['package_id']?>);
	    dijit.byId('price_'+r).attr('value',<?php echo $rs['price']?>);
	    dijit.byId('extracharge_'+r).attr('value',<?php echo $rs['extra_price']?>);
	    dijit.byId('note_'+r).attr('value','<?php echo $rs['note']?>');
	<?php }?>
}
function deleteRecord(index){
	var ids =dijit.byId('record_row').value;
	if(ids.length=='' || ids.length==null){
		dijit.byId('record_row').attr('value','');
		dojo.query("#row_guide"+ids).remove();
	}else{
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		dijit.byId('record_row').attr('value',strings);
		dojo.query("#row_guide"+index).remove();
	}
}
var url_getlocation = '<?php echo $this->url(array('module'=>'location','controller'=>'package','action'=>'get-location')); ?>';
function getLocation(id){
			province_id = dijit.byId('province_id'+id).get('value');
			if(province_id==''){
				return false;
			}
			$('#location_id'+id).empty('');
			dojo.xhrPost({
				url:url_getlocation,
				content:{
					'province_id':province_id
					},
				handleAs:"json",
				load: function(data) {
					for(i=0;i<data.length;i++){
						  $('#location_id'+id).append("<option value="+data[i].id+">"+data[i].location_name+"</option>");
					}
					
				},
				error: function(err) {
				}
			});
}

 
</script>
