<?php 
	$vehicle = $this->vehicle;
	$driver = $this->driver;
	$equipment = $this->equipment;
	$form = $this->frmbooking;
	$vehicle_price = $this->vehicle_price;
?>
<style>
	dt{ display: none;}
</style>
<style>
		#calendar,
		#calendar2,
		#calendar3 {
			border: 1px solid #DDD;
			font-family: Tahoma;
			font-size: 12px;
			-webkit-border-radius: 5px;
			-moz-border-radius: 5px;
			border-radius: 5px;
		}
		.my-dropdown input{ 
		padding: 5px;
	-webkit-border-radius: 5px;
-moz-border-radius: 5px;
border-radius: 5px;
}
</style>
<script>
	var myCalendar;
	function doOnLoad() {
		myCalendar = new dhtmlXCalendarObject(["pickup_date","return_date","card_issue_date","card_exp_date","pass_issue_date","pass_exp_date"]);
	}
</script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/codebase/dhtmlxcalendar.css"/>
<script src="<?php echo $this->baseUrl()?>/codebase/dhtmlxcalendar.js"></script>
<!--secondary-banner ends-->
<div class="message-shadow"></div>
<div class="clearfix"></div>
<section class="content">
    <div class="container">
        <div class="inner-page inventory-listing">
            <div class="row"> 
            <div class="clearfix"></div>
            	<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 left-content padding-left-none">
                    <div class="bs-example bs-example-tabs example-tabs margin-top-50">
                        <ul id="myTab" class="nav nav-tabs">
                            <li><a href="#step1" data-toggle="tab">Select Date</a></li>
                            <li><a href="#step2" data-toggle="tab">Select a Car</a></li>
                            <li><a href="#step3" data-toggle="tab">Product And Service</a></li>
                            <li><a href="#step4" data-toggle="tab">Personal Info</a></li>
<!--                             <li><a href="#step5" data-toggle="tab">Personal Info</a></li> -->
<!--                             <li><a href="#step6" data-toggle="tab">Customer information</a></li> -->
                        </ul>
                        <div id="myTabContent" class="tab-content margin-top-15 margin-bottom-20">
                            <div class="tab-pane fade in active" id="step1">
                                <h4 class="margin-bottom-25 margin-top-none"><strong>SEARCH</strong> CAR RENTAL BOOKING</h4>
                        	<div class="search-form margin-top-20 padding-vertical-20">
                            <form method="post">
                                <div class="select-wrapper clearfix">
                                    <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                        Pickup Date
                                        	<?php echo $form->getElement('pickup_date');?>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                         <div class="my-dropdown make-dropdown">
                                        Pickup Time
                                            <input type="text" name="pickup_time" value="<?php echo date("d-m-Y");?>" id="calendar" style="width: 100% !important;padding:1px !important;" >
                                        </div>
                                    </div>
                                </div>
                                <div class="select-wrapper clearfix">
                                     <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                        Return Date
                                        <?php echo $form->getElement('return_date');?>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                         <div class="my-dropdown make-dropdown">
                                        Return Time
                                            <input type="text" name="return_time" value="<?php echo date("d-m-Y");?>" id="calendar" style="width: 100% !important;padding:1px !important;" >
                                        </div>
                                    </div>
                                </div>
                                <div class="select-wrapper clearfix">
                                     <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                       	Pick-up Location
                                        	<?php echo $form->getElement('pickup_location');?>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                         <div class="my-dropdown make-dropdown">
                                        Return Location
                                        	<?php echo $form->getElement('return_location');?>
                                        </div>
                                    </div>
                                </div>
                                 <div class="select-wrapper clearfix">
                                     <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                         <div class="my-dropdown make-dropdown">
                                         <div class="form-element" style="float:right;">
	                                        <input type="submit" name="search_vehicle" value="Find Vehicle Now" class="find_new_vehicle pull-right md-button">
	                                    </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="clear"></div>
                            </form>
                        </div>
                            </div>
                            <div class="tab-pane" id="step2">
                             <?php if(!empty($vehicle)){ foreach ($vehicle as $rs){?>
                                <div class="inventory margin-bottom-20 clearfix">
                                <div class="title"><?php echo $rs["make"]." ".$rs["model"]." ".$rs["sub_model"]."(".$rs["reffer"].")"?></div>
                                <img src="http://demo.themesuite.com/automotive/images/car-1-200x150.jpg" class="preview" alt="preview">
                                <table class="options-primary">
                                    <tr>
                                        <td class="option primary">Body Color:</td>
                                        <td class="spec"><?php echo $rs["color"];?></td>
                                    </tr>
                                    <tr>
                                        <td class="option primary">Drivetrain:</td>
                                        <td class="spec">4WD</td>
                                    </tr>
                                    <tr>
                                        <td class="option primary">Engine:</td>
                                        <td class="spec"><?php echo $rs["engine"];?></td>
                                    </tr>
                                    <tr>
                                        <td class="option primary">Trans. Type:</td>
                                        <td class="spec"><?php echo $rs["transmission"]?></td>
                                    </tr>
                                    <tr>
                                        <td class="option primary">Seat No:</td>
                                        <td class="spec"><?php echo $rs["seat_amount"]?></td>
                                    </tr>
                                </table>
                                <table class="options-secondary">
                                    <tr>
                                        <td class="option secondary">Max Weight:</td>
                                        <td class="spec"><?php echo $rs["max_weight"]?></td>
                                    </tr>
                                    <tr>
                                        <td class="option secondary">Steering:</td>
                                        <td class="spec"><?php echo $rs["steering"]?></td>
                                    </tr>
                                    <tr>
                                        <td class="option secondary">MPG:</td>
                                        <td class="spec">15 city / 21 hwy</td>
                                    </tr>
                                    <tr>
                                        <td class="option secondary">Frame Number:</td>
                                        <td class="spec"><?php echo $rs["frame_no"]?></td>
                                    </tr>
                                    <tr>
                                        <td class="option secondary">Car Type:</td>
                                        <td class="spec"><?php echo $rs["type"];?></td>
                                    </tr>
                                </table>
                                <a href="<?php echo $this->baseUrl();?>/index/vehicle/id/<?php echo $rs["id"];?>" target="_blank"><div class="view-details gradient_button"><i class='fa fa-plus-circle'></i> View Details </div></a>
                                <a href="<?php echo $this->baseUrl();?>/index/getvehicleid/id/<?php echo $rs["id"];?>"><div class="select gradient_button"><i class='fa fa-plus-circle'></i> Select </div></a>
                                <a href="<?php echo $rs["show_url"];?>" target="_blank"><div class="view_video gradient_button"><i class="fa fa-video-camera"></i> View Video</div></a>
                               
                            </div>
                             <?php }}else echo "No Vehicle available!";?>
                            </div>
                            <div class="tab-pane fade" id="step3">
                            	<div class="bs-example bs-example-tabs example-tabs margin-top-0">
			                        <ul id="myTab" class="nav nav-tabs">
			                            <li class="active"><a href="#driver" data-toggle="tab">Driver</a></li>
			                            <li><a href="#equiment" data-toggle="tab">Equiment</a></li>
			                            <li style="float:right;"><button type="submit" style="padding: 0px 5px; margin-bottom: -9px;" name="pro_equip">Continue</button></li>
			                        </ul>
			                         <div id="myTabContent" class="tab-content margin-top-15 margin-bottom-0">
			                         	<div class="tab-pane active" id="driver">
			                         		<div style="float: left;padding-right: 99px;">
			                           			<input type="radio" name="self_drive" id="self_drive" checked="checked" style="left: 5px; float: left;" onClick="activeSelfDrive();" /><p style="margin-left: 34px;">Self Drive</p>
			                           		</div>
			                           		<div>
			                           			<input type="radio" name="self_drive" id="chauffeur" style="left: 165px; float: left;" onClick="activeChauffeur();" /><p style="margin-left: 34px;">Chauffeur</p>
			                           		</div>
			                           		<div id="drive_select">
			                         		<?php if(!empty($driver)){ $i =0; foreach ($driver as $rs){ $i++;?>
			                         			<div class="content-wrap car_listings">
				                                <div class="inventory margin-bottom-20 clearfix" style="padding-bottom: 20px;">
				                                <input type="checkbox" name="driver_<?php echo $i?>" class="checkbox input-checkbox" id="driver_<?php echo $i;?>" onClick="addDriver(<?php echo $i?>)" value="<?php echo $rs["id"];?>" style="rigth: 0 !important;"/><p>&nbsp;</p>
				                                <div class="title" style="position: absolute;top: 0px;"><?php echo $rs["name"];?></div>
				                                <img src="<?php echo $this->baseUrl();?>/images/driverphoto/<?php echo $rs["photo"];?>" class="preview" alt="preview">
				                                <table class="options-primary">
				                                    <tr>
				                                        <td class="option primary">Driver ID:</td>
				                                        <td class="spec"><?php echo $rs["driver_id"];?></td>
				                                    </tr>
				                                     <tr>
				                                        <td class="option primary">Nationality:</td>
				                                        <td class="spec"><?php echo $rs["nationality"]?></td>
				                                    </tr>
				                                    <tr>
				                                        <td class="option primary">Experience:</td>
				                                        <td class="spec"><?php echo $rs["experience_desc"]?></td>
				                                    </tr>
				                                    <tr>
				                                        <td class="option primary">Language:</td>
				                                        <td class="spec"><?php echo $rs["lang_note"];?></td>
				                                    </tr>
				                                    <tr>
				                                        <td class="option primary">Tel:</td>
				                                        <td class="spec"><?php echo $rs["tel"]?></td>
				                                    </tr>
				                                    <tr>
				                                        <td class="option primary">Email:</td>
				                                        <td class="spec"><?php echo $rs["email"]?></td>
				                                    </tr>
				                                </table>
				                                <table class="options-secondary" style="width:300px">
				                                    <tr>
				                                        <td class="option secondary" style="width:150px">City Nomal Price:</td>
				                                        <td class="spec"><?php echo $rs["c_normalprice"]?></td>
				                                    </tr>
				                                    <tr>
				                                        <td class="option secondary">City Holiday Price:</td>
				                                        <td class="spec"><?php echo $rs["c_holidayprice"]?></td>
				                                    </tr>
				                                    <tr>
				                                        <td class="option secondary">City Weeken Price:</td>
				                                        <td class="spec"><?php echo $rs["c_weekendprice"]?></td>
				                                    </tr>
				                                    <tr>
				                                        <td class="option secondary">City OT Price:</td>
				                                        <td class="spec"><?php echo $rs["c_otprice"]?></td>
				                                    </tr>
				                                    <tr>
				                                        <td class="option secondary">Province Nomal Price:</td>
				                                        <td class="spec"><?php echo $rs["p_normalprice"];?></td>
				                                    </tr>
				                                    <tr>
				                                        <td class="option secondary">Province Holiday Price:</td>
				                                        <td class="spec"><?php echo $rs["p_holidayprice"];?></td>
				                                    </tr>
				                                    <tr>
				                                        <td class="option secondary">Province Weeken Price:</td>
				                                        <td class="spec"><?php echo $rs["p_weekendprice"];?></td>
				                                    </tr>
				                                    <tr>
				                                        <td class="option secondary">Province OT Price:</td>
				                                        <td class="spec"><?php echo $rs["p_otprice"];?></td>
				                                    </tr>
				                                </table>
				                                <a href="<?php echo $this->baseUrl();?>/index/vehicle/id/<?php echo $rs["id"];?>" target="_blank"><div class="view-details gradient_button"><i class='fa fa-plus-circle'></i> View Details </div></a>
				                                <a href="<?php echo $this->baseUrl();?>/index/getvehicleid/id/<?php echo $rs["id"];?>"><div class="select gradient_button"><i class='fa fa-plus-circle'></i> Select </div></a>
				                                <a href="<?php //echo $rs["show_url"];?>" target="_blank"><div class="view_video gradient_button"><i class="fa fa-video-camera"></i> View Video</div></a>
				                               
				                            </div>
				                            </div>
				                           <?php }}else echo "No Driver Available!";?>
				                           <input type="text" name="identity_driver" id="identity_driver"/> 
				                           </div>
				                        </div>
                            			<div class="tab-pane fade" id="equiment">
                            				<?php if(!empty($equipment)){ foreach ($equipment as $rs){?>
				                                <div class="inventory margin-bottom-20 clearfix" style="padding-bottom: 42px;">
				                                <input type="checkbox" name="a" class="checkbox input-checkbox" id="equipment_<?php echo $i;?>" style="rigth: 0 !important;"/><p>&nbsp;</p>
				                                <div class="title" style="position: absolute;top: 0px;"><?php echo $rs["equipment_name"];?></div>
				                                <img src="<?php echo $this->baseUrl();?>/images/<?php echo $rs["photo_front"];?>" class="preview" alt="preview">
				                                <table class="options-primary">
				                                    <tr>
				                                        <td class="option primary">Reference No:</td>
				                                        <td class="spec"><?php echo $rs["reference_no"];?></td>
				                                    </tr>
				                                     <tr>
				                                        <td class="option primary">Price:</td>
				                                        <td class="spec"><?php echo $rs["price"]?></td>
				                                    </tr>
				                                    <tr>
				                                        <td class="option primary">Extra Price:</td>
				                                        <td class="spec"><?php echo $rs["extra_price"]?></td>
				                                    </tr>
				                                </table>
				                                 <table class="options-secondary" style="width:300px">
				                                    <tr>
				                                        <td class="option secondary" style="width:120px">Number of Rent:</td>
				                                        <td class="spec"><input type="text" name="number_equipment_<?php echo $i;?>"></td>
				                                    </tr>
				                                 </table>
				                                <a href="<?php echo $this->baseUrl();?>/index/vehicle/id/<?php echo $rs["id"];?>" target="_blank"><div class="view-details gradient_button"><i class='fa fa-plus-circle'></i> View Details </div></a>
				                                <a href="<?php echo $this->baseUrl();?>/index/getvehicleid/id/<?php echo $rs["id"];?>"><div class="select gradient_button"><i class='fa fa-plus-circle'></i> Select </div></a>
				                                <a href="<?php echo $rs["url"];?>" target="_blank"><div class="view_video gradient_button"><i class="fa fa-video-camera"></i> View Video</div></a>
				                            </div>
				                           <?php }}else echo "Equipment Not Available!";?>
				                           <<input type="text" name="identity_equipment" id="identity_equipment"/>
                            			</div>
			                         </div>
			                    </div>
                            </div>
                            <div class="tab-pane fade" id="step4">
                            	<div class="clearfix"></div>
			                    <div id="login_section">
			                    	<form action="">
			                    		 <div class="select-wrapper clearfix">
		                                     <div class="col-md-2">
		                                        <div class="my-dropdown make-dropdown">
		                                        User Name :
		                                        </div>
		                                    </div>
		                                    <div class="col-md-5">
		                                    	 <div class="my-dropdown make-dropdown">
		                                        <?php echo $form->getElement('user_name');?>
		                                        </div>
		                                    </div>
		                                    <div class="clearfix"></div>
		                                    <div class="col-md-2">
		                                        <div class="my-dropdown make-dropdown">
		                                        Password :
		                                        </div>
		                                    </div>
		                                    <div class="col-md-5">
		                                    	 <div class="my-dropdown make-dropdown">
		                                        <?php echo $form->getElement('password');?>
		                                        </div>
		                                    </div>
		                                    <div class="clearfix"></div>
		                                    <div class="col-md-5">
		                                    	<div class="my-dropdown make-dropdown" style="text-align:right">
		                                        	<button type="reset" name="reset">Reset</button>
		                                        	<button type="submit" name="login">Login</button>
		                                         </div>
		                                    </div>
		                                     <div class="col-md-3">
		                                    	 <div class="my-dropdown make-dropdown">
		                                        	<span id="signup" style="cursor: pointer;" onClick="signUp();" >Create an account</span>
		                                         </div>
		                                    </div>
		                                </div>
			                    	</form>
			                    </div>
			                    <div class="clearfix"></div>
			                    <div id="signup_section" style="display: none">
			                    	<form action="">
			                    		<div class="select-wrapper clearfix">
		                                     <div class="col-md-6">
		                                        <div class="my-dropdown make-dropdown">
		                                        First Name :
		                                        <?php echo $form->getElement('first_name');?>
		                                        </div>
		                                     </div>
		                                     <div class="col-md-6">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 Last Name : 
		                                        	<?php echo $form->getElement('last_name');?>
		                                        </div>
		                                      </div>
		                                </div>
		                                <div class="select-wrapper clearfix">
		                                	<div class="col-md-6">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 Email : 
		                                        	<?php echo $form->getElement('email');?>
		                                        </div>
		                                    </div>
		                                    <div class="col-md-6">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 Phone : 
		                                        	<?php echo $form->getElement('phone');?>
		                                        </div>
		                                    </div>
		                                </div>
		                                <div class="select-wrapper clearfix">
		                                	<div class="col-md-6">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 Nationality : 
		                                        	<?php echo $form->getElement('national');?>
		                                        </div>
		                                    </div>
		                                    <div class="col-md-6">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 Gender : 
		                                        	<?php echo $form->getElement('gender');?>
		                                        </div>
		                                    </div>
		                                </div>
		                                <div class="select-wrapper clearfix">
		                                	<div class="col-md-4">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 ID Card : 
		                                        	<?php echo $form->getElement('card_id');?>
		                                        </div>
		                                    </div>
		                                    <div class="col-md-4">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 Issue Date : 
		                                        	<?php echo $form->getElement('card_issue_date');?>
		                                        </div>
		                                    </div>
		                                    <div class="col-md-4">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 Expire Date : 
		                                        	<?php echo $form->getElement('card_exp_date');?>
		                                        </div>
		                                    </div>
		                                </div>
		                                
		                                <div class="select-wrapper clearfix">
		                                	<div class="col-md-4">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 Passport ID : 
		                                        	<?php echo $form->getElement('pass_id');?>
		                                        </div>
		                                    </div>
		                                    <div class="col-md-4">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 Issue Date : 
		                                        	<?php echo $form->getElement('pass_issue_date');?>
		                                        </div>
		                                    </div>
		                                    <div class="col-md-4">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 Expire Date : 
		                                        	<?php echo $form->getElement('pass_exp_date');?>
		                                        </div>
		                                    </div>
		                                </div>
		                                
		                                <div class="select-wrapper clearfix">
		                                	<div class="col-md-2">
		                                    	 
		                                    </div>
		                                    <div class="col-md-8" style="text-align: center;">
		                                    	<div class="my-dropdown make-dropdown">
		                                    	 	<button type="reset" name="reset">Reset</button>
		                                        	<button type="submit" name="signup">Sign Up</button>
		                                        	<span style="cursor: pointer; padding-left: 20px;color: rgb(195, 12, 148);" onClick="logIn();">Have account!</span>
		                                        </div>
		                                    </div>
		                                    <div class="col-md-2">
		                                    	 
		                                    </div>
		                                </div>
			                    	</form>
			                    </div>
			                    
                            </div>
<!--                             <div class="tab-pane fade" id="step5"> -->
                                
<!--                             </div> -->
<!--                             <div class="tab-pane fade" id="step6"> -->
                                
<!--                             </div> -->
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 right-content padding-right-none">
                	<div class="financing_calculator margin-top-10" style="border:1px solid #ccc; border-radius:5px; ">
                            <h6 style="background: #ccc;margin-top: 0px; padding: 10px;">Rental Price</h6>
                            <div class="table-responsive" style="padding:10px;">
                                <table class="table no-border no-margin">
                                    <tbody>
                                    	<tr>
                                        	<td><b>Car rate :</b></td>
                                        	<td><b><?php if($vehicle_price["price"]==""){echo 0;}else{ echo ($vehicle_price["price"]+($vehicle_price["price"]*($vehicle_price["vat_value"]/100)))*$this->total_day;} ?></b></td>
                                        </tr>
                                        <tr>
                                            <td>Chauffeur Rate : </td>
                                            <td><?php //echo $this->pickup_date." ". $this->pickup_time;?></td>
                                        </tr>
                                        <tr>
                                            <td>Equipment rate :</td>
                                            <td><?php //echo $this->pickup_location;?></td>
                                        </tr>
                                        <tr>
                                        	<td><b>Rantal Price</b></td>
                                        	<td><b>Total Days</b></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                     </div>
                     
                     <div class="financing_calculator margin-top-10" style="border:1px solid #ccc; border-radius:5px; ">
                            <h6 style="background: #ccc;margin-top: 0px; padding: 10px;">Booking Info</h6>
                            <div class="table-responsive" style="padding:10px;">
                                <table class="table no-border no-margin">
                                    <tbody>
                                    	<tr>
                                        	<td colspan="2"><b>Pickup</b></td>
                                        </tr>
                                        <tr>
                                            <td>Date and Time : </td>
                                            <td><?php echo $this->pickup_date." ". $this->pickup_time;?></td>
                                        </tr>
                                        <tr>
                                            <td>Location :</td>
                                            <td><?php echo $this->pickup_location;?></td>
                                        </tr>
                                        <tr>
                                        	<td colspan="2"><b>Return</b></td>
                                        </tr>
                                        <tr>
                                            <td>Date and Time : </td>
                                            <td><?php echo $this->return_date." ". $this->return_time;?></td>
                                        </tr>
                                        <tr>
                                            <td>Location :</td>
                                            <td><?php echo $this->return_location?></td>
                                        </tr>
                                        <tr>
                                        	<td><b>Total Days</b></td>
                                        	<td><b><?php echo $this->total_day; // if($this->total_day==0){ echo 1;}else{ echo $this->total_day;}?></b></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                     </div>
                     <div class="financing_calculator margin-top-10" style="border:1px solid #ccc; border-radius:5px; ">
                            <h6 style="background: #ccc;margin-top: 0px; padding: 10px;">Car Info</h6>
                            <div class="table-responsive" style="padding:10px;">
                                <table class="table no-border no-margin">
                                    <tbody>
                                    	<tr>
                                        	<td><b>Car Info : </b></td>
                                        	<td><b>Car Info : </b></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                     </div>
                </div>
                    <div class="clearfix"></div>
                <!--MAP-->
               
                <!--MAP--> 
                <!--CONTACT INFORMATION-->
                
                <!---CONTACT INFORMATION--> 
                
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <!--container ends--> 
</section>
<!--content ends-->
<script>
$( document ).ready(function() {
	  $( "#job-active" ).removeClass( "active" );
$( "#home-active" ).removeClass( "active" );
$( "#about-active" ).removeClass( "active" );
$( "#contact-active" ).removeClass( "active" );
$( "#service-active" ).removeClass( "active" );
$( "#promo-active" ).removeClass( "active" );
$( "#pralist-active" ).removeClass( "active" );
$( "#booking-active" ).addClass( "active" );
});
$('#drive_select').css("display", "none");
function activeSelfDrive(){
	var self_drive = $('#self_drive').val();
		 if(self_drive=="on") {
		      $('#drive_select').css("display", "none");
		   }
}
function activeChauffeur(){
	var Chauffeur = $('#chauffeur').val();
		 if(Chauffeur=="on") {
		      $('#drive_select').css("display", "block");
		   }
}

function signUp(){
	$('#signup_section').css("display", "block");
	$('#login_section').css("display", "none");
}
function logIn(){
	$('#signup_section').css("display", "none");
	$('#login_section').css("display", "block");
}
function addDriver(index){
	var ids=$('#identity_driver').val();
	var arrays = ids.split(',');
	for(var i=0;i<arrays.length;i++) {//calculate record row
		if(arrays[i] == index) arrays.splice(i,1);
		if(document.getElementById('driver_'+index).checked){
			if(($("#identity_driver").val())!="") {
				$("#identity_driver").val(ids+','+index);
			}else { 
				$("#identity_driver").val(index);
			}
		 }else{
			 //alert(index);
			var strings = arrays.join(',');
			$('#identity_driver').val(strings);
		}
	}
}
</script>
