<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage(); 
$form = $this->frmbooking;	 
$user_info = $this->user_info; 
?>
<title>Taxi Booking</title>
<style>
	dt{ display: none;}
</style>
<style>
		#calendar,
		#calendar2,
		#calendar3 {
			border: 1px solid #DDD;
			font-family: Tahoma;
			font-size: 12px;
		}
		.my-dropdown input{ 
		padding: 5px;
}
.wrapp{ width: 100%; height: 100%;}
      .h_left{width:40%;float:left;}
      .h_right{width:40%;float:right;}
      .conten{margin-top:20px;}
      table tr .totalbr{
			border: 1px solid #000;
		}
.note{margin-top:20px;}
		.note p{line-height: 15px !important;    font-size: 12px;}
		.note p+p{margin:6px !important;    font-size: -8px;}
		.note ol{margin-top: -8px;}
		.note li{font-size: 12px;line-height: 15px;}
</style>
<script>
	var myCalendar;
	function doOnLoad() {
		myCalendar = new dhtmlXCalendarObject(["calendar","calendar2","calendar3",]);
	}
</script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/codebase/dhtmlxcalendar.css"/>
<script src="<?php echo $this->baseUrl()?>/codebase/dhtmlxcalendar.js"></script>
<!--message-wrap ends-->
<section class="content">
    <div class="container">
        <div class="homepage margin-bottom-none">
            <!--car-info-wrap ends-->
            <section class="welcome-wrap padding-top-30 sm-horizontal-15">
                <div class="row">
                 <div class="clearfix"></div>
            	<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 left-content padding-left-none">
            			<h4 class="margin-bottom-25 margin-top-none"><strong>SEARCH</strong> FOR TAXI RESERVATION</h4>
                    <div class="bs-example bs-example-tabs example-tabs">
                        <ul id="myTab" class="nav nav-tabs">
                            <li <?php if(empty($this->bookinginfo->point_step))echo'class="active"';?>><a href="#step1" data-toggle="tab">Select Date</a></li>
                            <li <?php if($this->bookinginfo->point_step ==1 )echo'class="active"';?>><a href="#step2" data-toggle="tab">Select Vehicle</a></li>
                            <li <?php if($this->bookinginfo->point_step ==2 )echo'class="active"';?>><a href="#step3" data-toggle="tab">Personal Info</a></li>
                            <li <?php if($this->bookinginfo->point_step ==3) echo 'class="active"';?>><a href="#step4" data-toggle="tab">Confirm Payment</a></li>
                            <li  <?php if($this->bookinginfo->point_step ==4 )echo"class='active'";?>><a href="#step5" data-toggle="tab">Payment</a></li>
                        </ul>
                        <div id="myTabContent" class="tab-content margin-top-15 margin-bottom-20">
                        	<?php if($this->bookinginfo->step1==1 or empty($this->bookinginfo->point_step)){?>
                            <div class="tab-pane fade <?php if(empty($this->bookinginfo->point_step))echo"in active";?>" id="step1" >
                               <div class="search-form padding-vertical-20">
                            <form method="post" action="<?php echo $this->url(array('module'=>'default','controller'=>"taxi",'action'=>'getvehicle'),null,true); ?>">
                              <div class="select-wrapper clearfix">
                                    <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                           <strong>Pickup Date</strong>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="min-price select-dropdown">
                                             <div class="my-dropdown min-price-dropdown min-dropdown">
	                                              <strong>Hour</strong>
	                                          </div>
                                            <span class="my-dropdown"></span>
                                            <div class="my-dropdown max-price-dropdown min-dropdown">
                                             <strong>Min</strong>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                              <div class="select-wrapper clearfix">
                                    <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                            <input type="text" name="pickup_date" value="<?php echo date("d-m-Y");?>" id="calendar" style="width: 100% !important;padding:1px !important;" >
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="min-price select-dropdown">
                                             <div class="my-dropdown min-price-dropdown min-dropdown">
	                                                <select name="pickup_time" class="control_style" tabindex="1" >
	                                                    <?php for($i=1;$i<24;$i++){?>
	                                                    	<option value="<?php echo $i; ?>"><?php echo $i;if($i<=12){echo " AM";}else{ echo " PM";} ?></option>
	                                                    <?php }?>
	                                                </select>
	                                          </div>
                                            <span class="my-dropdown"></span>
                                            <div class="my-dropdown max-price-dropdown min-dropdown">
                                               <select name="pickup_mins" class="control_style" tabindex="1" >
	                                              <option value="00">00</option>
	                                                  <?php $sum = 0;for($i=1;$i<=3;$i++){?>
	                                                     <option value="<?php echo $sum+15; ?>"><?php echo $sum=$sum+15; ?></option>
	                                                  <?php }?>
	                                            </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="select-wrapper clearfix">
                                    <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                            <strong>Pickup Location</strong>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                           <strong>Dropoff Location</strong>
                                        </div>
                                    </div>
                                </div>
                                <div class="select-wrapper clearfix">
                                    <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                            <select name="from_location" class="control_style" tabindex="1">
                                                <option value="0">Please Select Location</option>
                                                <?php foreach ($this->alllocation as $row){?>
                                                	<option value="<?php echo $row['id'];?>"><?php echo $row['location_name'];?></option>
                                                <?php }?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                           <select name="to_location" class="control_style" tabindex="1" >
                                                <option value="0">Please Select Location</option>
                                                <?php foreach ($this->alllocation as $row){?>
                                                	<option value="<?php echo $row['id'];?>"><?php echo $row['location_name'];?></option>
                                                <?php }?>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="select-wrapper clearfix">
                                	<div class="col-md-6">
                                         <div class="my-dropdown make-dropdown">
                                          	<strong>One Way/Round-Trip</strong>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                        </div>
                                    </div>
                                    
                                </div>
                                <div class="select-wrapper clearfix">
                                	<div class="col-md-6">
                                         <div class="my-dropdown make-dropdown">
                                           <select name="trip_way" class="control_style" tabindex="1" >
                                                <option value="1">One-Way</option>
                                                <option value="2">Round-Trip</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                        	<button type="submit"><strong>Find My New Vehicle</strong></button>
                                        </div>
                                    </div>
                                    
                                </div>
                                <div class="clear"></div>
                            </form>
                        </div>
                        <div>
                          <div class="select-wrapper clearfix borderradius" style="border:1px solid #ccc;padding-bottom:5px; text-align: center;">
                        	<h4 align="center"><strong>Our Vehicle Makes.</strong></h4> 
                                  <img width="91px" src="<?php echo $this->baseUrl()."/images/partner/Toyota.jpg";?>" />
				                   <img width="91px" src="<?php echo $this->baseUrl()."/images/partner/Lexus.jpg";?>" />
				                   <img width="91px" src="<?php echo $this->baseUrl()."/images/partner/Ford.jpg";?>" />
				                   <img width="91px" src="<?php echo $this->baseUrl()."/images/partner/Honda.jpg";?>" />
                                   <img width="91px" src="<?php echo $this->baseUrl()."/images/partner/Hyundai.jpg";?>" />
				                   <img width="91px" src="<?php echo $this->baseUrl()."/images/partner/Isuzu.jpg";?>" />
				                   <img width="91px" src="<?php echo $this->baseUrl()."/images/partner/LandRover.jpg";?>" />
				                   <img width="91px" src="<?php echo $this->baseUrl()."/images/partner/KIA.jpg";?>" />
                           </div> 
                        </div>
                            </div>
                            <?php } 
                            if($this->bookinginfo->step1 ==1){?>
                            <div class="tab-pane <?php if($this->bookinginfo->point_step ==1 )echo"in active";?>" id="step2">
                             <?php if(!empty($this->bookinginfo->vehiclevaliable)){ foreach ($this->bookinginfo->vehiclevaliable as $rs){?>
                                <div class="inventory margin-bottom-20 clearfix">
                                <div class="title"><?php echo $rs["make"]." ".$rs["model"]." ".$rs["sub_model"]."(".$rs["reffer"].")"?></div>
                                
                                <?php empty($rs['img_front_right'])?'no-img.jpg':$rs['img_front_right']?>
                                <img src="<?php echo $this->baseUrl();?>/images/vehicle/<?php echo $rs['img_front_right'];?>"  class="preview" alt="preview">
                                <table class="options-primary">
                                     <tr>
                                        <td class="option primary">Ref. No. :</td>
                                        <td class="spec"><?php echo $rs["reffer"];?></td>
                                    </tr>
                                    <tr>
                                        <td class="option primary">Year : </td>
                                        <td class="spec"><?php echo $rs["year"];?></td>
                                    </tr>
                                    <tr>
                                        <td class="option primary">Color : </td>
                                        <td class="spec"><?php echo $rs["color"];?></td>
                                    </tr>
                                    <tr>
                                        <td class="option primary">No. of Seats :</td>
                                        <td class="spec"><?php echo $rs["seat_amount"];?></td>
                                    </tr>
                                    <tr>
                                         <td class="option primary"> Trans. Type :</td>
                                         <td class="spec"><?php echo $rs['transmission']?></td>
                                    </tr>
                                    <tr>
                                            <td class="option primary">Vehecle Type:</td>
                                            <td class="spec"><?php echo $rs['type']?></td>
                                     </tr>
                                </table>
                                <a href="<?php echo $this->baseUrl();?>/index/vehicle/id/<?php echo $rs["id"];?>" target="_blank"><div class="view-details gradient_button"><i class='fa fa-plus-circle'></i> View Details </div></a>
                                <a href="<?php echo $this->baseUrl();?>/taxi/getvehicletaxi/id/<?php echo $rs["id"];?>"><div class="select gradient_button"><i class='fa fa-plus-circle'></i> Select </div></a>
                                <a href="<?php echo $rs["show_url"];?>" target="_blank"><div class="view_video gradient_button"><i class="fa fa-video-camera"></i> View Video</div></a>
                            </div>
                             <?php }}else echo "No Vehicle available!";?>
                            </div>
                            <?php } if($this->bookinginfo->step2 ==1){?>
                            <div class="tab-pane fade <?php if($this->bookinginfo->point_step ==2 )echo"in active";?>" id="step3">
                            	<div class="clearfix"></div>
                            	<?php if($this->user_session ==1){ ?>
                            	<div id="user-panel">
                            		 <div class="select-wrapper clearfix">
		                                 <div class="col-md-2">
		                                     <div class="my-dropdown make-dropdown">
		                                       User Name :
		                                     </div>
		                                 </div>
		                                 <div class="col-md-3">
		                                     <div class="my-dropdown make-dropdown">
		                                       <?php echo $user_info['first_name']." ".$user_info["last_name"]?>
		                                     </div>
		                                 </div>
		                             </div>
		                             <div class="select-wrapper clearfix">
		                                 <div class="col-md-2">
		                                     <div class="my-dropdown make-dropdown">
		                                       E-mail :
		                                     </div>
		                                 </div>
		                                 <div class="col-md-3">
		                                     <div class="my-dropdown make-dropdown">
		                                       <?php echo $user_info['email']?>
		                                     </div>
		                                 </div>
		                             </div>
		                             <div class="select-wrapper clearfix">
		                                 <div class="col-md-2">
		                                     <div class="my-dropdown make-dropdown">
		                                       Phone :
		                                     </div>
		                                 </div>
		                                 <div class="col-md-3">
		                                     <div class="my-dropdown make-dropdown">
		                                       <?php echo $user_info['phone']?>
		                                     </div>
		                                 </div>
		                             </div>
<div class="select-wrapper clearfix note">
                                       <div class="col-md-12">
                                          <div class="my-dropdown make-dropdown">
                                         <h5 style="font-size: 15px;margin-bottom: 1px;"><b>TERMS & CONDITIONS</b></h5><br />
                                         <?php echo $this->termcondiction;?>
                                       </div>
                                       <form id="agree_form" action="" method="post">
                                       	   <div class="col-md-6 note">
		                                       <div class="my-dropdown make-dropdown">
		                                         	<input type="checkbox" name="agree_term" id="agree" onClick="checkAgree();"  style="margin-top: 6px;" /> <span style="padding-left: 40px; font-size:12px;"><a href="<?php echo $this->baseUrl();?>/index/termcondition"> I agree to the Terms & Conditions</a></span>  
		                                       </div>
	                                       </div>
	                                       <div class="col-md-6 note" style="text-align: right">
		                                       <div class="my-dropdown make-dropdown">
		                                         	<button type="submit" id="c_agree" name="term_condiction">Continue</button>
		                                       </div>
	                                       </div>
                                       </form>
                                  </div>
                            </div>
                            	</div>
                            	<?php }else{?>
			                    <div id="login_section" style="background: #E09206;padding: 10px 15px 10px 0px;border-radius:5px;color: white;font-weight: 600;">
			                    	<form action="<?php echo $this->baseUrl();?>/customer/customerlogin/id/2" method="post" id="login_taxi">
			                    		 <div class="select-wrapper clearfix">
		                                     <div class="col-md-2">
		                                        <div class="my-dropdown make-dropdown">
		                                        User Name :
		                                        </div>
		                                    </div>
		                                    <div class="col-md-5">
		                                    	 <div class="my-dropdown make-dropdown">
		                                        <?php echo $form->getElement('user_name');?>
		                                        </div>
		                                    </div>
		                                    <div class="clearfix"></div>
		                                    <div class="col-md-2">
		                                        <div class="my-dropdown make-dropdown">
		                                        Password :
		                                        </div>
		                                    </div>
		                                    <div class="col-md-5">
		                                    	 <div class="my-dropdown make-dropdown">
		                                        <?php echo $form->getElement('password');?>
		                                        </div>
		                                    </div>
		                                    <div class="clearfix"></div>
		                                    <div class="col-md-5">
		                                    	<div class="my-dropdown make-dropdown" style="text-align:right">
		                                        	<button type="reset" name="reset">Reset</button>
		                                        	<button type="button" onClick="loginValidate()" name="login_taxi" id="login">Login</button>
		                                         </div>
		                                    </div>
		                                     <div class="clearfix"></div>
		                                     <div class="col-md-8" style="margin-top: 10px;">
		                                    	 <div class="my-dropdown make-dropdown" style="text-align:center">
		                                        	<span id="signup" style="cursor: pointer;font-weight:bold;" onClick="signUp();" >| Create Account</span>
<span id="signup" style="cursor: pointer;font-weight:bold;" onClick="signUp();" > | <a href="<?php echo $this->baseUrl();?>/customer/forgetpass">Forget Password</a> |</span>
		                                         </div>
		                                    </div>
		                                </div>
			                    	</form>
			                    </div>
			                    <div class="clearfix"></div>
			                    <div id="signup_section" style="display: none;background: #E09206;padding: 10px 15px 10px 0px;border-radius:5px;color: white;font-weight: 600;">
			                    	<form action="<?php echo $this->baseUrl();?>/customer/signup/id/2; ?>" method="post" id="signups">
			                    	<div class="select-wrapper clearfix">
                                       <div class="col-md-6">
                                          <div class="my-dropdown make-dropdown">
                                          User Name :
                                          <?php echo $form->getElement('s_user_name');?>
                                          <div id='username_availability_result' style="position: absolute;right: 0px;"></div>
                                          </div>
                                       </div>
                                       <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                        Password : 
                                           <?php echo $form->getElement('s_password');?>
                                          </div>
                                        </div>
                                  </div>
                         		  <div class="select-wrapper clearfix">
                                       <div class="col-md-6">
                                          <div class="my-dropdown make-dropdown">
                                          First Name :
                                          <?php echo $form->getElement('first_name');?>
                                          </div>
                                       </div>
                                       <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                        Last Name : 
                                           <?php echo $form->getElement('last_name');?>
                                          </div>
                                        </div>
                                  </div>
                                  <div class="select-wrapper clearfix">
                                   <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                        Email : 
                                           <?php echo $form->getElement('email');?>
            								 <div id='email_availability_result' style="position: absolute;right: 0px;"></div>
                                          </div>
                                      </div>
                                      <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                        Phone : 
                                           <?php echo $form->getElement('phone');?>
                                          </div>
                                      </div>
                                  </div>
		                                <div class="select-wrapper clearfix">
		                                	<div class="col-md-6">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 Date of Birth : 
		                                        	<?php echo $form->getElement('dob');?>
		                                        </div>
		                                    </div>
		                                    <div class="col-md-6">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 Gender : 
		                                        	<?php echo $form->getElement('gender');?>
		                                        </div>
		                                    </div>
		                                </div>
		                                
		                                
		                                <div class="select-wrapper clearfix">
		                                	<div class="col-md-2">
		                                    	 
		                                    </div>
		                                    <div class="col-md-8" style="text-align: center;">
		                                    	<div class="my-dropdown make-dropdown">
		                                    	 	<button type="reset" name="reset">Reset</button>
		                                        	<button type="submit" onClick="formValidate();" name="signup">Sign Up</button>
		                                        	<span style="cursor: pointer; padding-left: 20px;color: rgb(195, 12, 148);" onClick="logIn();">Have account!</span>
		                                        </div>
		                                    </div>
		                                    <div class="col-md-2">
		                                    	 
		                                    </div>
		                                </div>
			                    	</form>
			                    </div>
			                    <?php }?>
			                    
                            </div>
                            <?php }if($this->bookinginfo->step3 ==1 ){ ?>
                            <div class="tab-pane <?php if($this->bookinginfo->point_step ==3 )echo"in active";?>" id="step4">
                            	<form action="" method="post">
                            	<button type="submit" class="pull-right" name="confirm_book">Confirm</button>
                            	</form>
                            	<table id="exportExcel" style="border-collapse:collapse;font-size: 12px;" width="100%">
									<tr>
										<th>
											<table style="border-collapse:collapse;font-size: 12px; width:100% ;text-align: left; padding:5px; line-height: 14px;" cellpadding="5 ">
												<tr style="line-height: 17px;"><td colspan="4" style="border-bottom:1px solid #ccc;text-align: left;background-color:  rgb(27, 86, 227);color:rgb(254, 250, 250);"><strong>&nbsp;Booking Info</strong></td></tr>
										        <tr>
										        	<td >&nbsp;For :</td>
										        	<td><?php echo $this->bookinginfo->user_name?></td>
										        	<td >&nbsp;Trip Way :</td>
										        	<td><?php echo ($this->bookinginfo->trip_way==1)?"One-Way":"Round Trip";?></td>
										        </tr>
										        <tr>
										        	<td >&nbsp;Pickup Date Time : </td>
										        	<td><?php echo date("d/m/Y",strtotime($this->bookinginfo->pickup_date)),'-'.$this->bookinginfo->pickup_time.":".$this->bookinginfo->pickup_mins;?></td> 
										        	<td>&nbsp;Pick-up Location :</td>
										        	<td><?php echo $this->bookinginfo->from_locationname;?></td>
										        </tr>
									            <tr>
									            	<td>&nbsp;Drop-off Date Time </td>
									            	<td><?php echo date("d/m/Y",strtotime($this->bookinginfo->pickup_date)),'-'.$this->bookinginfo->pickup_time.":".$this->bookinginfo->pickup_mins;?></td>
									            	<td>&nbsp;Drop-off Location :</td>
									            	<td><?php echo $this->bookinginfo->to_locationname;?></td>
									            </tr>
									            <tr></tr>
								       	 	</table>
								        </th>
									</tr>
								    <tr >
								    </tr>
								</table>
				                <table style="border-collapse:collapse;font-size: 12px;margin-top:10px;float: left;" width="100%">
								 <tr><td colspan="8" style="border-bottom:1px solid #ccc;text-align: left;background-color:  rgb(27, 86, 227);color:rgb(254, 250, 250);"><strong>&nbsp;Item Info</strong></td></tr>
								  <tr>
								     <th class="totalbr text-center">No</th>
								     <th class="totalbr text-center" >Items Description</th> 
								     <th class="totalbr text-center" >QTY</th> 
								     <th class="totalbr text-center">Price In US$</th>
								  </tr>
								  <tr>
								     <td class="totalbr text-center">&nbsp;<?php $i=1; echo $i;?></td>
								     <td class="totalbr">&nbsp;<?php echo $this->bookinginfo->vehicle_name; ?></td>
								     <td class="totalbr text-center">&nbsp;1</td>
								     <td style="color:red" class="totalbr text-center">&nbsp;<?php echo number_format($this->bookinginfo->taxi_price,2)?> $</td>
								  </tr>
								  <tr>
									  <td></td>
									  <td></td>
									  <td class="totalbr">&nbsp;1.NET TOTAL:</td>
									  <td style="font-weight: 800" class="totalbr text-center" colspan="2">&nbsp;$<?php echo number_format($this->bookinginfo->taxi_price,2)?> </td>
								  </tr>
								  <?php $price = $this->bookinginfo->taxi_price;
										$diposite = $price*(30/100);								  
								  ?>
								   <tr>
									  <td></td>
									  <td></td>
									  <td class="totalbr">&nbsp;2.AMOUNT PAID:</td>
									  <td style="font-weight: 800" class="totalbr text-center" colspan="2">&nbsp;$<?php echo number_format($price,2)?> </td>
								  </tr>
								  <tr>
									  <td></td>
									  <td></td>
									  <td class="totalbr">&nbsp;3.DUE AMOUNT:</td>
									  <td style="font-weight: 800" class="totalbr text-center" colspan="2">&nbsp;$<?php echo number_format(0,2)?></td>
								  </tr>
							   </table>
							   
							   <div class="select-wrapper clearfix note">
							   		<p style="color: red; font-weight: 800;margin-bottom: 5px;">Notes:</p>
							   		<p>1. Pay and Go!.</p>
							   		<p>2. You are requested to come over to our office for advance payment in the full amount as stated in the "<span style="font-weight: 800">Taxi Service Price</span>".</p>
							   		<p>3. Another way, you could also pay all fee via any options as provided on the page, such as:
							   			<ol style="list-style-type: none">
							   				<li>3.1. VISA Card</li>
							   				<li>3.2. WESTERN UNION.</li>
							   				<li>3.3. ACLEDA UNITY.</li>
							   			</ol>
							   		</p>
							   		<p>4. Standby $5.00 per hour.</p>
							   		<p>5. After the full amount of payment is well received, a <u>service</u> will be assigned to you within the time frame manner.</p>
							   </div>
                             </div>
                             <?php }if($this->bookinginfo->step4 ==1 ){?>
                             <div class="tab-pane <?php if($this->bookinginfo->point_step ==4 )echo"in active";?>" id="step5">
                                <form action="<?php echo $this->baseUrl();?>/taxi/payment" method="post" id="payment">
                                	<div class="select-wrapper clearfix">
                                		<div class="col-md-4" style="text-align: center;">
                                			<input id="visa_type" onChange="paymentType(1);" type="radio" name="payment_type" checked="checked" value="1" style="margin-top: 11px;">
		                            		<img alt="" src="<?php echo $this->baseUrl();?>/images/visa.jpg" style="margin-left: 30px;">  
		                            	</div>
		                            	<div class="col-md-4" style="text-align: center;">
		                            		<input id="ws_type" onChange="paymentType(2);" type="radio" name="payment_type" value="2" style="margin-top: 11px;">
		                            		<img alt="" src="<?php echo $this->baseUrl();?>/images/western-union-small.jpg" style="margin-left: 30px;"> 
		                            	</div>
		                            	<div class="col-md-4" style="text-align: left;">
		                            		<input id="wing_type" onChange="paymentType(3);" type="radio" name="payment_type" value="3" style="margin-top: 11px;">
		                            		<img alt="" src="<?php echo $this->baseUrl();?>/images/acleda.jpg" style="margin-left: 30px;"> 
		                            	</div>
		                            </div>
		                            <div class="clearfix" style="height: 20px;"></div>
                                	<div class="select-wrapper clearfix" id="visa" style="background: #FFC100;padding: 10px 14px 16px 0px;border-radius: 5px;">
                                		<div class="select-wrapper clearfix">
                                			<div class="col-md-6">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 Card Name : 
		                                        	<?php echo $form->getElement('card_name');?>
		                                        </div>
		                                    </div>
		                                	<div class="col-md-6">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 	 Card Number :
		                                    	 	 	<input name="card_id" type="text" style="width: 100%; padding:1px" class="credit_card_number" pattern="\d*" x-autocompletetype="cc-number" placeholder="Credit Card Number" required> </p>
		                                        </div>
		                                    </div>
		                                 </div>
		                                 <div class="select-wrapper clearfix">
		                                    <div class="col-md-6">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 Security Code/CVV : 
		                                    	 	<input style="width: 100%; padding:1px" name="secu_code" id=secu_code" type="text" class="credit_card_cvc" pattern="\d*" x-autocompletetype="cc-csc" placeholder="Security Code/CVV" required  autocomplete="off">
		                                        </div>
		                                    </div>
		                                    <div class="col-md-6">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 Expiration : 
		                                    	 	<input type="text" style="width: 100%" name="card_exp_date" class="credit_card_expiry" pattern="\d*" x-autocompletetype="cc-exp" placeholder="Expires MM / YY" required maxlength="9"> </p>
		                                        </div>
		                                    </div>
		                                 </div>
		                                </div>
		                                <div class="select-wrapper clearfix" id="ws_union" style="display: none;background: #FFC100;padding: 10px 14px 16px 0px;border-radius: 5px;">
		                                	<div class="col-md-6">
		                                    	 <div class="my-dropdown make-dropdown">
		                                    	 	 MTCN Code No.:
		                                    	 	 <input class="number" name="code_num" style="width: 100%; padding:1px;" type="text" placeholder="10-Digit MTCN No." data-formance_length="10">
		                                        		<?php //echo $form->getElement('card_id');?>
		                                        </div>
		                                    </div>
		                                    
		                                </div>
		                                
		                                <div class="select-wrapper clearfix" id="wing" style="display: none" style="background: #FFC100;padding: 10px 14px 16px 0px;border-radius: 5px;">
		                                	<div class="col-md-12">
		                                    	 <div class="my-dropdown make-dropdown" style="text-align: center;">
		                                    	 	<img alt="" src="<?php echo $this->baseUrl();?>/images/acleda-to.jpg"> 
		                                        </div>
		                                    </div>
		                                </div>
		                                 <div class="select-wrapper clearfix" style="margin-top: 10px;">
		                                	<div class="col-md-6">
		                                    </div>
		                                    <div class="col-md-6">
		                                    	 <div class="my-dropdown make-dropdown" style="text-align: center;">
		                                    	 	 <button type="button" class="pull-right" onClick="paymentValidate();">Pay and Finish</button>
		                                        </div>
		                                    </div>
		                                </div>
		                               
		                               
		                                <div class="select-wrapper clearfix" style="">
	                                		<div class="col-md-4">
			                            		<img alt="" src="<?php echo $this->baseUrl();?>/images/payment_card_256.png">  
			                            	</div>
			                            	<div class="col-md-4">
			                            		<img alt="" src="<?php echo $this->baseUrl();?>/images/western-union-mb-eng.png"> 
			                            	</div>
			                            	<div class="col-md-4">
			                            		<img alt="" src="<?php echo $this->baseUrl();?>/images/acleda_unity.jpg"> 
			                            	</div>
		                            </div>
                                </form>
                            </div>
                             <?php }?>
                             
                        </div>
                    </div>
                </div>
                    <!--invetory ends--> 
                     <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 padding-right-none sm-padding-left-none md-padding-left-15 xs-padding-left-none padding-bottom-40 scroll_effect fadeInUp">
                        <div class="financing_calculator margin-top-10" style="border:1px solid #ccc; border-radius:5px; ">
                           <h4 class="margin-top-none" style="background: #ccc;margin-top: 0px; padding: 10px; font-size: 16px; border-bottom: 3px solid #8C8C8C;"><strong>Taxi Service </strong>Price</h4>
                            <div class="table-responsive" style="padding:10px;">
                              <table class="table no-border no-margin" border="1">
		                           <tbody>
		                             <tr>
		                                  <td>Vehicle Name : </td>
		                                  <td><b><a style="font-size: 12px;" target="_blank" href="<?php echo $this->baseUrl()."/index/vehicle/id/".$this->bookinginfo->vehicle_id;?>"><?php echo $this->bookinginfo->vehicle_name; ?></a></b></td>
		                              </tr>
		                              <tr>
			                              <td>Price : </td>
			                              <td>US$ <?php echo number_format($this->bookinginfo->taxi_price,2)?></td>
		                              </tr>
		                           </tbody>
                            </table>
                            </div>
                     </div>
                         <div class="financing_calculator margin-top-10" style="border:1px solid #ccc; border-radius:5px; ">
                            <h4 class="margin-bottom-25 margin-top-none" style="background: #ccc;margin-top: 0px; padding: 10px; font-size: 16px; border-bottom: 3px solid #8C8C8C;"><strong>Reservation</strong> Information</h4>
                            <div class="table-responsive" style="padding:10px;">
                                <table class="table no-border no-margin">
                                    <tbody>
                                        <tr>
                                            <td>Pickup Date/Time : </td>
                                            <td><?php echo date("d-M-Y",strtotime($this->bookinginfo->pickup_date)),'&nbsp;&nbsp;'.$this->bookinginfo->pickup_time.":".$this->bookinginfo->pickup_mins;?></td>
                                        </tr>
                                        <tr>
                                            <td>Dropoff Date/Time : </td>
                                            <td><?php echo date("d-M-Y",strtotime($this->bookinginfo->pickup_date)),'&nbsp;&nbsp;'.$this->bookinginfo->pickup_time.":".$this->bookinginfo->pickup_mins;?></td>
                                        </tr>
                                        <tr>
                                            <td>Pickup Location : </td>
                                            <td><?php echo $this->bookinginfo->from_locationname;?></td>
                                        </tr>
                                        <tr>
                                        	<td>Dropoff Location : </td>
                                        	<td><?php echo $this->bookinginfo->to_locationname;?> </td>
                                        </tr>
                                        <tr>
                                        	<td>Trip Way : </td>
                                        	<td><?php echo ($this->bookinginfo->trip_way==1)?"One-Way":"Round Trip";?> </td>
                                        </tr>
                                        <tr>
                                        	<td>Time(s) : </td>
                                        	<td><?php echo $this->bookinginfo->time;?> </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                     </div>
                    </div>
                    <!--welcome ends-->
                </div>
                <!-- Footer Map -->
            </section>
            <!--welcome-wrap ends-->
            
        </div>
    </div>
</section>
<?php 
	$db = new Application_Model_DbTable_DbGlobal();
	$instruction = "instructiontaxi";
	$rows = $db->getAllParameter($instruction);
?>
<section class="content">
    <div class="container">
         <?php echo $rows;?> 
</div>
</section>
<script>
form_valid = 0;
function checkUserName(type){
	var checking_html = '<img src="<?php echo $this->baseUrl();?>/images/checkloading.gif" />';
	var available = '<img  src="<?php echo $this->baseUrl();?>/images/apply2.png" />';
	var unavailable = '<img title="User Name not available!" style="cursor:pointer" src="<?php echo $this->baseUrl();?>/images/cross.png" />';
	var emilunavailable = '<img title="Email not available!" style="cursor:pointer" src="<?php echo $this->baseUrl();?>/images/cross.png" />';
	var not_valid = '<img alt="Email not Valid!" title="Email not valid!" style="cursor:pointer" src="<?php echo $this->baseUrl();?>/images/none.png" />';
	var url = "<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'check-username-available'));?>";
	if(type==1){
		var user_name = $('#s_user_name').val();
		$('#username_availability_result').html(checking_html);
	}else{
		var user_name = $('#email').val();
		$('#email_availability_result').html(checking_html);
	}
	$.ajax({
        url: url,
        type: "post",
        data: {'user_name':user_name,'type':type},
        success: function(data){
            val = $.parseJSON(data);
			if(val==1){
				if(type==1){
					$('#username_availability_result').html(unavailable);
				}else{
					$('#email_availability_result').html(emilunavailable);
					$("#email").css("border", "1px solid red"); 
				}
				form_valid=1;
			}else{
				if(type==1){
					$('#username_availability_result').html(available);
				}else{
					var re = /^(([^<>()[\]\.,;:\s@\"]+(\.[^<>()[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i;
					email_validate = re.test(user_name);
					if(email_validate==true){
						$('#email_availability_result').html(available);
						form_valid=0;
					}else{
						$('#email_availability_result').html(not_valid);
						$("#email").css("border", "1px solid red"); 
						form_valid=1;
					}
					
				}
			}
        },
        error:function(e){
            alert(e);
        }
    });
}
function formValidate(){
	user_name =  $("#s_user_name").val();
	email =  $("#email").val();
	password = $("#s_password").val();
	first_name = $("#first_name").val();
	last_name= $("#last_name").val();
	phone = $("#phone").val();
	if(user_name==""){ 
        $("#s_user_name").css("border", "1px solid red"); 
        form_valid=1;
    } else {
		$("#s_user_name").css("border", "1px solid #E4E4E4");
	}
    if(email==""){ 
        $("#email").css("border", "1px solid red"); 
        form_valid=1;
    } else {
		$("#email").css("border", "1px solid #E4E4E4");
	}
    if(password=="") {  
        $("#s_password").css("border", "1px solid red"); 
        form_valid=1;
    } else {
		$("#s_password").css("border", "1px solid #E4E4E4");
	}
    if(first_name=="") {  
        $("#first_name").css("border", "1px solid red"); 
        form_valid=1;
    } else {
		$("#first_name").css("border", "1px solid #E4E4E4");
	}
    if(last_name=="") {  
        $("#last_name").css("border", "1px solid red"); 
        form_valid=1;
    } else {
		$("#last_name").css("border", "1px solid #E4E4E4");
	}
    if(phone=="") {  
        $("#phone").css("border", "1px solid red"); 
        form_valid=1;
    } else {
		$("#phone").css("border", "1px solid #E4E4E4");
	}
	if(form_valid==1){
		return false;
	}else{
		document.getElementById("signups").submit();
	}
}

function loginValidate(){
	user_name =  $("#user_name").val();
	password = $("#password").val();
	if(user_name==""){ 
        $("#user_name").css("border", "1px solid red"); 
        validate=1;
    } else {
		$("#user_name").css("border", "1px solid #E4E4E4");
		validate=0;
	}
	if(password=="") {  
        $("#password").css("border", "1px solid red"); 
        validate=1;
    } else {
		$("#password").css("border", "1px solid #E4E4E4");
		validate=0;
	}

	if(validate == 1){
		return false;
	}else{
		document.getElementById("login_taxi").submit();
	}
}
function signUp(){
	$('#signup_section').css("display", "block");
	$('#login_section').css("display", "none");
}
function logIn(){
	$('#signup_section').css("display", "none");
	$('#login_section').css("display", "block");
}
function paymentType(type){
	if(type==1){
		$('#visa').css("display","block");
		$('#ws_union').css("display","none");
		$('#wing').css("display","none");
	}else if(type==2){
		$('#ws_union').css("display","block");
		$('#visa').css("display","none");
		$('#wing').css("display","none");
	}else{
		$('#ws_union').css("display","none");
		$('#visa').css("display","none");
		$('#wing').css("display","block");
	}
}
$( document ).ready(function() {
	$( "#job-active" ).removeClass( "active" );
	$( "#home-active" ).removeClass( "active" );
	$( "#about-active" ).removeClass( "active" );
	$( "#contact-active" ).removeClass( "active" );
	$( "#service-active" ).removeClass( "active" );
	$( "#promo-active" ).removeClass( "active" );
	$( "#pralist-active" ).removeClass( "active" );
	$( "#booking-active" ).addClass( "active" );
});

function checkAgree(){
	var agree = $('#agree').val();
	if(agree=="on"){
		
		$('#c_agree').css("disabled","");
	}else{
		alert(2);
		$('#c_agree').css("disabled","disabled");
	}
}

function paymentValidate(){
	user_name =  $("#card_name").val();
	var payment_type = document.getElementsByName('payment_type');
	var rate_value;
	for(var i = 0; i < payment_type.length; i++){
	    if(payment_type[i].checked){
	        rate_value = payment_type[i].value;
	    }
	}
	lb_validate_credit_card_number = $("#lb_validate_credit_card_number").text();
	lb_validate_credit_card_expiry = $("#lb_validate_credit_card_expiry").text();
	lb_validate_credit_card_cvc = $("#lb_validate_credit_card_cvc").text();
	lb_validate_number = $("#lb_validate_number").text();
	if(rate_value==1){
		if(user_name=="" || lb_validate_credit_card_number=="Invalid" || lb_validate_credit_card_expiry=="Invalid" || lb_validate_credit_card_cvc=="Invalid"){
			validate=1;
		}else{
			validate=0;
		}
	}else if(rate_value==2){
		if(lb_validate_number=="Invalid"){
			validate=1;
		}else{
			validate=0;
		}
	}else{
		validate=0;
	}
	if(validate == 1){
		return false;
	}else{
		//$('#signup').submit();
		document.getElementById("payment").submit();
	}
}
</script>
<script src="<?php echo $this->baseUrl();?>/js/form-validate/scale.fix.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/form-validate/jquery.formance.min.js" /></script>
<script src="<?php echo $this->baseUrl();?>/js/form-validate/awesome_form.js"></script>