<?php 
	$db = new Application_Model_DbTable_DbGlobal();
	$var_desk_phone="desk_phone";
	$var_tel_cambodian = "tel_cambodian";
	$var_tel_english = "tel_english";
	$var_booking = "booking";
	$var_skype = "skype";
	$var_email = "email";
	$var_facebook = "facebook";
	$var_youtube = "youtube";
	$var_instantgram = "instantgram";
	$var_google_plus ="google_plus";
	$var_twitter = "twitter";
	$var_link_in = "link_in";
	$var_footerweb = "footer_webname";
	$below_sitelable = "below_sitelable";
	$copyright = "copyright_footer";
	$copyright = $db->getAllParameter($copyright);
	$var_footerweb = $db->getAllParameter($var_footerweb);
	$below_sitelable = $db->getAllParameter($below_sitelable);
	
	$desk_phone = $db->getAllParameter($var_desk_phone);
	$tel_cambodian = $db->getAllParameter($var_tel_cambodian);
	$tel_english = $db->getAllParameter($var_tel_english);
	$booking = $db->getAllParameter($var_booking);
	$skype = $db->getAllParameter($var_skype);
	$email = $db->getAllParameter($var_email);
	$facebook = $db->getAllParameter($var_facebook);
	$youtube = $db->getAllParameter($var_youtube);
	$linkin = $db->getAllParameter($var_link_in);
	$twiter = $db->getAllParameter($var_twitter);
	$google = $db->getAllParameter($var_google_plus);
	$instantgram =$db->getAllParameter($var_instantgram);
?>
<section class="content padding-bottom-30" style="border-top:3px solid #7D87FF; background: #0015FF;">
<div >
    <div class="container">
        <div class="homepage margin-bottom-none" >
	        <section class="welcome-wrap padding-top-30 sm-horizontal-15" >
				<div class="row" >
					<div style="height: 267px;" class="col-lg-4 col-md-4 col-sm-6 col-xs-12 padding-left-none md-padding-left-none sm-padding-left-15 xs-padding-left-15" >
		               <?php $db = new Application_Model_DbTable_DbGlobal(); $about = $db->getmenuaboutFooter();?>
		                <?php foreach ($about as $abouts){ ?>
		                	<h3> <?php echo $abouts['title']?></h3>
		                	<?php echo $abouts['description']?> 
		                <?php }?>
		            <a href="http://info.flagcounter.com/GRWa"><img src="http://s07.flagcounter.com/countxl/GRWa/bg_FFFFFF/txt_000000/border_CCCCCC/columns_4/maxflags_30/viewers_0/labels_0/pageviews_1/flags_0/percent_0/" alt="Flag Counter" border="0"></a>
		            </div>
		            <div style="border:2px solid #6772FD;height: 267px; background:#fff;" class="col-lg-4 col-md-4 col-sm-6 col-xs-12 padding-left-none md-padding-left-10 sm-padding-left-15 xs-padding-left-15" >
<div style="width: 320px;height: 70px;position: absolute;opacity: 0;z-index: 100000000;background:#000;">
							
						</div>
	                	 <h4 class="" style="font-size:20px;margin:0;margin-top:5px !important; text-align: center;"><img width="95px" src="<?php echo $this->baseUrl()."/images/testimonials.png"?>" /><strong>TESTIMONIALS</strong></h4>
	                	 <?php  $rows = $db->getAllGuestBookFooter();?>
		                <?php foreach ($rows as $row){ ?>
		                		<div style="color: blue;"><?php echo "Date : ".date("d-M-Y",strtotime($row["date"]))."| Subject :".substr($row['subject'],0, 20)?></div>
		                		<p style="border-bottom: 1px solid #ccc;text-align:justify;"><?php echo substr($row['comment'],0, 40);?>...</p>
		                <?php }?>
		               <p align="center"><a href="<?php echo  $this->baseUrl()."/index/guestbook"?>" style="text-align: center;">ADD YOUR <strong style="font-size:18px;">COMMENTS HERE</strong><img src="<?php echo $this->baseUrl()."/images/GuestBook1.png"?>" width="50px;" /></a></p>
<div style="position: absolute; z-index: 100;top: -151px;opacity: 0;">
				                    	
				         </div>
	                </div>
	                <div style="padding-right:1px !important; height: 267px; text-align: right;" class="col-lg-4 col-md-4 col-sm-6 col-xs-12 padding-left-none md-padding-left-none" style="border:2px solid red;">
							<script>(function(d, s, id) {
							  var js, fjs = d.getElementsByTagName(s)[0];
							  if (d.getElementById(id)) return;
							  js = d.createElement(s); js.id = id;
							  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
							  fjs.parentNode.insertBefore(js, fjs);
							}(document, 'script', 'facebook-jssdk'));</script>
			                <!--  <h4>Page Facebook </h4> -->
			                <div class="latest-tweet">
			                    <div>
			                    <div class="fb-page" data-href="<?php echo $facebook;?>" data-width="372" data-height="265" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="true">
				                    <div class="fb-xfbml-parse-ignore">
				                    	<blockquote cite="<?php echo $facebook;?>"><a href="<?php echo $facebook;?>">Facebook</a></blockquote>
				                    </div>
			                    </div>
			                    </div>
			                </div>
	                </div>
				</div>
			</section>
		</div>
	</div>
	</div>
</section>

<footer class="design_2"> 
</footer>

<div class="clearfix"></div>
<section class="copyright-wrap padding-bottom-10">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
                <div class="logo-footer margin-bottom-20 md-margin-bottom-20 sm-margin-bottom-10 xs-margin-bottom-20"><a href="#">
                    <h1 style="color:#fff;"><?php echo $var_footerweb;?></h1>
                    <span><?php echo $below_sitelable;?></span></a>
                <small>&copy;2001-<?php echo date("Y");?>&nbsp; <?php echo $copyright;?>&nbsp;&nbsp;Developed By <a href="http://www.vssservice.com" target="_blank">VSS Consultancy</a></small>
                </div>
            </div>
            <div class="col-lg-7 col-md-7 col-sm-6 col-xs-12">
            	<div class="" style="padding:25px 0; float: right;">
            		<ul class="footerSocial">
	                    <li><a class="sc-1" href="<?php echo $facebook;?>"><i class="fa fa-facebook-square"></i></a></li>
	                    <li><a class="sc-2" href="<?php echo $twiter; ?>"><i class="fa fa-twitter-square"></i></a></li>
	                    <li><a class="sc-3" href="<?php echo $linkin; ?>"><i class="fa fa-linkedin-square"></i></a></li>
	                    <li><a class="sc-4" href="<?php echo $google; ?>"><i class="fa fa-google-plus-square"></i></a></li>
	                    <li><a class="sc-5" href="<?php echo $youtube; ?>"><i class="fa fa-youtube-square"></i></a></li>
	                    <li><a class="sc-6" href="<?php echo $instantgram; ?>"><i class="fa fa-instagram"></i></a></li>
	                    <li><a class="sc-7" href="<?php echo $skype;?>"><i class="fa fa-skype"></i></a></li>
	                </ul>
            	</div>
            	<div class="" style="float: right;">
	                <ul class="footernavbar ">
	                    <li id="home-active" class="active"><a href="<?php echo $this->baseUrl();?>">Home</a></li>
                            <li id="about-active"><a href="<?php echo $this->baseUrl()?>/index/about">About Us </a></li>
                            <li id="job-active"><a href="<?php echo $this->baseUrl()?>/index/termcondition">Terms & Conditions</a>
                            <li id="job-active"><a href="<?php echo $this->baseUrl()?>/index/job">Job Vacancies</a>
                            <li id="contact-active"><a href="<?php echo $this->baseUrl()?>/index/policy">Privacy Policy</a></li>
                            <li id="service-active"><a href="<?php echo $this->baseUrl()?>/index/fqa">FAQs</a></li>
                            <li id="booking-active"><a href="<?php echo $this->baseUrl()?>/index/contact">Contact Us </a></li>
	                </ul>
<script type="text/javascript" async="async" defer="defer" data-cfasync="false" src="https://mylivechat.com/chatinline.aspx?hccid=76836371"></script>

                </div>
            </div>
        </div>
    </div>
</section>          