<?php 
$request=Zend_Controller_Front::getInstance()->getRequest();
$action=$request->getActionName();
$controller=$request->getControllerName();
$module=$request->getModuleName();

	$session_lang=new Zend_Session_Namespace('lang');
	//if(empty($lang_id)){
		//$session_lang->lang_id=2;
	//}
	$currentlang = $session_lang->lang_id;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$db = new Application_Model_DbTable_DbGlobalSelect();
	$slide = $db->getWebsiteSetting("slideshow");
	$row = $db->getWebsiteSetting('logo');
	$headerbg = $db->getWebsiteSetting('headebackground');
	$slides = explode(",", $slide['value']);
	$menu_items = $db->getMenuItems();
	
	$vdgb = new Application_Model_DbTable_DbVdGlobal();
	$alllang =  $vdgb->getLaguage();
	
	$client_session=new Zend_Session_Namespace('client');
	$cus_id =$client_session->client_id;
	$user_name = $client_session->client_name;
	
	$para=Zend_Controller_Front::getInstance()->getRequest()->getParam("param");
	$param = explode('.',$para);
	
	$indexparam=Zend_Controller_Front::getInstance()->getRequest()->getParams();
	//echo $db->getCurrentLang();
	$searchtxt = empty($indexparam['textsearch'])?'':$indexparam['textsearch'];
	$facebook = $db->getWebsiteSetting('facebook');
	$youtube = $db->getWebsiteSetting('youtube');
	$twitter = $db->getWebsiteSetting('twitter');
	$googleplus = $db->getWebsiteSetting('googleplus');
	$tel = $db->getWebsiteSetting('tel');
	$email = $db->getWebsiteSetting('email');
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
<meta name="description" content="">
<meta name="author" content="">
 <!-- Favicon Icon -->
 <link rel="shortcut icon" href="<?php echo $this->baseUrl();?>/images/icon.ico" type="image/x-icon"/>

<!-- Reset CSS -->
<link href="<?php echo $this->baseUrl();?>/templates/css/reset.css" rel="stylesheet" type="text/css">
<!-- Custom Fonts -->
<link href="<?php echo $this->baseUrl();?>/templates/css/fonts.css" rel="stylesheet" type="text/css">
<!-- Bootstrap -->
<link href="<?php echo $this->baseUrl();?>/templates/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<!-- Select2 -->
<link href="<?php echo $this->baseUrl();?>/templates/assets/select2/css/select2.min.css" rel="stylesheet" type="text/css">
<!-- Font Awesome -->
<link href="<?php echo $this->baseUrl();?>/templates/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<!-- Magnific Popup -->
<link href="<?php echo $this->baseUrl();?>/templates/assets/magnific-popup/css/magnific-popup.css" rel="stylesheet" type="text/css">
<!-- Iconmoon -->
<link href="<?php echo $this->baseUrl();?>/templates/assets/iconmoon/css/iconmoon.css" rel="stylesheet" type="text/css">
<!-- Owl Carousel -->
<link href="<?php echo $this->baseUrl();?>/templates/assets/owl-carousel/css/owl.carousel.min.css" rel="stylesheet" type="text/css">
<!-- Animate -->
<link href="<?php echo $this->baseUrl();?>/templates/css/animate.css" rel="stylesheet" type="text/css">

<!-- Custom Style -->
<link href="<?php echo $this->baseUrl();?>/templates/css/jquery.mmenu.all.css" rel="stylesheet" type="text/css">
<link href="<?php echo $this->baseUrl();?>/templates/css/template.css" rel="stylesheet" type="text/css">
<link href="<?php echo $this->baseUrl();?>/templates/css/custom.css" rel="stylesheet" type="text/css">
<link href="<?php echo $this->baseUrl();?>/templates/css/responsivemenu/css/responsivemultimenu.css" rel="stylesheet" type="text/css">
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> 
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/templates/js/jquery.min.js"></script> 
</head>
<script>		
			var url_changelang = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
			function changeLange(lang){
				jQuery.ajax({
					url: url_changelang,
					type: "post",
					data:{'lange':lang},
					success: function(data){
						location.reload();
					},
					error:function(err){
						
					}
				});
			}
			<?php if ($currentlang==1){?>
				var monthNames = [
				                  "Jan", "Feb", "Mar",
				                  "Apr", "May", "Jun", "Jul",
				                  "Aug", "September", "Oct",
				                  "Nov", "Dec"
				                ];
		      <?php }else{?>
		     var monthNames = [
			                  "មករា", "កុម្ភៈ", "មិនា",
			                  "មេសា", "ឧសភា", "មិថុនា", "កក្កដា",
			                  "សីហា", "កញ្ញា", "តុលា",
			                  "វិច្ឆិការ", "ធ្នូ"
			                ];
		      <?php }?>
		      var baseurl = '<?php echo $this->baseUrl();?>';
		      var currentlanguage='<?php echo $currentlang;?>';
	</script>
<body>

<!-- Start Header -->
<header style="background: url(<?php echo $this->baseUrl()."/images/headerbackground/".$headerbg['value'];?>) no-repeat;background-size: 100%;"> 
  <!-- Start Header Middle -->
  <div class="container header-middle">
    <div class="row"> <span class="col-xs-6 col-sm-3"><a class="logo" href="<?php echo $this->baseUrl();?>"><img src="<?php echo $this->baseUrl().'/images/lang/'.$row['value']?>" class="img-responsive" alt=""></a></span>
      <div class="col-xs-6 col-sm-3"></div>
      <div class="col-xs-6 col-sm-9">
        <div class="contact clearfix">
          <ul class="hidden-xs" style="
				background: rgba(255, 226, 15, 0.8);
				padding: 5px 0;
				-webkit-box-shadow: 7px 11px 43px -17px rgba(69,69,69,1);
				-moz-box-shadow: 7px 11px 43px -17px rgba(69,69,69,1);
				box-shadow: 7px 11px 43px -17px rgba(69,69,69,1);
				border-radius: 4px;
			">
            <li> <span><?php echo $tr->translate("EMAIL");?></span> <?php echo $email['value'];?> </li>
            <li> <span><?php echo $tr->translate("PHONE");?></span> <?php echo $tel['value'];?> </li>
			<li>
			    <div class="lang-wrapper">
				  <div class="select-lang2">
					<div class="lang">
                       <?php if (!empty($alllang)) foreach ($alllang as $ll){
						if ($currentlang != $ll['id']){?>
                          		<img title="<?php echo $tr->translate(strtoupper($ll['title']));?>" src="<?php echo $this->baseUrl()."/images/lang/".$ll['iconImage'];?>" onclick="changeLange('<?php echo $ll['id'];?>');" />
                            <?php }
						}?>
                     </div>
				  </div>
				</div>
			</li>
          </ul>
          
		  </div>
      </div>
    </div>
  </div>
  <!-- End Header Middle --> 
  <!-- Start Navigation -->
  <div class="menu_mobile">
 	 <a href="#primary-navigation" class="menu-button primary-navigation-button">
		<i class="fa fa-bars" aria-hidden="true"></i> <?php echo $tr->translate("MENU");?>
	</a>
  	<?php if (!empty($alllang)) foreach ($alllang as $ll){
		if ($currentlang != $ll['id']){?>
           <img title="<?php echo $tr->translate(strtoupper($ll['title']));?>" src="<?php echo $this->baseUrl()."/images/lang/".$ll['iconImage'];?>" onclick="changeLange('<?php echo $ll['id'];?>');" />
           <?php }
		}?>
	
  </div>
  <nav class="navbar navbar-inverse">
    <div class="container">
        <form action="<?php echo $this->baseUrl()."/index/result"?>" method="GET" class="navbar-form navbar-right">
          <input type="text" name="textsearch" placeholder="<?php echo $tr->translate("SEARCH_NOW");?>" value="<?php echo $searchtxt;?>" class="form-control">
          <button class="search-btn"><span class="icon-search-icon"></span></button>
        </form>
		  
			<nav id="primary-navigation" class="site-navigation main-menu">
				<div class="rmm style" >
					<ul id="primary-menu"  class="rmm-menu">
						<li class="<?php if($controller=="index" && $action=="index") { echo 'active';}?>"><a href="<?php echo $this->baseUrl();?>"><?php echo $tr->translate("HOME");?></a></li>
						<?php if (!empty($menu_items)) foreach ($menu_items as $menu){?>
	                    <li class="<?php if($menu['alias_menu']==$param[0]) { echo 'active';}?>">
	                      <a href="<?php echo $this->baseUrl()."/page/index?param=".$menu['alias_menu'].".html";?>"><?php echo $menu['title']; if (!empty($vdgb->checkSubMenu($menu['id']))){ ?><i class="icon-arrow-down"></i><?php }?></a>
	                      <?php echo $vdgb->getSubMaiMenu($this->baseUrl(), $menu['id']); ?>
	                    </li>
	                     <?php }?>
					</ul>
				</div>
			</nav>
		</div>
  </nav>
  <!-- End Navigation --> 
</header>
<!-- End Header -->