<?php 
	$db = new Application_Model_DbTable_DbGlobal();
	$var_desk_phone="desk_phone";
	$var_tel_cambodian = "tel_cambodian";
	$var_tel_english = "tel_english";
	$var_booking = "booking";
	$var_skype = "skype";
	$var_email = "email";
	$desk_phone = $db->getAllParameter($var_desk_phone);
	$tel_cambodian = $db->getAllParameter($var_tel_cambodian);
	$tel_english = $db->getAllParameter($var_tel_english);
	$booking = $db->getAllParameter($var_booking);
	$skype = $db->getAllParameter($var_skype);
	$email = $db->getAllParameter($var_email);
?>
<style>
	.toolbar .navbar-nav > li > a{padding:0 !important;}
	.toolbar .nav > li > a:hover, .nav > li > a:focus{background:none}
	.toolbar .nav-bar .li a{padding:0 !important}
	.toolbar .dropdown-menu{background-color:#8E0C83}
	.toolbar .navbar-nav > li > .dropdown-menu{background-color:#8E0C83; color:#fff}
	.toolbar .navbar-nav > li > .dropdown-menu li a{background-color:#8E0C83; color:#fff;padding:0px 10px;}
	header .toolbar > .navbar-nav > li > .dropdown-menu > li > a{padding:0;}
        .goog-te-gadget {
        font-size: 12px !important;
    }  
    .goog-te-gadget img {
        display: none;
    }
    .goog-te-gadget .goog-te-gadget-simple {
    	background:rgba(245, 245, 245, 0.97) !important;
        border-left: 1px solid #d5d5d5; 
     border-top: 0px !important; 
    border-bottom: 0px !important;
    border-right: 0px !important;
    font-size: 10pt; 
    display: inline-block;
    padding-top: 0px !important;
    padding-bottom: 0px !important;
    } 
</style>
	<header  data-spy="affix" data-offset-top="1" class="clearfix">
    <section class="toolbar">
        <!--<div class="container">-->
            <div class="row">
            	<nav>
                <div class="col-lg-3 collapse navbar-collapse" style="padding-left: 73px;">
                    <ul class="nav navbar-nav pull-left nav-bar">
                    	<?php 
                    		$customer_session  = new Zend_Session_Namespace('customer');
    						$user_session = $customer_session->customer_session;
    						if($user_session!=""){
								$user_name = $customer_session->customer_name;
    					?>
    						 <li class="dropdown li-dropdown" >
    						 	<a style="padding:0;" class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-user"></i> <?php echo $user_name;?></a>
    						 	<ul class="dropdown-menu li-menu">
    						 		<li><a href="<?php echo $this->baseUrl();?>/customer/dashboard"><i class="fa fa-cogs"></i> Profile</a></li>
    						 		<li><a href="<?php echo $this->baseUrl();?>/customer/logout/value/1"><i class="fa fa-power-off"></i> Log out</a></li>
    						 	</ul>
    						 </li>
    					<?php }else{?>
                        	<li><a href="<?php echo $this->baseUrl();?>/customer/customerlogin"><i class="fa fa-user"></i> Login</a></li>
                        <?php }?>
                        <li><div id="google_translate_element" style="float:left;"></div><script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
}
</script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script></li>
                    </ul>
                </div>
                </nav>
                <div class="col-lg-9 pull-right" style="padding-right: 73px;">
                    <ul class="right-none pull-right company_info">
                     <?php if(!empty($desk_phone)){?>   
                   <li><a href="tel:<?php echo $desk_phone;?>"><i class="fa fa-phone"></i> <?php echo $desk_phone;?></a></li>
<?php }?>
                        <li><a href="tel:<?php echo $tel_cambodian;?>"><i class="fa fa-phone"></i> <?php echo $tel_cambodian;?></a></li>
                        <li><a href="tel:<?php echo $tel_english;?>"><i class="fa fa-phone"></i> <?php echo $tel_english;?></a></li>
                        <li><a href="tel:<?php echo $booking;?>"><i class="fa fa-shopping-cart"></i><?php echo $booking;?></a></li>
                        <li><a href="mailto:<?php echo $booking;?>"><i class="fa fa-envelope-o"></i><?php echo $email;?></a></li>
                        <li><a href="skype:<?php echo $skype;?>"><i class="fa fa-skype"></i> <?php echo $skype;?></a></li>
<!--                         <li class="address"><a href="contact.html"><i class="fa fa-map-marker"></i> 107 Sunset Blvd., Beverly Hills, CA  90210</a></li> -->
                    </ul>
                </div>
            </div>
        <!--</div>-->
        <div class="toolbar_shadow"></div>
    </section>
    <div class="bottom-header" >
        <div class="container">
            <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid"> 
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                        <a class="navbar-brand" href="<?php echo $this->baseUrl();?>"><img src="<?php echo $this->baseUrl()?>/images/SL-Logo.png" /></a> </div>
                    
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav pull-right">
                            <li id="home-active" class="active"><a href="<?php echo $this->baseUrl();?>">HOME</a></li>
                            <li id="about-active" class="dropdown"><a href="<?php echo $this->baseUrl()?>/index/about">ABOUT US <b class="caret"></b></a></li>
                              <li id="booking-active" class="dropdown">
                                <a href="<?php echo $this->baseUrl()?>/index/bookingservice">BOOKING <b class="caret"></b></a>
		                            <!--<ul class="dropdown-menu">
		                                    <li><a href="<?php //echo $this->baseUrl()?>/index/vehiclelist">Car Rental Booking</a></li>
		                                    <li class="dropdown"><a href="<?php //echo $this->baseUrl()?>/taxi/index">Taxi Service Booking<b class="caret"></b></a></li>
		                                    <li class="dropdown"><a href="<?php //echo $this->baseUrl()?>/index/citytour">City Tour Service Booking<b class="caret"></b></a></li>
		                                    <li><a href="<?php //echo $this->baseUrl()?>/index/stuff">Products Rental Booking</a></li>
<li><a href="<?php //echo $this->baseUrl()?>/guidebooking">Guide & Chauffeur Rental Booking</a></li>
		                                    <li><a href="<?php //echo $this->baseUrl()?>/index/instruction">Booking Instruction</a></li>
		                            </ul>-->
		                    </li>
                            <li id="service-active"><a href="<?php echo $this->baseUrl()?>/index/service">Services</a></li>
                            <li id="promo-active" class="dropdown"><a href="<?php echo $this->baseUrl()?>/index/promo">PROMOTION </a></li>
                            <li id="carsale-active" class="dropdown"><a href="<?php echo $this->baseUrl()?>/index/carsales">CAR SAlES </a>
                            <li id="prayer-active" class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="<?php echo $this->baseUrl()?>/index/booking">Prayer<b class="caret"></b></a>
		                            <ul class="dropdown-menu">
		                            	<?php 
		                            	$rowprayer= Other_Model_DbTable_DbPlayerList::getAllPlayerListNameForMenu();
		                            	if(!empty($rowprayer)) foreach($rowprayer As $row){?>
		                            		<li><a href="<?php echo $this->baseUrl()."/index/prayer/id/".$row['id'];?>"><?php echo $row['title'];?></a></li>
		                            	<?php }?>
		                            </ul>
		                    </li>
                            <li id="job-active" class="dropdown"><a href="<?php echo $this->baseUrl()?>/index/job">JOB VACANCY </a>
                            
                            
                            <li id="otherinfo-active" class="dropdown"><a href="<?php echo $this->baseUrl()?>/index/infomation">OTHER INFORMATION </a>
                          <!--   <li id="pralist-active" class="dropdown"><a href="<?php //echo $this->baseUrl()?>/index/prayerlist">PRAYER LIST </a></li> -->
                            <li id="fqa-active" ><a style="text-transform: none !important;" href="<?php echo $this->baseUrl()?>/index/fqa">FAQs</a></li>
                            <li id="contact-active"><a href="<?php echo $this->baseUrl()?>/index/contact">Contact</a></li>
                        </ul>
                    </div>
                    <!-- /.navbar-collapse --> 
                </div>
                <!-- /.container-fluid --> 
            </nav>
        </div>
        <div class="header_shadow"></div>
    </div>
</header>
<script>
$( document ).ready(function() {
	<?php  $request=Zend_Controller_Front::getInstance()->getRequest(); ?>
	action='<?php echo $request->getActionName();?>';
	<?php 
	?>
	//alert(' link here'+action+' ');
	$( "#job-active" ).removeClass( "active" );
	$( "#home-active" ).removeClass( "active" );
	$( "#about-active" ).removeClass( "active" );
	$( "#contact-active" ).removeClass( "active" );
	$( "#service-active" ).removeClass( "active" );
	$( "#promo-active" ).removeClass( "active" );
	$( "#pralist-active" ).removeClass( "active" );
	$( "#booking-active" ).removeClass( "active" );
	if(action=='about'){
		$( "#about-active" ).addClass( "active" )

	}else if(action=='index'){
		$( "#home-active" ).addClass( "active" )
	}else if(action=='service'){
		$( "#service-active").addClass( "active" )
	}else if(action=='fqa'){
		$( "#fqa-active").addClass( "active" )
	}else if(action=='prayer'){
		$( "#prayer-active").addClass( "active" )
	}else if(action=='job'){
		$( "#job-active").addClass( "active" )
	}else if(action=='promo'){
		$( "#promo-active").addClass( "active" )
	}else if(action=='infomation'){
		$( "#otherinfo-active").addClass( "active" )
	}else if(action=='infomation'){
		$( "#otherinfo-active").addClass( "active" )
	}else if(action=='contact'){
		$( "#contact-active").addClass( "active" )
	}else if(action=='contact'){
		$( "#carsale-active").addClass( "active" )
	}	
	
										
	
	

});
</script>

