<title>Add Location</title>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.js"></script>
<link href="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.css" rel="stylesheet">
<form id="add_location" action="<?php echo $this->url(array('module'=>'location','controller'=>'location','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data" >
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>
	<table style="margin: 0 auto; width: 100%">
		<tr>
			<td>
				<fieldset>
					<legend><strong>Add Location</strong></legend>
					<table  width="100%" >
						<tr>
							<td align="center" valign="top">
								<table style="margin: 0 auto; width:100%;" cellspacing="10">
									<tr>
										<td>Location Name</td>
										<td><input dojoType="dijit.form.ValidationTextBox" class="fullside" required="true" id="location_name" name="location_name" value="" type="text"></td>
										<td>Province Name</td>
										<td>
											<select dojoType="dijit.form.FilteringSelect" name="province_name" id="province_name" class="fullside">
												<?php foreach ($this->provincelist as $row){?>
													<option value="<?php echo $row['id']?>"><?php echo $row['province_name']?></option>
												<?php }?>
											</select>
										</td>
										<td>Service Type</td>
										<td>
											<select Onchange="checkLocationType();" name="service_type" id="service_type"  dojoType="dijit.form.FilteringSelect" class="fullside">
													<option value="2">Normal</option>
													<option value="1">City Tour Place</option>
											</select>
										</td>
										
									</tr>
									<tr>
										<td>Location Type</td>
										<td>
											<select readonly="readonly" id="location_type" name="location_type" dojoType="dijit.form.FilteringSelect" class="fullside">
												<?php if(!empty($this->locationtype))foreach ($this->locationtype AS $row){?>
													<option value="<?php echo $row['id'];?>"><?php echo $row['title'];?></option>
												<?php }?>
											</select>
										</td>
										<td>Status</td>
										<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true"  class="fullside">
											    <option value="1" label="Active">Active</option>
											    <option value="0" label="Deactive">Deactive</option>
											</select>
										</td>
									</tr>
									<tr>
										<td colspan="6">
											<textarea class="ckeditor"  style="height:300px !important;" id="note" name="note"></textarea>
										</td>
									</tr>
									<tr>
										<td colspan="6" align="center">
											<div style="clear: both;"></div>
											<input type="hidden" dojoType="dijit.form.TextBox" id="record_row" name="record_row" />
											<div  id="store_record"></div>
											<input iconClass="dijitIconClear" type="button" onClick="addNewSeason();" label="Add Record Photo" dojoType="dijit.form.Button"/>
										</td>
									</tr>
									<tr>
										<td colspan="6" align="center">
											<input type="reset" value="សំអាត" label="Clear"dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
											<input type="submit" value="save_close" name="save_close" label="Save&Close" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
											<input type="submit" value="save_new" name="save_new" label="Save&New" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>

<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");
require(["dojo/ready"], function(ready){
	ready(function(){
		addNewRecord();
	});
});
function addNewRecord(){
	dojo.query("#store_record").append('');
	tmp='<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#store_record").append(tmp);
	thead='<th>Delete</th>';
	thead+='<th>Images Name</th>';
	fund_title=1;
	dojo.query("#head_title").append(thead);	
	dijit.byId('record_row').attr('value','');
	addNewSeason();
}
r=0;
function addNewSeason(){
	r++;
	tmp='<tr style="border:1px solid #ccc; font-size:12px;" id="row_guide'+r+'">'
	tmp+="</tr>";
		dojo.query("#t_amountmoneytype").append(tmp);
		
	temp='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="/lyna/trunk/public/images/Delete_16.png"></td>';
	temp+='<td><input type="file" name="photo'+r+'" id="photo'+r+'" /></td>';
	
		dojo.html.set(dojo.byId("row_guide"+r),temp, {
	    parseContent: true,
	     
	});
	if(dijit.byId("record_row").get('value')!="") {
		var ids = dijit.byId("record_row").value;
		dijit.byId("record_row").attr('value',ids+','+r);
	} else { dijit.byId("record_row").attr('value',r);}
}
function deleteRecord(index){
	var ids =dijit.byId('record_row').value;
	if(ids.length=='' || ids.length==null){
		dijit.byId('record_row').attr('value','');
		dojo.query("#row_guide"+ids).remove();
	}else{
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		dijit.byId('record_row').attr('value',strings);
		dojo.query("#row_guide"+index).remove();
	}
}
function checkLocationType(){
	service_type = dijit.byId('service_type').get('value');
	if(service_type==1){
		dijit.byId('location_type').set('readOnly',false);
	}else{
		dijit.byId('location_type').set('readOnly',true);
	}
}
 
</script>
