<?php 
	  $url_save = $this->url(array('module'=>'vehicle','controller'=>'index','action'=>'edit'));
	  $tr=Application_Form_FrmLanguages::getCurrentlanguage();
      $rows_engine=$this->rows_engine;
      $rows_type=$this->rows_type;
      $rows_tran=$this->rows_tran;
      $rows_veh_typ=$this->rows_veh_typ;
      $rowv=$this->row_vehicle;
?>
<?php $tr=Application_Form_FrmLanguages::getCurrentlanguage();
 echo '<title>'. $tr->translate("VEHICLE").'</title>';
?>
<style>
   /* input[type="file"]{
	width: 90px;
   	height:20px;
} */
.form-group.bg {
    background: #f2f4fa;
    padding: 10px 0;
}
img.image_view {
    width: 100px;
	/* height: 50px; */
    padding-bottom: 2px;
}
.bg{ border:1px solid #eee;}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
			if(dijit.byId('branch_id').get('value')==''){
					alert('Please Select Branch');
					dijit.byId('branch_id').focus();
					return false;
			    }
				if(dijit.byId('province').get('value')==0){
					alert('Province required');
					dijit.byId('province').focus();
					return false;
			    }
                if(dijit.byId('situ_status').get('value')==''){
					alert('Province situ_status');
					dijit.byId('situ_status').focus();
					return false;
			    }
				return true;
			} else {
				return false;
			}
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);

var make_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->all_make));?> );
dojo.ready(function(){
new dijit.form.FilteringSelect({
    store: make_store,
    autoComplete: true,                        
    required: true,
    id: "make",
    name: "make",  
    value:'<?php echo $rowv['make_id'];?>',     
    class: 'fullside',            
    onChange: function() {  
    	make_id = dijit.byId('make').get('value');
    	if(make_id==-1){
			dijit.byId('pop_make').show();
	     }
    	else {
    		dijit.byId('model').attr('value','');
    		getallModel(make_id);
    	}           
    }
}, "make");

	new dijit.form.FilteringSelect({
	   // store: make_store,
	    autoComplete: true,                        
	    required: true,
	    id: "model",
	    name: "model", 
	    value:'<?php echo $rowv['model_id'];?>',          
	    class: 'fullside',            
	    onChange: function() {  
	    	model_id = dijit.byId('model').get('value');
	    	if(model_id==-1){
		    	make_id=dijit.byId('make').get('value');
		    	dijit.byId('txt_makeid').attr('value',make_id);
				dijit.byId('pop_model').show();
				//dijit.byId('model').attr('value','');
		     }else{
		    	// alert(model_id);
		    	   getallSubModel(model_id);
		    	   dijit.byId('submodel').attr('value','');
		     }
	    }
	}, "model");
	dijit.byId('year').attr('value','<?php echo $rowv['year'];?>');
	dijit.byId('engine').attr('value','<?php echo $rowv['engine'];?>');
	dijit.byId('transmission').attr('value','<?php echo $rowv['transmission'];?>');
	dijit.byId('type').attr('value','<?php echo $rowv['type'];?>');
	dijit.byId('vehicle_type').attr('value','<?php echo $rowv['car_type'];?>');
	
	new dijit.form.FilteringSelect({
	   // store: make_store,
	    autoComplete: true,                        
	    required: true,
	    id: "submodel",
	    name: "submodel",   
	    value:"<?php echo $rowv['sub_model'];?>",        
	    class: 'fullside',            
	    onChange: function() {  
	    	make_id = dijit.byId('submodel').get('value');
	    	if(make_id==-1){
		    	model_id=dijit.byId('model').get('value');
		    	dijit.byId('txt_model_id').attr('value',model_id);
		    	//make setvalue hiden
		    	txt_make_id=dijit.byId('make').get('value');
		    	dijit.byId('txt_make_id').attr('value',txt_make_id);
				dijit.byId('pop_submodel').show();
				//dijit.byId('model').attr('value','');
		     }
	    }
	}, "submodel");
	getallModel('<?php echo $rowv['make_id'];?>');
	
	}); 
var model_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_getmake = '<?php echo $this->url(array('module'=>'vehicle','controller'=>'submodel','action'=>'get-model')); ?>';
function getallModel(make_id){
		dojo.xhrPost({
			url:url_getmake,
			content:{
				'make_id':make_id
				},
			handleAs:"json",
			load: function(data) {
				model_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('model').set('store',model_store);  
			    dijit.byId('model').attr('value','<?php echo $rowv['model_id'];?>'); 
			},
			error: function(err) {
				alert(err);
			}
		});
}
var submodel_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_getsubmodel = '<?php echo $this->url(array('module'=>'vehicle','controller'=>'index','action'=>'get-sub-model')); ?>';
function getallSubModel(model_id){
	if(model_id==''){
	      return false;
		}
		dojo.xhrPost({
			url:url_getsubmodel,
			content:{
				'model_id':model_id
				},
			handleAs:"json",
			load: function(data) {
				//alert(data);
				submodel_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('submodel').set('store',submodel_store);   
			    dijit.byId('submodel').attr('value','<?php echo $rowv['sub_model'];?>'); 
			},
			error: function(err) {
				alert(err);
			}
		});
}

</script>
<form id='add_client' action="<?php echo $url_save; ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<div class="clearfix"></div>
	<div class="row">
      	 <div class="col-md-12 col-xs-12 forms_padding">
	          <div class="x_panel">
	              <div class="x_title">
	                 <h2><i class="fa  fa-edit" aria-hidden="true"></i> <?php echo $tr->translate('Edit Vehicle')?></h2>
	                 <ul class="nav navbar-right panel_toolbox">
	                    <li>
	                    	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	                    </li>
	               	</ul>
	               <div class="clearfix"></div>
	          	</div>
	       		<div class="x_content">
	       		 <div class="" role="tabpanel" data-example-id="togglable-tabs">
                      <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true"><?php echo $tr->translate('Vehicle Infomation')?></a>
                        </li>
                        <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false"><?php echo $tr->translate('Price And Photo')?></a>
                        </li>
                      </ul>
                      <div id="myTabContent" class="tab-content">
                        <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                        	 <div class="col-md-8 col-sm-8 col-xs-12">
	                        	 	<div class="title_form_blog">
						               		<h4><i class="fa  fa-car" aria-hidden="true"></i> <?php echo $tr->translate('Vehicle Information')?></h4>
						             </div>
	                        	 	<div class="form-group">
					                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Vehicle Ref.No.')?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                   		<input type="hidden" name="id" value="<?php echo $rowv['id'];?>"/>
					                    	<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="vehicle_ref_no" name="vehicle_ref_no" value="<?php echo $rowv['reffer'];?>" type="text" required="true">
					                   </div>
					                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Frame No")?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                    	<input tabindex="14"dojoType="dijit.form.ValidationTextBox" class="fullside" id="frame_no" name="frame_no" value="<?php echo $rowv['frame_no'];?>" type="text" required="true">
					                   </div>
					                </div>
					                <div class="form-group">
					                	<label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Vehicle Type')?></label>
					                    <div class="col-md-4 col-sm-4 col-xs-12">
						                 	<select name="vehicle_type" id="vehicle_type" dojoType="dijit.form.FilteringSelect" class="fullside">
												<?php foreach ($rows_veh_typ as $rs){?>
												<option value="<?php echo $rs['id'];?>" ><?php echo $rs['title'];?></option>
												<?php }?>
											</select>
					                   </div>
					                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Year')?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                 		 <select name="year" id="year" dojoType="dijit.form.FilteringSelect" class="fullside">
												<?php $year=1995;    $i=1;
												      for($i;$i < 25;$i++){
												      	$year=$year+1;?>
												 <option  value="<?php echo $year;?>"><?php echo $year;?></option>
												 <?php }?>
												</select>
					                   </div>
				               	 </div>
				               	 <div class="form-group">
				                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Make')?>
				                   </label>
				                   <div class="col-md-4 col-sm-4 col-xs-12">
				                 		 <input id="make" />
				                   </div>
				                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Model')?>
				                   </label>
				                   <div class="col-md-4 col-sm-4 col-xs-12">
				                 	  <input id="model" />
				                   </div>
				                </div>
				               	 <div class="form-group">
					                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Sub Model')?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                 	  <input id="submodel" />
					                   </div>
					                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Licence Plate No")?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                  	 <input dojoType="dijit.form.TextBox" class="fullside" id="licence_piate_no" name="licence_piate_no" value="<?php echo $rowv['licence_plate'];?>" type="text">
					                   </div>
				                </div>
				                 <div class="title_form_blog">
				               		<h4><i class="fa  fa-car" aria-hidden="true"></i> <?php echo $tr->translate('Drive Information')?></h4>
				               	</div>
				               	  <div class="form-group">
					                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Color')?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                 	 <input tabindex="7" dojoType="dijit.form.TextBox" class="fullside" id="color" name="color" value="<?php echo $rowv['color'];?>" type="text">
					                   </div>
					                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Transmission Type")?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                   		<select name="transmission" id="transmission" dojoType="dijit.form.FilteringSelect" class="fullside" >
										     <?php foreach ($rows_tran as $rs){?>
										     <option value="<?php echo $rs['id'];?>"><?php echo $rs['tran_name'];?></option>
										     <?php }?>
										</select>
					                   </div>
					                </div>
				               		<div class="form-group">
					                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Maximum Weight")?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                 	 <input dojoType="dijit.form.TextBox" class="fullside" id="maximum_weight" name="maximum_weight" value="<?php echo $rowv['max_weight'];?>" type="text">
					                   </div>
					                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("No. of Seats")?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                 	  <input tabindex="17" dojoType="dijit.form.NumberTextBox" class="fullside" id="no_of_seats" name="no_of_seats" value="<?php echo $rowv['seat_amount'];?>" type="text">
					                   </div>
					                </div>
					                <div class="form-group">
					                	<label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Horse Power')?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                 	 <select name="engine" id="engine" dojoType="dijit.form.FilteringSelect" class="fullside" >
									         <?php foreach ($rows_engine as $rs){?>
									         <option value="<?php echo $rs['id'];?>" ><?php echo $rs['capacity'];?></option>
									         <?php }?>
										</select>
					                   </div>
					                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Engine Number')?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                 		<input tabindex="9" dojoType="dijit.form.TextBox" class="fullside" id="engine_number" name="engine_number" value="<?php echo $rowv['engine_number'];?>" type="text">
					                   </div>
					                </div>
					                 <div class="form-group">
						                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Chasis No')?>
						                   </label>
						                   <div class="col-md-4 col-sm-4 col-xs-12">
						                 		<input tabindex="10"dojoType="dijit.form.TextBox" class="fullside" id="chassis_no" name="chassis_no" value="<?php echo $rowv['chassis_no'];?>" type="text">
						                   </div>
						                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Cylinders Disp')?>
						                   </label>
						                   <div class="col-md-4 col-sm-4 col-xs-12">
						                	   <input tabindex="11" dojoType="dijit.form.TextBox" class="fullside" id="cylinders_dip" name="cylinders_dip" value="<?php echo $rowv['cylinders_dip'];?>" type="text">
						                   </div>
						                </div>
						                 <div class="form-group">
						                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('No. Of Axles')?>
						                   </label>
						                   <div class="col-md-4 col-sm-4 col-xs-12">
						                 		<input tabindex="11" dojoType="dijit.form.TextBox" class="fullside" id="of_axlex" name="of_axlex" value="<?php echo $rowv['of_axlex'];?>" type="text">
						                   </div>
						                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('No. Of Cylinders')?>
						                   </label>
						                   <div class="col-md-4 col-sm-4 col-xs-12">
						                 		<input tabindex="13" dojoType="dijit.form.TextBox" class="fullside" id="of_cylinder" name="of_cylinder" value="<?php echo $rowv['of_cylinder'];?>" type="text">
						                   </div>
						                </div>
						                <div class="form-group">
						                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Type")?>
						                   </label>
						                   <div class="col-md-4 col-sm-4 col-xs-12">
						                   		<select name="type" id="type" dojoType="dijit.form.FilteringSelect" class="fullside">
											         <?php foreach ($rows_type as $rs){?>
											         <option value="<?php echo $rs['id'];?>" ><?php echo $rs['type'];?> </option>
											         <?php }?>
												</select>
						                   </div>
						                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Steering Wheel")?>
						                   </label>
						                   <div class="col-md-4 col-sm-4 col-xs-12">
						                   		<input tabindex="23" dojoType="dijit.form.TextBox" class="fullside" id="steering" name="steering" value="<?php echo $rowv['steering'];?>" type="text">
						                   </div>
						                </div>
                        	 </div>
                        	<div class="col-md-4 col-sm-4 col-xs-12">
                        	 	 <div class="title_form_blog">
					              	<h4><i class="fa  fa-car" aria-hidden="true"></i> <?php echo $tr->translate('Other Information')?></h4>
					              </div>
					              <div class="form-group">
					                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate("Original Cost")?>
					                   </label>
					                   <div class="col-md-8 col-sm-8 col-xs-12">
					                   		<input tabindex="19" dojoType="dijit.form.NumberTextBox" class="fullside" id="original" name="original" value="<?php echo $rowv['org_cost'];?>" type="text">
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate("Date Buy")?>
					                   </label>
					                   <div class="col-md-8 col-sm-8 col-xs-12">
					                  	 <input tabindex="20"  name="date_buy" id="date_buy" dojoType="dijit.form.DateTextBox"  class="fullside" value="<?php echo $rowv['date_buy'];?>" type="text"/>
					                   </div>
					                </div>
					                 <div class="form-group">
					                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate("Test Drive URL")?>
					                   </label>
					                   <div class="col-md-8 col-sm-8 col-xs-12">
					                   		<input tabindex="11" dojoType="dijit.form.TextBox" class="fullside" id="test_url" name="test_url" value="<?php echo $rowv['test_url'];?>" type="text">
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate("Show URL")?>
					                   </label>
					                   <div class="col-md-8 col-sm-8 col-xs-12">
					                   		<input tabindex="13" dojoType="dijit.form.TextBox" class="fullside" id="show_url" name="show_url" value="<?php echo $rowv['show_url'];?>" type="text">
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate("Note")?>
					                   </label>
					                   <div class="col-md-8 col-sm-8 col-xs-12">
					                   	<textarea tabindex="21" dojoType="dijit.form.TextBox" class="fullside" id="note" name="note"><?php echo $rowv['description'];?></textarea>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS")?>
					                   </label>
					                   <div class="col-md-8 col-sm-8 col-xs-12">
					                   		<select name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside">
											    <option value="1" <?php if ($rowv['status']==1){ echo 'selected="selected"';}?> label="Active">Active</option>
											    <option value="0" <?php if ($rowv['status']==0){ echo 'selected="selected"';}?> label="Deactive">Deactive</option>
											</select>
					                   </div>
					                </div>
					        </div>
		                 </div>
		                 <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
								<div class="col-md-8 col-sm-8 col-xs-12">	
									<div class="form-group">
					                   <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name"><?php echo $tr->translate('Deposit')?>
					                   </label>
					                   <div class="col-md-3 col-sm-3 col-xs-12">
					                 	<input dojoType="dijit.form.TextBox" class="fullside" id="deposit" name="deposit" value="<?php echo $rowv['ordering'];?>" type="text">
					                   </div>
					                   <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name"><?php echo $tr->translate("Road Side Assistance")?>
					                   </label>
					                   <div class="col-md-3 col-sm-3 col-xs-12">
					                 		<input dojoType="dijit.form.NumberTextBox" class="fullside" id="root_side_ass" name="root_side_ass" value="<?php echo $rowv['root_side_ass'];?>" type="text">
					                   </div>
				               		 </div>	
				               		 <?php 
						            if($rowv['is_promotion']==1){
							            	$selected ='checked="checked"';
							            }
							            else{
							            	$selected='';
							            }
							        ?>
					                <div class="form-group" style=" background: #eefff1; padding-top: 15px;  margin: 0;">
					                   <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name"><?php echo $tr->translate('Discount')?> <span><input dojoType="dijit.form.CheckBox" class="fullside" id="discount" name="discount" <?php echo $selected;?>  type="checkbox"></span>
					                   </label>
					                </div>
					                <div class="form-group" style=" background: #eefff1; padding-bottom: 15px; margin-bottom: 0;">
					               		<label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name"><?php echo $tr->translate("Discount Value");?>(%)
					                   	</label>
					                    <div class="col-md-3 col-sm-3 col-xs-12">
					                   		<input dojoType="dijit.form.TextBox" class="fullside" id="discount_value" name="discount_value" value="<?php echo $rowv['discount'];?>" type="text">
					                    </div>
					                </div>
					                 <div class="form-group" style=" background: #eefff1; padding-bottom: 15px;">
					                 	<label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name"><?php echo $tr->translate("From");?> 
					                   	</label>
					                    <div class="col-md-3 col-sm-3 col-xs-12">
					                   		 <input dojoType="dijit.form.DateTextBox"  id="discount_fromdate" name="discount_fromdate" value="<?php echo $rowv['discount_fromdate'];?>" type="text">
					                    </div>
					                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name"><?php echo $tr->translate("To");?> 
					                   </label>
					                    <div class="col-md-3 col-sm-3 col-xs-12">
					                   		<input dojoType="dijit.form.DateTextBox" id="discount_todate" name="discount_todate" value="<?php echo $rowv['discount_todate'];?>" type="text">
					                    </div>
					                 </div>
					                 <div class="form-group" style=" background: #f0f0f0; margin-bottom: 0;">
					                 	<label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name"><?php echo $tr->translate("Vehicle for Sale");?><span><input dojoType="dijit.form.CheckBox" class="fullside" id="is_sale" name="is_sale"  <?php if($rowv['is_sale']==1){ echo "checked='checked'";}?>  type="checkbox"></span>
					                   	</label>
					                 </div>
					                 <div class="form-group" style=" background: #f0f0f0;  padding: 15px 0;">
					               		<label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name"><?php echo $tr->translate("Price");?>
					                   	</label>
					                    <div class="col-md-3 col-sm-3 col-xs-12">
					                   		<input dojoType="dijit.form.TextBox" class="fullside" id="sale_price" name="sale_price" value="<?php echo  $rowv['sale_price'];?>" type="text" >
					                    </div>
					                	 <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name"><?php echo $tr->translate("Description Car Sales");?> 
					                   	</label>
					                    <div class="col-md-3 col-sm-3 col-xs-12">
					                    	<input dojoType="dijit.form.TextBox" class="fullside" id="desc_sale" name="desc_sale" value="<?php echo  $rowv['description_sale'];?>" type="text" style="height:60px;">
						                </div>
						            </div>
								</div>			
								<div class="col-md-4 col-sm-4 col-xs-12">
		                		<div class="text-center">
		                			<table class="table" style="margin: 0 auto; width: 100%; border-collapse: collapse;">
										<tr id="head-title" class="head-td"  style="background: #f8f6f6;"></tr>
									</table>
		                		</div>
		                		<div class="form-group " style="max-height: 244px;  min-height: 244px;    overflow: auto;     border: solid 1px #eee">
			                		<table id="table_parent" class="set-style" style="margin: 0 auto; width: 100%;  " >
										<thead>
											<tr>
												<td colspan="8">
													
													<table id="table_row"   style="margin: 0 auto; width: 100%; border-collapse: collapse; ">
													</table>
												</td>
											</tr>
										</thead>
									</table>
								</div>
								<div class="text-center">
									<input type="button" label="<?php echo $tr->translate('ADD_MORE');?>" dojoType="dijit.form.Button" 
														 	iconClass="dijitIconEditProperty" onclick="addRow();" />
									<input type="hidden" name="identity" id="identity"  value="" >
								</div>
		                	</div>			
                     </div>
                  </div>
               </div>
       		</div>
       	</div>
     </div>
	     <div class="clearfix"></div>
	     <div class="col-md-12 col-xs-12 forms_padding text-center">
	      	<input type="reset" style="color:#000;" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
				iconClass="dijitIconClear" /> 
			<input type="submit" value="SAVE_CLOSE" label="<?php echo $tr->translate('SAVECLOSE');?>" style="color:#000;" id="save_close" dojoType="dijit.form.Button" name="save_close"
				iconClass="dijitEditorIcon dijitEditorIconSave" /> 
	     </div>
	  </div>
	   <div class="clearfix"></div>
</form>
<div class="dijitHidden">
				<div data-dojo-type="dijit.Dialog"  id="frm_district" >
				<form id="form_district" ><table style="margin: 0 auto; width: 100%;" cellspacing="7">
					<tr>
						<td>District Name English</td>
						<td>
<input dojoType="dijit.form.ValidationTextBox" required="true" missingMessage="Invalid Module!" class="fullside" id="pop_district_name" name="pop_district_name" value="" type="text"></td>
					</tr>
								<tr>
						<td>Province Name English</td>
						<td>
<input dojoType="dijit.form.ValidationTextBox" required="true" missingMessage="Invalid Module!" class="fullside" id="pop_district_namekh" name="pop_district_namekh" value="" type="text"></td>
					</tr>
					<tr>
						<td>District Name Khmer</td>
						<td>
							<select name="province_names" id="province_names" dojoType="dijit.form.FilteringSelect" class="fullside" onchange="filterDistrict();">
							    <option value="" label="-----Select Province-----">-----Select Province-----</option>
							    <option value="1" label="Phnom Penh-ភ្នំពេញ">Phnom Penh-ភ្នំពេញ</option>
							</select>
						</td>
					</tr>
					
					<tr>
						<td colspan="2" align="center">
						<input type="button" value="Save" label="Save" dojoType="dijit.form.Button"
						iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewDistrict();"/>
						</td>
				    </tr>
				</table></form></div>
		</div><div class="dijitHidden">
				<div data-dojo-type="dijit.Dialog"  id="frm_village" >
					<form id="form_village" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
        </script>
		<table style="margin: 0 auto; width: 95%;" cellspacing="10">
					    <tr>
							<td>Village KH</td>
							<td>
							   <input dojoType="dijit.form.ValidationTextBox" required="true" missingMessage="Invalid Module!" class="fullside" id="village_namekh" name="village_namekh" value="" type="text"></td>
						</tr>
						<tr>
							<td>Village Name EN</td>
							<td>
								<input dojoType="dijit.form.ValidationTextBox" required="true" missingMessage="Invalid Module!" class="fullside" id="village_name" name="village_name" value="" type="text"></td>
						</tr>
						<tr>
							<td>Display By</td>
							<td>
								<select name="display" id="display" dojoType="dijit.form.FilteringSelect" class="fullside">
								    <option value="1" label="Name KH">Name KH</option>
								    <option value="2" label="Name(Last,First) In English">Name(Last,First) In English</option>
								</select></td>
						</tr>
						<tr>
							<td>Province Name</td>
							<td>
								<select name="province_name" id="province_name" dojoType="dijit.form.FilteringSelect" required="true" class="fullside" onchange="filterDistrict();" invalidMessage="">
								    <option value="0" label="-----Select Province-----">-----Select Province-----</option>
								    <option value="1" label="Phnom Penh-ភ្នំពេញ">Phnom Penh-ភ្នំពេញ</option>
								  
								</select></td>
						</tr>
						<tr>
							<td>District Name</td>
							<td>
								<select name="district_name" id="district_name" dojoType="dijit.form.FilteringSelect" class="fullside" required="true">
								    <option value="0" label="-----Select District-----">-----Select District-----</option>
								    <option value="1" label="ចំការមន-Chamkarmon">ចំការមន-Chamkarmon</option>
								   
								</select>
							</td>
						</tr>
						<tr>
							<td>Commune Name</td>
							<td>
								<select name="commune_name" id="commune_name" dojoType="dijit.form.FilteringSelect" class="fullside" required="true">
								    <option value="1" label="Tonle Bassak">Tonle Bassak</option>
								    <option value="2" label="Boeng Keng Kang I">Boeng Keng Kang I</option>
								    <option value="3" label="Boeng Keng Kang II">Boeng Keng Kang II</option>
								   
								</select>
						  </td>
						</tr>
						<tr>
							<td>Status</td>
							<td></td>
						</tr>
						<tr>
							<td colspan="2" align="center">
											<input type="reset" value="សំអាត" label=Clear dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
											<input type="button" value="save_close" name="save_close" label="Save" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" Onclick="addVillage();"  />
							</td>
						</tr>
					</table></form></div>
		</div><div class="dijitHidden">
				<div data-dojo-type="dijit.Dialog"  id="frm_commune" >
					<form id="form_commune" ><table style="margin: 0 auto; width: 100%;" cellspacing="7">
					<tr>
						<td>Commune Name EN</td>
						<td>
							<input dojoType="dijit.form.ValidationTextBox" required="true" missingMessage="Invalid Module!" class="fullside" id="commune_nameen" name="commune_nameen" value="" type="text"></td>
					</tr>
					<tr>
						<td>Commune KH</td>
						<td>
							<input dojoType="dijit.form.ValidationTextBox" required="true" missingMessage="Invalid Module!" class="fullside" id="commune_namekh" name="commune_namekh" value="" type="text"></td>
					</tr>
					<tr>
						<td>District Name</td>
						<td>
							<select name="district_nameen" id="district_nameen" dojoType="dijit.form.FilteringSelect" class="fullside">
							    <option value="1" label="ចំការមន-Chamkarmon">ចំការមន-Chamkarmon</option>
							    <option value="2" label="ដូនពេញ-Daun Penh">ដូនពេញ-Daun Penh</option>
							  
							</select></td>
					</tr>
					<tr>
						<td colspan="2" align="center">
						<input type="button" value="Save" label="Save" dojoType="dijit.form.Button"
						iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewCommune();"/>
						</td>
					</tr>
				</table></form></div>
			</div><div class="dijitHidden">
				<div data-dojo-type="dijit.Dialog"  id="frm_clienttype" >
					<form id="form_clienttype" ><table style="margin: 0 auto; width: 100%;" cellspacing="7">
					<tr>
						<td>Document Type EN</td>
						<td>
							<input dojoType="dijit.form.TextBox" class="fullside" id="clienttype_nameen" name="clienttype_nameen" value="" type="text"></td>
					</tr>
					<tr>
						<td>Document Type KH</td>
						<td>
						<input dojoType="dijit.form.TextBox" class="fullside" id="clienttype_namekh" name="clienttype_namekh" value="" type="text"></td>
					</tr>
					
					<tr>
						<td colspan="2" align="center">
						<input type="button" value="Save" label="Save" dojoType="dijit.form.Button"
						iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewDocumentType();"/>
						</td>
					</tr>
				</table>
</form>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_make" title="<?php echo $tr->translate("Add New Make")?>">
		<form id='frm_make' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td><?php echo $tr->translate("Make Name")?></td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="txt_make" name="txt_make" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="<?php echo $tr->translate("SAVE")?>" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addMake();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_model" title="<?php echo $tr->translate("Add Model")?>">
		<form id='frm_model' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td><?php echo $tr->translate("Model Name")?></td>
				<td>
				<input dojoType="dijit.form.ValidationTextBox" required="true" id="txt_model" name="txt_model" value="" type="text">
				<input dojoType="dijit.form.TextBox" id="txt_makeid" name="txt_makeid" type="hidden"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="<?php echo $tr->translate("SAVE")?>" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addModel();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_submodel" title="<?php echo $tr->translate("Add Sub Model")?>">
		<form id='frm_sub_model' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td><?php echo $tr->translate("Sub Model")?></td>
				<td>
					<input dojoType="dijit.form.ValidationTextBox" required="true" id="txt_submodel" name="txt_submodel" value="" type="text">
					<input dojoType="dijit.form.TextBox" id="txt_model_id" name="txt_model_id" type="hidden">
					<input dojoType="dijit.form.TextBox" id="txt_make_id" name="txt_make_id" type="hidden">
				</td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="<?php echo $tr->translate("SAVE")?>" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addSubModel();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<script type="text/javascript">
dojo.require("dijit.form.Textarea"); 
dojo.require("dojo.parser");
dojo.require("dojo.NodeList-manipulate");
</script>
<script type="text/javascript">
require(["dojo/ready"], function(ready){
	ready(function(){
		initailize();
	});
});
var col = 0;
var no = 0;
var title = 0;
func='';
tmp = '';
var temp='';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th style="text-align: center;"><?php echo $tr->translate("IMAGE");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td style="text-align: center; padding: 2px 0; width: 10%;" >'+col+'</td>';
			template+='<td style="text-align: center; padding: 2px 0;" ><img class="image_view" id="image_view'+col+'" src="<?php echo $this->baseUrl().'/images/no-image.png';?>" alt=""  /></td>';
			template+='<td><div class="button_browse"><span>Upload <span><i class="fa fa-camera" aria-hidden="true"></i></span></span><input class="btn_borwse_image" required="true" type="file" id="photo'+col+'" name="photo'+col+'" onchange="loadImage('+col+')"></div></td>';
			template+='<td align="center" style=" padding: 10px;"><img style=" cursor: pointer;" onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		tmp='<tr id="row'+col+'" style="background: #fff;">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!='') {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }

<?php $image = explode(",", $rowv['images_list']);

?>
function initailize() {
	<?php if (!empty($image)) foreach ($image as $rs){?>
	col++;no++;
	template='';
	if(title!=1){
		temp+='<th style="text-align: center;"><?php echo $tr->translate("IMAGE");?></th>';
		dojo.query("#head-title").append(temp);
		title=1;
	}
		template+='<td style="text-align: center; padding: 2px 0; width: 10%;" >'+col+'</td>';
		template+='<td ><input type="hidden" id="old_photo'+col+'" name="old_photo'+col+'" value="<?php echo $rs;?>"><img class="image_view" id="image_view'+col+'" src="<?php echo $this->baseUrl().'/images/vehicle/'.$rs;?>" alt=""  /></td>';
		template+='<td><div class="button_browse"><span>Upload <span><i class="fa fa-camera" aria-hidden="true"></i></span></span><input class="btn_borwse_image" type="file" id="photo'+col+'" name="photo'+col+'" onchange="loadImage('+col+')"></div></td>';
		template+='<td align="center" style=" padding: 10px;"><img style=" cursor: pointer;" onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
	tmp='<tr id="row'+col+'" style="background: #fff;">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);
	if($("#identity").val()!='') {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
	<?php }?>
	title=1;
}
var url_make = '<?php echo $this->url(array('module'=>'vehicle','controller'=>'model','action'=>'add-make')); ?>';
function addMake(){
	if(dijit.byId('frm_make').validate()){
		dojo.xhrPost({
			url:url_make,
			form: dojo.byId("frm_make"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
					    name: dijit.byId('txt_make').get('value')
				};			
				addDataToSelectbox(dijit.byId('make'), model_store, Itemmake, data);
				dijit.byId('frm_make').reset();
				dijit.byId("pop_make").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
var url_model = '<?php echo $this->url(array('module'=>'vehicle','controller'=>'model','action'=>'add-model')); ?>';
function addModel(){
	if(dijit.byId('frm_model').validate()){
		dojo.xhrPost({
			url:url_model,
			form: dojo.byId("frm_model"),
			handleAs:"json",
			load: function(data) {
				//alert(data);
				var Itemmake = {					
						id: data,
					    name: dijit.byId('txt_model').get('value')
				};			
				addDataToSelectbox(dijit.byId('model'), model_store, Itemmake, data);
				dijit.byId('frm_model').reset();
				dijit.byId("pop_model").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
var url_sub_model = '<?php echo $this->url(array('module'=>'vehicle','controller'=>'index','action'=>'add-sub-model')); ?>';
function addSubModel(){
	if(dijit.byId('frm_sub_model').validate()){
		dojo.xhrPost({
			url:url_sub_model,
			form: dojo.byId("frm_sub_model"),
			handleAs:"json",
			load: function(data) {
				//alert(data);
				var Itemmake = {					
						id: data,
					    name: dijit.byId('txt_submodel').get('value')
				};			
				addDataToSelectbox(dijit.byId('submodel'), model_store, Itemmake, data);
				dijit.byId('frm_sub_model').reset();
				dijit.byId("pop_submodel").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
</script>