<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$request=Zend_Controller_Front::getInstance()->getRequest();
echo $this->headTitle($tr->translate("VEHICLE"));
 $status = $request->getParam('search_status');
 if(empty($status)) $status=-1;
 $make=$request->getParam('make');
 $model=$request->getParam('model');
 $submodel=$request->getParam('submodel');
?>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.store.Memory");
dojo.require("dojo.data.ObjectStore");

var make_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->all_make));?> );
dojo.ready(function(){
new dijit.form.FilteringSelect({
    store: make_store,
    autoComplete: true,                        
   // required: true,
    id: "make",
    name: "make",    
    placeHolder:"Selected Make",       
    class: 'fullside',   
    value:'<?php echo $make; ?>',       
    onChange: function() {  
    		make_id=dijit.byId('make').get('value');
    		//alert(make_id);
    		getallModel(make_id);
    }
}, "make");
//model controll
	new dijit.form.FilteringSelect({
	   // store: make_store,
	    autoComplete: true,                        
	    //required: true,
	    id: "model",
	    name: "model",  
	    placeHolder:"Selected Model",
	    value:'<?php echo $model; ?>',         
	    class: 'fullside',            
	    onChange: function() {  
	    	      model_id=dijit.byId('model').get('value');
	    	      //alert(model_id);
		    	   getallSubModel(model_id);
		    	   dijit.byId('submodel').attr('value','');
	    }
	}, "model");
	getallModel('<?php echo $make; ?>');
	
//submodel controll
	new dijit.form.FilteringSelect({
	   // store: make_store,
	    autoComplete: true,                        
	    //required: true,
	    id: "submodel",
	    name: "submodel",     
	    placeHolder:"Selected Submodel",      
	    class: 'fullside',            
	    onChange: function() {  
	    }
	}, "submodel");
	}); 
var model_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_getmake = '<?php echo $this->url(array('module'=>'vehicle','controller'=>'submodel','action'=>'get-model')); ?>';
function getallModel(make_id){
	if(make_id==''){
	      return false;
		}
		dojo.xhrPost({
			url:url_getmake,
			content:{
				'make_id':make_id
				},
			handleAs:"json",
			load: function(data) {
				model_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('model').set('store',model_store);   
			    dijit.byId('model').attr('value','<?php echo $model; ?>');
			},
			error: function(err) {
				alert(err);
			}
		});
}
var submodel_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_getsubmodel = '<?php echo $this->url(array('module'=>'vehicle','controller'=>'index','action'=>'get-sub-model')); ?>';
function getallSubModel(model_id){
	if(model_id==''){
	      return false;
		}
		dojo.xhrPost({
			url:url_getsubmodel,
			content:{
				'model_id':model_id
				},
			handleAs:"json",
			load: function(data) {
				//alert(data);
				submodel_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('submodel').set('store',submodel_store);  
			    dijit.byId('submodel').attr('value','<?php echo $submodel; ?>'); 
			},
			error: function(err) {
				alert(err);
			}
		});
}
</script>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'vehicle','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table>
	  <tr> 
		   <td><input dojoType="dijit.form.TextBox" class="fullside" id="adv_search" name="adv_search" value="<?php echo $request->getParam('adv_search');?>" placeholder="<?php echo $this->translate("Search");?>" type="text" ></td>
		   <td><input id="make" /></td>
		   <td><input id="model" /></td>		
		   <td><input id="submodel" /></td>
		   <td>
		        <select name="search_status" id="search_status" dojoType="dijit.form.FilteringSelect" class="fullside">
		                <option value="-1" <?php if($status==-1){ echo"selected='selected'";} ?>>Status all</option>
					    <option value="1" <?php if($status==1){ echo"selected='selected'";} ?> >Active</option>
					    <option value="0"  <?php if($status==0){ echo"selected='selected'";} ?>>Deactive</option>
				</select>
		   </td>
		   <td> <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   	  </tr>
   </table>
   <?php echo $this->list;?>
</form>
