<title>Edit Season</title>
<form id='add_season'  action="<?php echo $this->url(array('module'=>'other','controller'=>'season','action'=>'edit')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table  width="100%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend ><strong>Edit Season</strong></legend>
					<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
							<td>Season Title<input dojoType="dijit.form.TextBox" required="true" type="hidden" class="fullside" id="id" name="id" value="<?php echo $this->row['id'];?>" ></td>
							<td><input dojoType="dijit.form.ValidationTextBox" required="true" type="text" value="<?php echo $this->row['season_title']; ?>" class="fullside" id="season_title" name="season_title"></td>
							<td>In-/Decrease Price(%)</td>
							<td><input dojoType="dijit.form.NumberTextBox" class="fullside" required="true" type="text" name="value" id="value" value="<?php echo $this->row['value']; ?>" /></td>
							<td>Season Type</td>
							<td><select name="season_type" id="season_type" dojoType="dijit.form.FilteringSelect" class="fullside">
								    <option value="1" <?php if($this->row['season_type']==1){echo'selected="selected"';}?>>Hight Season</option>
								    <option value="2" <?php if($this->row['season_type']==2){echo'selected="selected"';}?>>Low Season</option>
								</select></td>
						</tr>
						<tr>
							<td>Start Date</td>
							<td><input dojoType="dijit.form.DateTextBox" required="true" type="text" class="fullside" id="start_date" name="start_date" value="<?php echo $this->row['start_date'];?>" ></td>
							<td>End Date</td>
							<td><input dojoType="dijit.form.DateTextBox" class="fullside"  required="true" type="text" name="end_date" id="end_date" value="<?php echo $this->row['end_date'];?>" /></td>
							<td>Photo Name</td>
							<td><input type="file" name="photo" /><img src="<?php echo $this->baseUrl()."/images/".$this->row['photo_name'];?>" style="max-width: 70px;" /> <input type="hidden" name="oldphoto" value="<?php echo$this->row['photo_name']; ?>"/></td>
						</tr>
						<tr>
							<td>Note</td>
							<td colspan="3"><textarea name="note" style="width:100%; height:70px;"><?php echo$this->row['note']; ?></textarea></td>
							<td valign="top">Status</td>
							<td  valign="top"><select name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside">
								    <option value="1" <?php if($this->row['status']==1){echo'selected="selected"';}?> >Active</option>
								    <option value="0" <?php if($this->row['status']==0){echo'selected="selected"';}?> >Deactive</option>
								</select></td>
						</tr>
						<tr>
							<td colspan="6" align="center">
							<input type="reset" label="Clear" dojoType="dijit.form.Button" 
								 iconClass="dijitIconClear" /> 
							<input type="submit" value="SAVE_NEW" label="Edit" id="save_new" dojoType="dijit.form.Button" name="save_new"
								 iconClass="dijitEditorIcon dijitEditorIconSave"/> 
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<script>
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
</script>