<?php 
	$rs = $this->rs;
	$o_sex="";
	if($rs["o_sex"]==1){
		$o_sex ="Male";
	}else{$o_sex ="Female";}
	
	$sex="";
	if($rs["sex"]==1){
		$sex ="Male";
	}else{$sex ="Female";}
	
	if($rs["import_tax"]==1){
		$import_tax = "Yes";
	}else {$import_tax="No";}
	
	if($rs["annual_road_tax"]==1){
		$annual_road_tax = "Yes";
	}else {$annual_road_tax="No";}
	
	if($rs["vehicle_sertificate"]==1){
		$vehicle_sertificate = "Yes";
	}else {$vehicle_sertificate="No";}
	
	if($rs["vehicle_id_card"]==1){
		$vehicle_id_card = "Yes";
	}else {$vehicle_id_card="No";}
	
	$barcode = $rs["ag_code"];
	$url_barcode = $this->url(array("module"=>"agreement","controller"=>"carsale","action"=>"generate-barcode","product_code"=>$barcode),null,true);
	
	$url_invoice = $this->url(array("module"=>"agreement","controller"=>"carsale","action"=>"invoice","id"=>$rs["id"]),null,true);
?>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<style>
#footer{display: none;}
table{
	font-family: 'Khmer OS Siemreap';

}
 .padd tr td{ 
	font-family: 'Khmer OS Siemreap';

 }
 
</style>	

<script type="text/javascript">
function doPrint() {
	//getLabel();
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function hideleft(){
	(dojo.style("leftmenu","display") == "none") ? 'show':'hide'();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=794, height=700, left=0, top=0"; 
  var content_vlue = document.getElementById("print").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:12px !important; margin:0px; font-family:arial;"><style>table th {font-size:12px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
</script>
<iframe name="print_frame" width="0" height="0" frameborder="0" src=about:blank></iframe>
<table width="50%">
	<tr>
	<td valign="top">
		<div class="menureport">
			<ul>
				<li class="preview"><a title="Preview" href="#" onclick="preview();"></a></li>
				<li class="print"><a href="#" title="Print" onclick="doPrint();" ></a></li>
				<li class="excel"><a href="#"  title="Export"  onclick="exportExcel();"></a></li>
			</ul>
		</div>
		<div style="clear:both;"></div>
   	</td>
   	<td>
			<a href="<?php echo $url_invoice;?>" ><button iconClass="dijitEditorIcon dijitEditorIconSave" dojoType="dijit.form.Button">Make Invoice</button></a>
	</td>
   	</tr>
</table>

<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;height: 26cm;width:21cm;">
		<div id="divPrint" style="padding: 0 !important;margin: 0 auto !important;">
		<style>
#footer{display: none;}
table{
	font-family: 'Khmer OS Siemreap';
	font-size: 12px;
}
 .padd tr td{ 
	font-family: 'Khmer OS Siemreap';
	
 }
 .padd tr{ 
	
 }
</style>
		<img style="margin: 0;padding:0;width:100%" src="<?php echo $this->baseUrl();?>/images/Lyna_garage_invoice.jpg"/>
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 0 1cm; ">
							<tr>
								<td style="color:#04AE18;"><img style="" src="<?php echo $url_barcode;?>"/></td>
								<td></td>
								<td style="color:#04AE18;" align="right"><strong style=" font:18px bold, Courier New;">BILL OF BUY & SALE</strong></td>
							</tr>
							
							<tr>
								<td colspan="3" align="left"><strong style="color:#04AE18; font:18px bold, Courier New;">VENDOR'S INFORMATION</strong></td>
							</tr>
							<tr>
								<td colspan="3">
									<div style="border: solid 1px #000;">
										<table class="padd" width="100%" align="center" style="white-space:nowrap; border-collapse: collapse; font-size:14px">
											<tr>
												<td width="10%">&nbsp;Name :</td>
												<td width="40%"style="border-bottom: 1px solid #000;">&nbsp;<strong><?php echo $rs["o_f_name"]." ".$rs["o_l_name"]?></strong></td>
												<td width="5%"style="border-bottom: 1px solid #fff;">&nbsp;Sex: </td>
												<td width="20%"style="border-bottom: 1px solid #000;">&nbsp;<strong><?php echo $o_sex?></strong></td>
												<td width="5%"style="border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;Age:</td>
												<td width="10%"><strong>49 Yrs</strong></td>
											</tr>
											<tr>
												<td style="border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;Current Occupation:</td>
												<td colspan="5" style="border-bottom: 1px solid #000;">&nbsp;<strong>Project Coordinator<?php echo $rs["o_occupation"]?></strong></td>
											</tr>
											<tr>
												<td style="border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;Organization:</td>
												<td colspan="5" style="border-bottom: 1px solid #000;">&nbsp;<strong><?php echo $rs["o_company_name"]?></strong></td>
											</tr>
											<tr>
												<td style="border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;Current Address:</td>
												<td colspan="5" style="border-bottom: 1px solid #000;">&nbsp;<strong><?php echo $rs["o_addr1"];?></strong></td>
											</tr>
											<tr>
												<td style="border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;Passport | ID No.:</td>
												<td style="border-bottom: 1px solid #000;">&nbsp;<strong><?php echo $rs["o_passport"]?></strong></td>
												<td style="border-left:1px solid #fff; border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;Nationality:</td>
												<td colspan="3" style="border-bottom: 1px solid #000;"><strong><?php echo $rs["o_national"]?></strong></td>
											</tr>
											<tr>
												<td style="border-right: solid 1px #fff;">&nbsp;Cell Phone No.:</td>
												<td>&nbsp;<strong><?php echo $rs["o_phone"]?></strong></td>
												<td style="border-left: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;Email:</td>
												<td colspan="3">&nbsp;<strong><?php echo $rs["o_email"]?></strong></td>
											</tr>
										</table>
									</div>	
								</td>
							</tr>
							<tr>
								<td colspan="3" align="left"><strong style="color:#04AE18; font:18px bold, Courier New;">VEHICLE'S INFORMATION</strong></td>
							</tr>
							<tr>
								<td colspan="3">
									<div style="border: solid 1px #000;">
										<table class="padd" width="100%" align="center" style=" white-space:nowrap; border-collapse: collapse; font-size:14px !important;">
											<tr>
												<td width="25%">&nbsp;ឆ្នាំផលិត Year:</td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;<?php echo $rs["year"]?></td>
												<td width="25%">&nbsp;លេខតួ Frame No.: </td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;<?php echo $rs["frame_no"]?></td>
											</tr>
											<tr>
												<td width="25%">&nbsp;ម៉ាក Make:</td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;<?php echo $rs["make"]?></td>
												<td width="25%">&nbsp;សាក់ស៊ី Chassis No.: </td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;<?php echo $rs["chassis_no"]?></td>
											</tr>
											<tr>
												<td width="25%">&nbsp;ម៉ូដែល Model:</td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;<?php echo $rs["model"]?></td>
												<td width="25%">&nbsp;លេខម៉ាស៊ីន Engine No.: </td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;<?php echo $rs["engine_number"]?></td>
											</tr>
											<tr>
												<td width="25%">&nbsp;ម៉ូដែលបន្ទាប់ Sub-model:</td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;<?php echo $rs["sub_model"]?></td>
												<td width="25%">&nbsp;ចំនួនភ្លៅ No Of Axles: </td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;<?php echo $rs["of_axlex"]?></td>
											</tr>
											<tr>
												<td width="25%">&nbsp;ប្រភេទ Type:</td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;<?php echo $rs["car_type"]?></td>
												<td width="25%">&nbsp;ចំនួនស៊ីឡាំង No. of Cylinders: </td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;<?php echo $rs["of_cylinder"]?></td>
											</tr>
											<tr>
												<td width="25%">&nbsp;ពណ៌ Color:</td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;<?php echo $rs["color"]?></td>
												<td width="25%">&nbsp;ទំហំស៊ីឡាំង Cylinder Size: </td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;<?php echo $rs["cylinders_dip"]?></td>
											</tr>
											<tr>
												<td width="25%">&nbsp;កម្លាំង Horse Power:</td>
												<td width="25%" colspan="2">&nbsp;<?php echo $rs["hors_power"]?></td>
												<td width="25%">&nbsp;លាកលេខ Plaque No.: </td>
												<td width="25%">&nbsp;<?php echo $rs["licence_plate"]?></td>
											</tr>
										</table>
									</div>
								</td>
							</tr>
							<tr>
								<td colspan="3" align="left"><strong style="color:#04AE18; font:18px bold, Courier New;">CUSTOMER'S INFORMATION</strong></td>
							</tr>
							<tr>
								<td colspan="3">
									<div style="border: solid 1px #000;">
										<table class="padd" width="100%" align="center" style=" white-space:nowrap; border-collapse: collapse;">
											<tr>
												<td width="10%">&nbsp;Name :</td>
												<td width="40%"style="border-bottom: 1px solid #000;">&nbsp;<strong><?php echo $rs["first_name"]." ".$rs["last_name"]?></strong></td>
												<td width="5%"style="border-bottom: 1px solid #fff;">&nbsp;Sex: </td>
												<td width="20%"style="border-bottom: 1px solid #000;">&nbsp;<strong><?php echo $sex?></strong></td>
												<td width="5%"style="border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;Age:</td>
												<td width="10%"><strong>49 Yrs</strong></td>
											</tr>
											<tr>
												<td style="border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;Current Occupation:</td>
												<td colspan="5" style="border-bottom: 1px solid #000;">&nbsp;<strong><?php echo $rs["occupation"]?></strong></td>
											</tr>
											<tr>
												<td style="border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;Organization:</td>
												<td colspan="5" style="border-bottom: 1px solid #000;">&nbsp;<strong><?php echo $rs["company_name"]?></strong></td>
											</tr>
											<tr>
												<td style="border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;Current Address:</td>
												<td colspan="5" style="border-bottom: 1px solid #000;">&nbsp;<strong><?php echo $rs["address1"]?></strong></td>
											</tr>
											<tr>
												<td style="border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;Passport | ID No.:</td>
												<td style="border-bottom: 1px solid #000;">&nbsp;<strong><?php echo $rs["passport_name"]?></strong></td>
												<td style="border-left:1px solid #fff; border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;Nationality:</td>
												<td colspan="3" style="border-bottom: 1px solid #000;"><strong><?php echo $rs["nationality"]?></strong></td>
											</tr>
											<tr>
												<td style="border-right: solid 1px #fff;">&nbsp;Cell Phone No.:</td>
												<td>&nbsp;<strong><?php echo $rs["phone"]?></strong></td>
												<td style="border-left: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;Email:</td>
												<td colspan="3">&nbsp;<strong>&nbsp;<?php echo $rs["email"]?></strong></td>
											</tr>
										</table>
									</div>	
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<p style="font-size:12px; line-height: 20px"><span style=" font-size:12px; font-weight: 800;">Declaration: </span>I strongly declared that the above-mentioned vehicle is really my belongings, in the contrary, if any one claims that the above-mentioned vehicle belongs to him/her I dear to face the law or court.</p>
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<p style="font-size:12px;line-height: 20px"><span style=" font-size:12px; font-weight: 800;">Description: </span>This vehicle has all the complete documents, such as: 1. Imported tax paid <span style="color:#F44336;">[<?php echo $import_tax?>]</span>, 2. Annual Road Tax <span style="color:#F44336;">[<?php echo $annual_road_tax?>]</span>, 3. Certificate Of Motor Vehicle Technical Inspection <span style="color:#F44336;">[<?php echo $vehicle_sertificate?>]</span>, and 4. ID Card (Registration Card) of the vehicle <span style="color:#F44336;">[<?php echo $vehicle_id_card?>]</span>. The car is sold as-is and where-is, no any breakdown warranty!</p>
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<table class="padd" width="100%"  align="center" style="white-space:nowrap; border-collapse: collapse;">
										<tr align="center">
											<td width="25%">Buyer</td>
											<td width="25%">Buyer's Witness</td>
											<td width="25%">Seller's Witness</td>
											<td width="25%" style="line-height: 18px;">September 30, 2015<br />Name of Vendor</td>
										</tr>
										
										<tr align="center">
											<td colspan="4">&nbsp;</td>
										</tr>
										<tr align="center">
											<td colspan="4">&nbsp;</td>
										</tr>
										<tr align="center">
											<td width="25%"><h4><?php echo $rs["first_name"]." ".$rs["last_name"]?></h4></td>
											<td width="25%"><h4><?php echo $rs["buyer_witness"]?></h4></td>
											<td width="25%"><h4><?php echo $rs["seller_witness"] ?></h4></td>
											<td width="25%"><h4><?php echo $rs["o_f_name"]." ".$rs["o_l_name"]?></h4></td>
										</tr>
									</table>
								</td>
							</tr>
					</table>
	</div>	
</div>

