<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.js"></script>
<link href="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.css" rel="stylesheet">
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Service'));
?>	
<?php  
    $holiday= $this->frm_holiday;
    $row_ser= $this->row_service;
    $img = $this->baseUrl()."/images/".$row_ser['photo'];
?>
<form  id='add_techer' action="<?php echo $this->url(array('module'=>'driverguide','controller'=>'serviceprice','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post"
 enctype="multipart/form-data">
 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
 <style>
       .image img{widtd: 100px;
              height: 100px;
             }
</style>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
require(["dojo/parser", "dijit/Editor"]);
</script>
<table width="100%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend align="center" ><strong><?php echo $tr->translate("Edit Service Rental Price");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("Servie Title")?><input type="hidden" name="id" id="id" value="<?php echo $this->row_service['id']?>"/></td>
							<td><input dojoType="dijit.form.ValidationTextBox" class="fullside" id="serice_title" name="serice_title" value="<?php echo $this->row_service['service_title']?>" type="text" required="required"></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Price")?></td>
							<td><input dojoType="dijit.form.NumberTextBox" class="fullside" id="price" name="price" value="<?php echo $this->row_service['price']?>" type="text"></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Description")?></td>
							<td><textarea class="ckeditor" dojoType="dijit.form.SimpleTextarea"  class="fullside" style="min-height:80px;" id="description" name="description"><?php echo $this->row_service['description']?></textarea></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Photo");?></td>
							<td><input type="file" name="photo" id="photo" value=""   class="fullside"/><?php echo '<img width="80px" src="'.$img.'"/>';?><input type="hidden" name="oldphoto" id="oldphoto" value="<?php echo $this->row_service['photo'];?>"  />
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Photo1")?></td>
							<td><input type="file" name="photo1" id="photo1"  class="fullside"/><img width="80px" src="<?php echo $this->baseUrl()."/images/".$row_ser['photo1'];?>" /><input type="hidden" name="oldphoto1" id="oldphoto1" value="<?php echo $this->row_service['photo1'];?>"  /></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Photo2")?></td>
							<td><input type="file" name="photo2" id="photo2"  class="fullside"/><img width="80px" src="<?php echo $this->baseUrl()."/images/".$row_ser['photo2'];?>" /><input type="hidden" name="oldphoto2" id="oldphoto2" value="<?php echo $this->row_service['photo2'];?>"  /></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true" missingMessage="Invalid Module!" class="fullside">
								    <option value="1">Active</option>
								    <option value="0">Deactive</option>
								</select>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
									<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
