<title>Edit Vehicle Rental Price</title>
<style>
.fixed_lable{ 
	min-width: 80px; float: left;margin: 3px 5px;
}
.fixed_value{ 
	min-width: 160px; background:#fff; float: left;margin: 1px 5px;
	padding:0px 3px;border:1px solid #ccc; min-height: 30px;
}
</style>
<form id="vehicleprice" action="<?php echo $this->url(array('module'=>'driverguide','controller'=>'vehicleprice','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				 if(dijit.byId('record_row').get('value')==''){
                    alert('Can not submit without record !');
                    return false;
                 }
				return true;
			} else {
				return false;
			}
	</script>
	<table cellspacing="10" style="margin: 0 auto; width: 100%">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong>Vehicle Rental Price</strong></legend>
					<table  width="100%" >
						<tr>
							<td align="center" valign="top">
								<table style="margin: 0 auto; width:100%;" cellspacing="10">
									<tr>
										<td>Vehicle Ref</td>
										<td><select name="reference_id" id="reference_id" dojoType="dijit.form.FilteringSelect" required="true"  class="fullside" onChange="getAllVehicle(1);">
											<?php if(!empty($this->vehicle))foreach ($this->vehicle as $rows){?>
												<option <?php if($this->vehicle_id==$rows['id']){echo "selected='selected'";}?> value="<?php echo $rows['id'];?>"><?php echo $rows['reffer'];?></option>
											<?php }?>
										</select></td>
										<td>Frame No</td>
										<td><select name="frame_id" id="frame_id" dojoType="dijit.form.FilteringSelect" required="true"  class="fullside" onChange="getAllVehicle(2);">
											<?php if(!empty($this->vehicle))foreach ($this->vehicle as $rows){?>
												<option <?php if($this->vehicle_id==$rows['id']){echo'selected="selected"';}?> value="<?php echo $rows['id'];?>"><?php echo $rows['frame_no'];?></option>
											<?php }?>
										</select></td>
									</tr>
									<tr>
										<td colspan="4" height="60px" style="border:1px solid #ccc;" valign="top">
										<table style="white-space: nowrap;">
													<tr>
														<td><label class="fixed_lable">Vehicle Ref</label></td>
														<td><label class="fixed_value" id='lbl_refer'></label></td>
														<td><label class="fixed_lable">Frame No</label></td>
														<td><label class="fixed_value" id='lbl_frame'></label></td>
														<td><label class="fixed_lable">Licence Plate</label></td>
														<td><label class="fixed_value" id='lbl_licence'></label></td>
													</tr>
													<tr>
														<td><label class="fixed_lable">Make</label></td>
														<td> <label class="fixed_value" id='lbl_make'></label></td>
														<td><label class="fixed_lable">Model</label></td>
														<td><label class="fixed_value" id='lbl_model'></label></td>
														<td><label class="fixed_lable">Sub Model</label></td>
														<td><label class="fixed_value" id='lbl_submodel'></label></td>
													</tr>
													<tr>
														<td><label class="fixed_lable">Year</label></td>
														<td><label class="fixed_value" id='lbl_year'></label></td>
														<td><label class="fixed_lable">Seat</label></td>
														<td><label class="fixed_value" id='lbl_seat'></label></td>
														<td></td>
														<td></td>
													</tr>
												</table>
										</td>
									</tr>
									<tr>
										<td>Tax</td>
										<td><select name="tax" id="tax" dojoType="dijit.form.FilteringSelect" class="fullside"> 
											<?php if(!empty($this->rs_tax))foreach ($this->rs_tax as $key=> $row){?>
												<option value="<?php echo $row['id'];?>"><?php echo $row['title'];?></option>
											<?php }?>
											</select>
										</td>
										<td>Status</td>
										<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true"  class="fullside">
											    <option value="1" label="Active">Active</option>
											    <option value="0" label="Deactive">Deactive</option>
											</select>
										</td>	
									</tr>
									<tr>
										<td colspan="6" align="center">
											<div style="clear: both;"></div>
											<input type="hidden" dojoType="dijit.form.TextBox" id="record_row" name="record_row" />
											<div  id="store_record"></div>
											<input iconClass="dijitIconClear" type="button" onClick="addPockage();" label="Add Record" dojoType="dijit.form.Button"/>
										</td>
									</tr>
									<tr>
										<td colspan="6" align="center">
											<input type="reset"  label="Clear"dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
											<input type="submit" value="save_close" name="save_new" label="Edit" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>

<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.html");
	dojo.require("dijit.form.NumberTextBox");
require(["dojo/ready"], function(ready){
	ready(function(){
		innitialize();
		//getAllVehicle(1);
	});
});
province_option = '<?php echo $this->package_option;?>';
function innitialize(){
	dojo.query("#store_record").append('');
	tmp='<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr style="background:#eee; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#store_record").append(tmp);
	thead='<th>Delete</th>';
	thead+='<th>Amount Day</th>';
	thead+='<th>Price</th>';
	thead+='<th>Extra Day Price</th>';
	thead+='<th>Note</th>';
	fund_title=1;
	dojo.query("#head_title").append(thead);	
	dijit.byId('record_row').attr('value','');
	
	<?php if(!empty($this->rows)) {
	foreach($this->rows AS $i=>$rs){?>
	r++;
	tmp='<tr style="border:1px solid #ccc;" id="row_guide'+r+'">'
	tmp+="</tr>";
		dojo.query("#t_amountmoneytype").append(tmp);
		temp='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		temp+='<td><select style="width:250px;"  id="package_id'+r+'" name="package_id'+r+'" dojoType="dijit.form.FilteringSelect" onchange="getLocation('+r+')">'+province_option+'</select></td>';
		temp+='<td><input style="width:250px;" dojoType="dijit.form.NumberTextBox" class="fullside" required="true" name="price_'+r+'" id="price_'+r+'" value="" type="text"></td>';
		temp+='<td><input style="width:250px;" dojoType="dijit.form.NumberTextBox" class="fullside" required="true" name="extracharge_'+r+'" id="extracharge_'+r+'" value="" type="text"></td>';
		temp+='<td><input style="width:250px;" dojoType="dijit.form.TextBox" class="fullside" name="note_'+r+'" id="note_'+r+'" value="" type="text"></td>';
		
		dojo.html.set(dojo.byId("row_guide"+r),temp, {
	    parseContent: true,
	     
	});
	if(dijit.byId("record_row").get('value')!="") {
		var ids = dijit.byId("record_row").value;
		dijit.byId("record_row").attr('value',ids+','+r);
	} else { dijit.byId("record_row").attr('value',r);}

	dijit.byId('package_id'+r).attr('value',<?php echo $rs['packageday_id'];?>);
	dijit.byId('price_'+r).attr('value',<?php echo $rs['price'];?>);
	dijit.byId('extracharge_'+r).attr('value',<?php echo $rs['extraprice'];?>);
	dijit.byId('note_'+r).attr('value','<?php echo $rs['note'];?>');
	 <?php  if($i+1==count($this->rows)){ ?>
		dijit.byId('tax').attr('value','<?php echo $rs['vat_value'];?>');
		dijit.byId('status').attr('value','<?php echo $rs['status'];?>');
		dijit.byId('reference_id').attr('value','<?php echo $rs['vehicle_id'];?>');
		getAllVehicle(1)
		dijit.byId('reference_id').set('readOnly',true);
		dijit.byId('frame_id').set('readOnly',true);
	<?php }?>
<?php }}?>
}

function addNewRecord(){
	dojo.query("#store_record").append('');
	tmp='<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr style="background:#eee; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#store_record").append(tmp);
	thead='<th>delete</th>';
	thead+='<th>Amount Day</th>';
	thead+='<th>Price</th>';
	thead+='<th>Extra Day Price</th>';
	thead+='<th>Note</th>';
	fund_title=1;
	dojo.query("#head_title").append(thead);	
	dijit.byId('record_row').attr('value','');
	addPockage();
}
r=0;
function addPockage(){
	r++;
	tmp='<tr style="border:1px solid #ccc;" id="row_guide'+r+'">'
	tmp+="</tr>";
		dojo.query("#t_amountmoneytype").append(tmp);
		
	temp='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="/lyna/trunk/public/images/Delete_16.png"></td>';
	temp+='<td><select style="width:250px;"  id="package_id'+r+'" name="package_id'+r+'" dojoType="dijit.form.FilteringSelect" onchange="getLocation('+r+')">'+province_option+'</select></td>';
	temp+='<td><input style="width:250px;" dojoType="dijit.form.NumberTextBox" class="fullside" required="true" name="price_'+r+'" id="price_'+r+'" value="" type="text"></td>';
	temp+='<td><input style="width:250px;" dojoType="dijit.form.NumberTextBox" class="fullside" required="true" name="extracharge_'+r+'" id="extracharge_'+r+'" value="" type="text"></td>';
	temp+='<td><input style="width:250px;" dojoType="dijit.form.TextBox" class="fullside" name="note_'+r+'" id="note_'+r+'" value="" type="text"></td>';
	
	dojo.html.set(dojo.byId("row_guide"+r),temp, {
	    parseContent: true,
	});
	if(dijit.byId("record_row").get('value')!="") {
		var ids = dijit.byId("record_row").value;
		dijit.byId("record_row").attr('value',ids+','+r);
	} else { dijit.byId("record_row").attr('value',r);}
}
function deleteRecord(index){
	var ids =dijit.byId('record_row').value;
	if(ids.length=='' || ids.length==null){
		dijit.byId('record_row').attr('value','');
		dojo.query("#row_guide"+ids).remove();
	}else{
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		dijit.byId('record_row').attr('value',strings);
		dojo.query("#row_guide"+index).remove();
	}
}
var url_getmake = '<?php echo $this->url(array('module'=>'driverguide','controller'=>'vehicleprice','action'=>'get-vehicle')); ?>';
function getAllVehicle(type){
	if(type==1){
		vehicle_id=dijit.byId("reference_id").get('value');
	}else{
		vehicle_id=dijit.byId("frame_id").get('value');
	}
	if(vehicle_id==''){ return false;}
	dojo.byId('lbl_refer').innerHTML ='';
	dojo.byId('lbl_frame').innerHTML ='';
	dojo.byId('lbl_licence').innerHTML ='';
	dojo.byId('lbl_make').innerHTML ='';
	dojo.byId('lbl_model').innerHTML ='';
	dojo.byId('lbl_submodel').innerHTML ='';
	dojo.byId('lbl_seat').innerHTML ='';
	dojo.byId('lbl_year').innerHTML ='';
	dojo.byId('lbl_seat').innerHTML ='';
	dojo.xhrPost({
				url:url_getmake,
				content:{
					'vehicle_id':vehicle_id
					},
				handleAs:"json",
				load: function(data) {
					dojo.byId('lbl_refer').innerHTML =data.reffer;
					dojo.byId('lbl_frame').innerHTML =data.frame_no;
					dojo.byId('lbl_licence').innerHTML =data.licence_plate;
					dojo.byId('lbl_make').innerHTML =data.make_id;
					dojo.byId('lbl_model').innerHTML =data.model_id;
					dojo.byId('lbl_submodel').innerHTML =data.sub_model;
					dojo.byId('lbl_seat').innerHTML =data.seat;
					dojo.byId('lbl_year').innerHTML =data.year;
					dojo.byId('lbl_seat').innerHTML =data.seat_amount;
					if(type==1){
						dijit.byId('frame_id').attr('value',vehicle_id) ;
					}else{
						dijit.byId('reference_id').attr('value',vehicle_id) ;
					}
				},
				error: function(err) {
					alert(err);
				}
			});
}
</script>