<?php 
   $tr = Application_Form_FrmLanguages::getCurrentlanguage();
   echo $this->headTitle($tr->translate("BOOKING"));
   $rows_owner= $this->rows_owner;
   $rows_cus=$this->rows_cus;
   
   $frm = $this->frm;
   $session = $this->bookinginfo;
   $day =date_diff(date_create($this->bookinginfo->pickup_date), date_create($this->bookinginfo->return_date));
   $total_day = $day->format("%a%")+1;
   $product = $this->bookinginfo->rowsguide;
   
   $is_mount = $session->is_month;
   $num_month = $session->month_num;
   if($is_mount==2){
   		$duration = $num_month." Month(s)";
   }else{
   		$duration= $total_day." Day(s)";
   }
   
$net_total_driver=0;
   if($this->bookinginfo->driver){
   	foreach($this->bookinginfo->driver As $num => $row){
   		if($is_mount==1){
   			$net_total_driver += number_format(($row['driver_price']*$row['amount_rent'])*$total_day,2);
   		}else{
   			$net_total_driver += number_format(($row['monthly_price']*$row['amount_rent'])*$num_month,2);
   		}
   	}
   }
   $net_total_other_fee = 0;
   if(!empty($session->other_fee)){ foreach ($session->other_fee as $key=>$row){
   	$net_total_other_fee+=$row["price"];
   }}
   $net_total= $net_total_driver+$net_total_other_fee;
?>
<style>
	dt{ display: none;}
	#lb_validate{ display: none;}
	table tr .totalbr{
			border: 1px solid #000;
		}
	.note{margin-top:20px;}
		.note p{line-height: 15px !important;    font-size: 12px;}
		.note p+p{margin:6px !important;    font-size: -8px;}
		.note ol{margin-top: -8px;}
		.note li{font-size: 12px;line-height: 15px;}
	table tr .text-center{text-align: center;}
</style>
<script type="text/javascript">
dojo.ready(function(){
	//dijit.byId('vehicle_ref_no').attr("placeholder", "Month");
	// $("#vehicle_ref_no").attr("placeholder", "Month");
});
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<style>
 table.date tr{height: 63px;}
 table.options-primary table td{line-height: 20px;font-size: 13px;}
</style>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
<table  width="100%" style="margin-top:-5px;">
	<tr>
		<td>
		<fieldset>
					<legend ><strong>Add Vehicle</strong></legend>
					<div id="mainTabContainer" style="max-width:1110px; height: 540px;" dojoType="dijit.layout.TabContainer" region="center"  >
						<div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="Select Date" <?php if(empty($this->bookinginfo->point_step))echo 'selected="true"';?>>
							<form action="<?php echo $this->url(array('module'=>'booking','controller'=>'guidebooking','action'=>'get-guide-available')); ?>" method="post" dojoType="dijit.form.Form" method="post">
								<div class="select-wrapper clearfix" >
                                    	<div style="background: #fff;padding: 5px 10px;border-radius: 5px; width:20%; float:left;">
                                           <div style="background: rgb(167, 24, 182) none repeat scroll 0% 0% !important;width: 19px;height: 19px;position: absolute;top: 17px !important;border-radius: 11px;"><input type="radio" checked="checked" class="control_style" name="rental_type" onChange="mothlyRetntal()" id="rental_type" value="1" style="margin: -4px 0 0 3px !important;" ></div><strong style="margin-left: 44px;">Daily Rental</strong>
                                    	</div>
                                    	<div style="background: #fff;padding: 5px 10px;border-radius: 5px;width:20%; float:left;">
                                            <div style="background: rgb(167, 24, 182) none repeat scroll 0% 0% !important;width: 19px;height: 19px;position: absolute;top: 17px !important;border-radius: 11px;"><input type="radio" class="control_style" name="rental_type" id="rental_type" onChange="mothlyRetntal()" value="2" style="margin: -4px 0 0 3px !important;" ></div><strong style="margin-left: 44px;">Monthly Rental</strong>
                                    	</div>
                                    <div style="width:20%; float:left;">
                                            <input type="text" class="fullside" readonly="readonly" name="monthly_rent" id="monthly_rent"  onKeyup="calculateDate();" style="margin-top: -4px; width:100%" dojoType="dijit.form.NumberTextBox" >
                                    </div>
                                </div>
								<table style="margin: 0 auto; width:100%; font-size:14px;white-space: nowrap;" class="date">
								    <tr>
										<td width="2%">Pickup Date:</td>
										<td width="25%"><?php echo $frm->getElement("pickup_date");?></td>
										<td width="25%" colspan="2">
											<table>
												<tr>
													<td style="width: 23%;">Pickup Time:</td>
													<td><?php echo $frm->getElement("pickup_time");?></td>
													<td>Minutes:</td>
													<td><?php echo $frm->getElement("pickup_minute");?></td>
												</tr>
											</table>
										</td>
									</tr>
									<tr>
										<td width="2%">Return Date:</td>
										<td width="25%"><?php echo $frm->getElement("return_date");?></td>
										<td width="25%" colspan="2">
											<table>
												<tr>
													<td style="width: 23%;">Return Time:</td>
													<td><?php echo $frm->getElement("return_time");?></td>
													<td>Minutes:</td>
													<td><?php echo $frm->getElement("return_minute");?></td>
												</tr>
											</table>
										</td>
									</tr>
									<tr>
										<td></td>
										<td></td>
										<td></td>
										<td style="text-align: right;"><input type="submit" iconclass="dijitIconSearch" dojoType="dijit.form.Button" value="Find Vehicle Now" label="Find Vehicle Now"></td>
									</tr>
								</table>
							</form>
						</div>
						<div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="Select Guide/Driver" <?php if($this->bookinginfo->point_step ==1 )echo 'selected="true"'?> >
							<?php if($this->bookinginfo->step1 ==1 ){?>
							<form method="post" action="<?php echo $this->url(array('module'=>'booking','controller'=>"guidebooking",'action'=>'get-guide-selected'),null,true); ?>">
								<div style="z-index: 100000000;height: 50px;">
				                        <div style="float: right;" >
				                        	<input type="submit" dojoType="dijit.form.Button" value="Continue" label="Continue">
				                        </div>
			                    </div>
								<div id="drive_select" style="display:block" >
									<?php if(!empty($session->rowsguide)){ $i=0; foreach ($session->rowsguide as $rs){ $i++;?>
									<div style="margin-top:30px;position:relative;margin-bottom: 10px; padding:10px; border-radius:10px;border: 1px solid #E5E5E5;border-radius: 11px / 13px;background-color: #FFF;box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.13);">
										<table class="options-primary">
											<tr>
												<td style="width: 20%"><img style="width:178px;" src="<?php echo $this->baseUrl();?>/images/driverphoto/<?php echo $rs["photo"];?>" class="preview" alt="preview"></td>
												<td style="width: 40%;">
													<table>
														<tr>
															<td colspan="2" style="color:red; font-size:16px;"><h4><?php echo $rs["name"];?></h4></td>
														</tr>
														<tr>
															<td>Driver ID:</td>
															<td><?php echo $rs["driver_id"];?></td>
														</tr>
														<tr>
															<td>Nationality:</td>
															<td><?php echo $rs["nationality"];?></td>
														</tr>
														<tr>
															<td>Experience:</td>
															<td><?php echo $rs["experience_desc"];?></td>
														</tr>
														<tr>
															<td>Language:</td>
															<td><?php echo $rs["lang_note"];?></td>
														</tr>
														<tr>
															<td>&nbsp;</td>
															<td>&nbsp;</td>
														</tr>
														<tr>
															<td>&nbsp;</td>
															<td>&nbsp;</td>
														</tr>
														<tr>
															<td>&nbsp;</td>
															<td>&nbsp;</td>
														</tr>
														<tr>
															<td>&nbsp;</td>
															<td colspan=""><a href="<?php echo $this->baseUrl();?>/index/vehicle/id/<?php echo $rs["id"];?>" target="_blank"><div style="background: rgb(177, 35, 175) none repeat scroll 0% 0%;padding: 6px;border-radius: 5px;color: White;width: 71px;"> View Details </div></a></td>
														</tr>
														
														
													</table>
												</td>
												<td>
													<table>
														<tr>
															<td>
															</td>
					                                        <td colspan="" style="text-align: right">
					                                        	<input type="hidden" name="driverid_<?php echo $i ?>" value="<?php echo $rs["id"] ?>" />
																<span style="margin-top: -28px ! important; position: absolute; right: 47px; top: 46px;">Tick the Box</span>
																<input type="checkbox" name="driver_<?php echo $i?>" class="checkbox input-checkbox" id="driver_<?php echo $i;?>" onClick="addDriver(<?php echo $i?>)" value="<?php echo $rs["id"];?>" style="rigth: 0 !important;"/>
					                                        </td>
					                                        
					                                    </tr>
														<tr>
					                                        <td>City Nomal Price:</td>
					                                        <td>$<?php echo $rs["c_normalprice"]?>/day</td>
					                                    </tr>
					                                    <tr>
					                                        <td>City Holiday Price:</td>
					                                        <td>$<?php echo $rs["c_holidayprice"]?>/day</td>
					                                    </tr>
					                                    <tr>
					                                        <td>City Weeken Price:</td>
					                                        <td>$<?php echo $rs["c_weekendprice"]?>/day</td>
					                                    </tr>
					                                    <tr>
					                                        <td>City OT Price:</td>
					                                        <td>$<?php echo $rs["c_otprice"]?>/day</td>
					                                    </tr>
					                                    <tr>
					                                        <td>Province Nomal Price:</td>
					                                        <td>$<?php echo $rs["p_normalprice"];?>/day</td>
					                                    </tr>
					                                    <tr>
					                                        <td>Province Holiday Price:</td>
					                                        <td>$<?php echo $rs["p_holidayprice"];?>/day</td>
					                                    </tr>
					                                    <tr>
					                                        <td>Province Weeken Price:</td>
					                                        <td>$<?php echo $rs["p_weekendprice"];?>/day</td>
					                                    </tr>
					                                    <tr>
					                                        <td>Province OT Price:</td>
					                                        <td>$<?php echo $rs["p_otprice"];?>/day</td>
					                                    </tr>
													</table>
												</td>
												
											</tr>
			                            </table>
			                         </div>
			                    <?php }}else echo "No Driver Available!";?>
			                    </div>
				                <input type=hidden name="identity_driver" id="identity_driver"/> 
				            </form>
				            <?php }?>
						</div>
						
						<div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="Other Fee" <?php if($this->bookinginfo->point_step ==2 )echo 'selected="true"'?> >
							<?php if($this->bookinginfo->step2 ==1 ){?>
							<form method="post" action="<?php echo $this->url(array('module'=>'booking','controller'=>"guidebooking",'action'=>'other-fee'),null,true); ?>">
								<table>
									<tr id="tr_1">
										<td><input type="checkbox" name="other_1" id="other_1" onClick="addOtherFee(1);"></td>
										<td>Other Fee 1:</td>
										<td><?php echo $frm->getElement("other_fee1"); ?></td>
										<td class="align">Note :</td>
										<td><?php echo $frm->getElement("other_fee_note1"); ?></td>
									</tr>
									
									<tr id="tr_2">
										<td><input type="checkbox" name="other_2" id="other_2" onClick="addOtherFee(2);"></td>
										<td>Other Fee 2:</td>
										<td><?php echo $frm->getElement("other_fee2"); ?></td>
										<td class="align">Note :</td>
										<td><?php echo $frm->getElement("other_fee_note2"); ?></td>
									</tr>
									
									<tr id="tr_3">
										<td><input type="checkbox" name="other_3" id="other_3" onClick="addOtherFee(3);"></td>
										<td>Other Fee 3:</td>
										<td><?php echo $frm->getElement("other_fee3"); ?></td>
										<td class="align">Note :</td>
										<td><?php echo $frm->getElement("other_fee_note3"); ?></td>
									</tr>
									
									<tr id="tr_4">
										<td><input type="checkbox" name="other_4" id="other_4" onClick="addOtherFee(4);"></td>
										<td>Other Fee 4:</td>
										<td><?php echo $frm->getElement("other_fee4"); ?></td>
										<td class="align">Note :</td>
										<td><?php echo $frm->getElement("other_fee_note4"); ?></td>
									</tr>
									
									<tr id="tr_5">
										<td><input type="checkbox" name="other_5" id="other_5" onClick="addOtherFee(5);"></td>
										<td>Other Fee 5:</td>
										<td><?php echo $frm->getElement("other_fee5"); ?></td>
										<td class="align">Note :</td>
										<td><?php echo $frm->getElement("other_fee_note5"); ?></td>
									</tr>
									
									<tr id="tr_6">
										<td><input type="checkbox" name="other_6" id="other_6" onClick="addOtherFee(6);"></td>
										<td>Other Fee 6:</td>
										<td><?php echo $frm->getElement("other_fee6"); ?></td>
										<td class="align">Note :</td>
										<td><?php echo $frm->getElement("other_fee_note6"); ?></td>
									</tr>
									<tr>
										<td><input type="hidden" name="identity_other_fee" id="identity_other_fee"></td>
										<td></td>
										<td></td>
										<td></td>
										<td class="align"><input type="submit" iconclass="dijitIconNew" dojoType="dijit.form.Button" value="Continue" label="Continue" ></td>
									</tr>
								</table>
								
							</form>
							<?php }?>
						</div>
						<div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="Customer Info" <?php if($this->bookinginfo->point_step ==3 )echo 'selected="true"'?> >
							<?php if($this->bookinginfo->step3 ==1 ){?>
							<form method="post" action="<?php echo $this->url(array('module'=>'booking','controller'=>"guidebooking",'action'=>'customer-info'),null,true); ?>">
							<div id="exist_customer">
								<table>
									<tr>
										<td style="width:20%">Choose Customer :</td>
										<td style="width:30%"><?php echo $frm->getElement("customer");?></td>
										<td></td>
									</tr>
								</table>
								<div id="customer_info" style="margin-top:30px;">
									
								</div>
								<div id="confirm_btn" style="display: none;margin-top:30px;"  >
									<table>
										<tr>
											<td>Filght No.:</td>
											<td><?php echo $frm->getElement("fly_no");?></td>
											<td>Flight Date:</td>
											<td><?php echo $frm->getElement("fly_date");?></td>
										</tr>
										<tr>
											<td>Flight Time Arrival:</td>
											<td><?php echo $frm->getElement("fly_time");?></td>
											<td>Flight Distination:</td>
											<td><?php echo $frm->getElement("fly_destination");?></td>
										</tr>
										<tr>
											<td></td>
											<td>
<!-- 												<input type="reset" name="reset" iconclass="dijitIconDelete" dojoType="dijit.form.Button" value="Reset" label="Reset"> -->
												<input type="submit" name="" iconclass="dijitIconSearch" dojoType="dijit.form.Button" value="Confirm" label="Confirm" >
												<input id="create_acc" iconclass="dijitIconNew" dojoType="dijit.form.Button" value="Confirm" label="Create Account" onClick="signup(1);"></td>
											<td style="text-align: left"></td>
										</tr>
									</table>
								</div>
								
							</div>
							</form>
							<div id="new_customer" style="display:none;">
								<form action="" method="Post">
								<table>
									<tr>
										<td>User Name :</td>
										<td><?php echo $frm->getElement("cu_user_name");?></td>
										<td>Password</td>
										<td><?php echo $frm->getElement("cu_pass");?></td>
										<td>Email</td>
										<td><?php echo $frm->getElement("cu_email");?></td>
									</tr>
									<tr>
										<td>First Name :</td>
										<td><?php echo $frm->getElement("cu_first_name");?></td>
										<td>Last Name</td>
										<td><?php echo $frm->getElement("cu_last_name");?></td>
										<td>Gender</td>
										<td><?php echo $frm->getElement("gender");?></td>
									</tr>
									<tr>
											<td></td>
											<td></td>
											<td></td>
											<td>
												<input type="reset" name="reset" iconclass="dijitIconDelete" dojoType="dijit.form.Button" value="Reset" label="Reset">
												<input type="submit" name="confirm_cu" iconclass="dijitIconSearch" dojoType="dijit.form.Button" value="Confirm" label="Confirm" >
												<input id="choose_cu" iconclass="dijitIconSearch" dojoType="dijit.form.Button" value="Choose Customer" label="Choose Customer" onClick="signup(2);"/>
											</td>
											<td style="text-align: left"></td>
											<td style="text-align: left"></td>
										</tr>
								</table>
								</form>
							</div>
							<?php }?>
						</div>
						<div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="Booking List" <?php if($this->bookinginfo->point_step ==4 )echo 'selected="true"'?> >
							<?php if($this->bookinginfo->step4 ==1 ){?>
							<form action="<?php echo $this->url(array('module'=>'booking','controller'=>"guidebooking",'action'=>'confirm-booking'),null,true); ?>" method="post">
                            		<button type="submit" style="float: right" name="confirm_book" dojoType="dijit.form.Button" value="Cofirm Booking" label="Cofirm Booking">Confirm</button>
                            </form>
							<table id="exportExcel" style="border-collapse:collapse;font-size: 12px;" width="100%">
									<tr>
										<th>
											<table style="border-collapse:collapse;font-size: 12px; width:100% ;text-align: left; padding:5px; line-height: 14px;" cellpadding="5 ">
												<tr style="line-height: 17px;"><td colspan="4" style="border-bottom:1px solid #ccc;text-align: left;background-color:  rgb(27, 86, 227);color:rgb(254, 250, 250);"><strong>&nbsp;Booking Info</strong></td></tr>
										        <tr>
										        	<td style="width:18%">&nbsp;For :</td>
										        	<td><?php echo $this->user_name?></td>
										        	<td style="width:18%">&nbsp;Duration :</td>
										        	<td><?php echo $duration;?></td>
										        </tr>
										        <tr>
										        	<td style="width:18%">&nbsp;Pickup Date Time : </td>
										        	<td><?php echo date("d-M-Y",strtotime($this->bookinginfo->pickup_date)) ." ".$this->bookinginfo->pickup_time;?></td> 
									            	<td style="width:18%">&nbsp;Return Date Time </td>
									            	<td><?php echo date("d-M-Y",strtotime($this->bookinginfo->return_date))." ".$this->bookinginfo->return_time;?></td>
									            </tr>
									            <tr></tr>
								       	 	</table>
								        </th>
									</tr>
								    <tr >
								    </tr>
								</table>
				                	<table style="border-collapse:collapse;font-size: 12px;margin-top:10px;float: left;" width="100%">
								 <tr><td colspan="5" style="border-bottom:1px solid #ccc;text-align: left;background-color:  rgb(27, 86, 227);color:rgb(254, 250, 250);"><strong>&nbsp;Item Info</strong></td></tr>
								  <tr>
								     <th rowspan="2" width="5%" class="totalbr text-center">No</th>
								     <th rowspan="2" width="50%" class="totalbr text-center" >Items Description</th> 
								     <th rowspan="2" width="10%" class="totalbr text-center" >QTY</th> 
								     <th colspan="2" width="20%" class="totalbr text-center">Price In US$</th>
								  </tr>
								  <tr style="text-align: center">
								     <th class="totalbr text-center" width="10%">Price</th>
								     <th class="totalbr text-center" width="25%" nowrap="nowrap">Amount</th>
								  </tr>
								  <?php $refun_deposit_driver=0; if(!empty($this->bookinginfo->driver)){
								   		foreach($this->bookinginfo->driver As $num => $row){
												$refun_deposit_driver += $row["refund_deposit"];
// 												$net_total_driver += number_format(($row['driver_price']*$row['amount_rent'])*$total_day,2);
												if($is_mount==1){
													$total_price = number_format(($row['driver_price']*$row['amount_rent'])*$total_day,2);
													$price = $row['driver_price'];
												}else{
													$total_price = number_format(($row['monthly_price']*$row['amount_rent'])*$num_month,2);
													$price = $row['monthly_price'];
												}
												
												
								   ?>
									  <tr>
									  	  <td class="totalbr text-center"><?php echo $num; $j = $num; ?></td>
			                              <td class="totalbr" style="text-align: left; !important;"><?php echo $row['driver_name'];?></td>
			                              <td class="totalbr" style="text-align: center; !important;"><?php echo $row['amount_rent'];?></td>
			                              <td class="totalbr" align="right" style="padding-right: 10px">$<?php echo number_format($price,2);?></td>
			                              <td class="totalbr" align="right" style="padding-right: 10px">$<?php echo number_format($total_price,2);?></td>
									  </tr>
								  <?php }}else{if(empty($this->bookinginfo->driver)){$j=$i;}}?>
								  <?php if(!empty($session->other_fee)){ foreach ($session->other_fee as $key=>$row){ ?>
								  		 <tr>
								  		  <td class="totalbr text-center"><?php echo $j+$key; $x = $j+$key; ?></td>
			                              <td class="totalbr" style="text-align: left; !important;"><?php echo $row['item_name'];?></td>
			                              <td class="totalbr" style="text-align: center; !important;"><?php //echo $row['amount_rent'];?></td>
			                              <td class="totalbr" align="right" style="padding-right: 10px">$<?php echo number_format($row["price"],2);?></td>
			                              <td class="totalbr" align="right" style="padding-right: 10px">$<?php echo number_format($row["price"],2);?></td>
			                            </tr>
								  <?php }}else {$x=$j;}?>
								  <tr>
									  <td ></td>
									  <td></td>
									  <td class="totalbr" colspan="2">&nbsp;1. Rental Fee:</td>
									  <td style="font-weight: 800;text-align: right" class="totalbr" colspan="2">&nbsp;$<?php echo number_format($net_total,2)?> </td>
								  </tr>
								   <tr>
									  <td ></td>
									  <td></td>
									  <td style="white-space: nowrap;" class="totalbr" colspan="2">&nbsp;2. Amount Paid :</td>
									  <td style="font-weight: 800;text-align: right" class="totalbr" colspan="2">&nbsp;$<?php echo number_format($net_total,2)?> </td>
								  </tr>
								  <tr>
									  <td ></td>
									  <td></td>
									  <td class="totalbr" colspan="2">&nbsp;3. Due Amount:</td>
									  <td style="font-weight: 800; text-align: right" class="totalbr" colspan="2">&nbsp;$<?php echo number_format(0,2)?></td>
								  </tr>
							   </table>
							 <?php }?>
						</div>
						<div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="Payment" <?php if($this->bookinginfo->point_step ==5 )echo 'selected="true"'?> >
							<?php if($this->bookinginfo->step5 ==1 ){?>
							<form action="" method="post" id="payment" dojoType="dijit.form.Form">
								<script type="dojo/method" event="onSubmit">			
									if(this.validate()) {
										var pay_type = $('input[name=payment_type]:checked').val();
										var card_id = dijit.byId('card_id').get('value');
										var card_name = dijit.byId('card_name').get('value');
										var card_exp = dijit.byId('card_exp_date').get('value');
										var card_cvv = dijit.byId('secu_code').get('value');
										var wu_code = dijit.byId('wu_code').get('value');
                                        var cash_pay = dijit.byId('cash_pay').get('value');
										if(pay_type==1){
											if(card_id==""){
												alert('Card ID is required');
												dijit.byId('card_id').focus();
												return false;
											}
											if(card_name==""){
												alert('Card Name is required');
												dijit.byId('card_name').focus();
												return false;
											}
											if(card_exp==""){
												alert('Card Expiration Date is required');
												dijit.byId('card_exp_date').focus();
												return false;
											}
											if(card_cvv==""){
												alert('CVV code is required');
												dijit.byId('secu_code').focus();
												return false;
											}
										}else if(pay_type==2){
											if(wu_code=="" || wu_code=="NaN"){
												alert('MTCN Code is required');
												dijit.byId('wu_code').focus();
												return false;
											}
										}else if(pay_type==4){
											if(cash_pay=="" || cash_pay=="NaN"){
												alert('Total Pay is required');
												dijit.byId('cash_pay').focus();
												return false;
											}
										}
										return true;
									} else {
										return false;
									}
								</script>
                                	<div style="margin: 20px 20px;">
                                		<div class="col-md-4" style="float: left;margin-right: 50px;">
                                			<input id="visa_type" class="payment_type" onChange="paymentType(1);" type="radio" name="payment_type" checked="checked" value="1" style="margin-top: 11px;">
		                            		<img alt="" src="<?php echo $this->baseUrl();?>/images/visa.jpg" style="margin-left: 30px;">  
		                            	</div>
		                            	<div class="col-md-4" style="float: left;margin-right: 50px;">
		                            		<input id="ws_type" class="payment_type" onChange="paymentType(2);" type="radio" name="payment_type" value="2" style="margin-top: 11px;">
		                            		<img alt="" src="<?php echo $this->baseUrl();?>/images/western-union-small.jpg" style="margin-left: 30px;"> 
		                            	</div>
		                            	<div class="col-md-4" style="float: left;margin-right: 50px;">
		                            		<input id="wing_type" class="payment_type" onChange="paymentType(3);" type="radio" name="payment_type" value="3" style="margin-top: 11px;">
		                            		<img alt="" src="<?php echo $this->baseUrl();?>/images/acleda.jpg" style="margin-left: 30px;"> 
		                            	</div>
		                            	<div class="col-md-4" style="float: left;margin-right: 50px;">
		                            		<input id="cash_type" class="payment_type" onChange="paymentType(4);" type="radio" name="payment_type" value="4" style="margin-top: 11px;">
		                            		<img alt="" src="<?php echo $this->baseUrl();?>/images/cptlogo.png" style="margin-left: 30px;width:174px"> 
		                            	</div>
		                            </div>
		                            
		                            <div id="visa">
		                            	<table>
		                            		<tr>
		                            			<td>Card Name</td>
		                            			<td><?php echo $frm->getElement("card_name");?></td>
		                            			<td>Card No.</td>
		                            			<td><?php echo $frm->getElement("card_id");?></td>
		                            		</tr>
		                            		<tr>
		                            			<td>Secure Code/CVV</td>
		                            			<td><?php echo $frm->getElement("secu_code");?></td>
		                            			<td>Expiration Date</td>
		                            			<td><?php echo $frm->getElement("card_exp_date");?></td>
		                            		</tr>
		                            	</table>
		                            </div>
		                            <div id="ws_union" style="display: none">
		                            	<table style="width: 50%">
		                            		<tr>
		                            			<td style="width:10%">Code Number :</td>
		                            			<td style="width: 20%"><?php echo $frm->getElement("wu_code");?></td>
		                            		</tr>
		                            	</table>
		                            </div>
		                            <div id="wing" style="text-align: center;display: none;">
		                            	<!-- <img alt="" src="<?php //echo $this->baseUrl();?>/images/acleda-to.jpg"> -->
		                            </div>
		                            <div id="cash" style="text-align: center;display: none;">
		                            	<table style="width: 50%">
		                            		<tr>
		                            			<td style="width:10%">Total Pay :</td>
		                            			<td style="width: 20%"><?php echo $frm->getElement("cash_pay");?></td>
		                            		</tr>
		                            	</table>
		                            </div>
		                             <div id="" style="text-align: right;">
		                            	<input type="submit" iconclass="dijitIconSearch" dojoType="dijit.form.Button" value="Pay Finish" label="Pay Finish" >
		                            </div> 
		                            
                                </form>
                            <?php }?>
						</div>
					</div>	
		</fieldset>		
		</td>
	</tr>
</table>	
<script type="text/javascript">

function signup(type){
	if(type==1){
		document.getElementById('new_customer').style.display="block";
		document.getElementById('exist_customer').style.display="none"
	}else{
		document.getElementById('exist_customer').style.display="block"
		document.getElementById('new_customer').style.display="none";
	}
}
$( document ).ready(function() {
	//activeSelfDrive();
});
function addDriver(index){
	var ids=$('#identity_driver').val();
	var arrays = ids.split(',');
	for(var i=0;i<arrays.length;i++) {//calculate record row
		if(arrays[i] == index) arrays.splice(i,1);
		if(document.getElementById('driver_'+index).checked){
			if(($("#identity_driver").val())!="") {
				$("#identity_driver").val(ids+','+index);
			}else { 
				$("#identity_driver").val(index);
			}
		 }else{
			 //alert(index);
			var strings = arrays.join(',');
			$('#identity_driver').val(strings);
		}
	}
}

function addEquipment(index){
	var id=$('#identity_equipment').val();
	var arrays = id.split(',');
	for(var j=0;j<arrays.length;j++) {//calculate record row
		if(arrays[j] == index) arrays.splice(j,1);
		if(document.getElementById('equipment_'+index).checked){
			if(($("#identity_equipment").val())!="") {
				$("#identity_equipment").val(id+','+index);
				
			}else { 
				$("#identity_equipment").val(index);
			}
			$("#number_equipment_"+index).removeAttr("readonly");
			$("#number_equipment_"+index).val(1);
		 }else{
			 //alert(index);
			var strings = arrays.join(',');
			$('#identity_equipment').val(strings);
			$("#number_equipment_"+index).val("");
			$("#number_equipment_"+index).attr("readonly", true);
		}
	}
}
function activeSelfDrive(){
	var self_drive = $('#self_drive').val();
		 if(self_drive=="on") {
		      $('#drive_select').css("display", "none");
		   }
}
function activeChauffeur(){
	var Chauffeur = $('#chauffeur').val();
		 if(Chauffeur=="on") {
		      $('#drive_select').css("display", "block");
		   }
}
$("#submitform").submit(function( event ) {
	alldata = $("#identity_equipment").val();
	if(alldata==''){
		alert("Please Select One of Product !");
		return false;
	}else{
		return true;
	}
});

var url="<?php echo $this->url(array('module'=>'booking','controller'=>'guidebooking','action'=>'get-customer'));?>";
function getCustomer(){
	var id = dijit.byId('customer').get('value');
	tep="";
	loading();
	dojo.xhrPost({
	    url: url,
	    content:{
	     'id':id
	     },
	    handleAs:"json",
	    load: function(data) {
	    	document.getElementsByClassName("overlay")[0].style.display="none";
		     	tep+='<table>';
		     		tep+='<tr>';
		     			tep+='<td style="width:10%">Name:<input type="hidden" name="cu_id" value="'+data.id+'" /></td>';
		     			tep+='<td style="width:30%">'+data.first_name+" "+data.last_name+'</td>';
		     			tep+='<td></td></tr>';
		     		tep+='<tr>';
			     		tep+='<td style="width:10%">Email:</td>';
		     			tep+='<td style="width:30%">'+data.email+'</td>';
		     			tep+='<td></td>' ;
		 			tep+='</tr>';
		 			tep+='<tr>';
			 			tep+='<td style="width:10%">Cell Phone:</td>';
		     			tep+='<td style="width:30%">'+data.phone+'</td>';
		     			tep+='<td></td></tr>';
		     	tep+='</table>';
				document.getElementById('confirm_btn').style.display="block";
     		//$('#customer_info').append(tep);
     		document.getElementById('customer_info').innerHTML =tep;
	    },
	    error: function(err) {
	     alert(err);
	    }
	   });
}
function paymentType(type){
	if(type==1){
		
		dijit.byId('card_id').attr('required',true);
        dijit.byId('card_name').attr('required',true);
        dijit.byId('card_exp_date').attr('required',true);
        dijit.byId('secu_code').attr('required',true);
        dijit.byId('wu_code').attr('required',false);
		dijit.byId('cash_pay').attr('required',false);
		
		$('#visa').css("display","block");
		$('#ws_union').css("display","none");
		$('#wing').css("display","none");
		$('#cash').css("display","none");
	}else if(type==2){
		dijit.byId('card_id').attr('required',false);
        dijit.byId('card_name').attr('required',false);
        dijit.byId('card_exp_date').attr('required',false);
        dijit.byId('secu_code').attr('required',false);
		dijit.byId('wu_code').attr('required',true);
		dijit.byId('cash_pay').attr('required',false);
		
		$('#ws_union').css("display","block");
		$('#visa').css("display","none");
		$('#wing').css("display","none");
		$('#cash').css("display","none");
	}else if(type==3){
		dijit.byId('card_id').attr('required',false);
        dijit.byId('card_name').attr('required',false);
        dijit.byId('card_exp_date').attr('required',false);
        dijit.byId('secu_code').attr('required',false);
        dijit.byId('wu_code').attr('required',false);
		dijit.byId('cash_pay').attr('required',false);
		
		$('#ws_union').css("display","none");
		$('#visa').css("display","none");
		$('#wing').css("display","block");
		$('#cash').css("display","none");
	}else{
		dijit.byId('card_id').attr('required',false);
        dijit.byId('card_name').attr('required',false);
        dijit.byId('card_exp_date').attr('required',false);
        dijit.byId('secu_code').attr('required',false);
        dijit.byId('wu_code').attr('required',false);
		dijit.byId('cash_pay').attr('required',true);
		
		$('#cash').css("display","block");
		$('#ws_union').css("display","none");
		$('#visa').css("display","none");
		$('#wing').css("display","none");
	}
}
function mothlyRetntal(){
	var rentaltype = $('input[name="rental_type"]:checked').val();
	if(rentaltype==2){
		$('#monthly_rent').attr("readonly", false);
		dijit.byId('monthly_rent').attr('value',1);
		calculateDate();
// 		dijit.byId('return_date').textbox.readonly = true;
        $('#return_date').attr("readonly", true);
        $('#return_date').focus();
	}else{
		$('#monthly_rent').attr("readonly", true);
		$('#monthly_rent').val("");
// 		dijit.byId('return_date').textbox.readonly = false;
        $('#return_date').attr("readonly", false);
	}
}
function calculateDate(){
	var month_num = $('#monthly_rent').val();
	var current_date = $('#pickup_date').val();
	old_date = new Date(current_date);
	
	mm = (old_date.getMonth()+parseInt(month_num)+parseInt(1));
	dd = old_date.getDate();
	yy = old_date.getFullYear();
    var today = mm+'/'+dd+'/'+yy;
	$('#return_date').val(today);
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
function addOtherFee(index){
	var id=$('#identity_other_fee').val();
	var arrays = id.split(',');
	for(var j=0;j<arrays.length;j++) {//calculate record row
		if(arrays[j] == index) arrays.splice(j,1);
		if(document.getElementById('other_'+index).checked){
			if(($("#identity_other_fee").val())!="") {
				$("#identity_other_fee").val(id+','+index);
				
			}else { 
				$("#identity_other_fee").val(index);
			}
			dijit.byId("other_fee"+index).attr("disabled",false);
			dijit.byId("other_fee_note"+index).attr("disabled",false);
			dijit.byId("other_fee_note"+index).attr("required",true);
			dijit.byId("other_fee"+index).attr("required",true);
			dijit.byId("other_fee"+index).attr('value',1);
		 }else{
			 //alert(index);
			var strings = arrays.join(',');
			$('#identity_other_fee').val(strings);
			dijit.byId("other_fee"+index).attr('value',0);
			dijit.byId("other_fee"+index).attr("disabled",true);
			dijit.byId("other_fee_note"+index).attr("disabled",true);
			dijit.byId("other_fee_note"+index).attr("required",false);
			dijit.byId("other_fee"+index).attr("required",false);
		}
	}
}
</script>
<style>
.overlay {display: none;position: absolute;width: 100%;height: 100%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .95;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           border: solid 1px #060522;text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>