<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("Customer List"));
?>	
<?php $frm =  $this->frm_search;
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.FilteringSelect');
</script>
 <div class="blog_form_title">
 	<h4><i class="fa fa-users" aria-hidden="true"></i> <?php echo $tr->translate("CUSTOMER")?></h4>
 </div>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
  <?php echo $frm->getElement("title");?>
  <?php echo $frm->getElement('status_search');?>
    <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
<?php echo $this->list;?>
</form>