<?php 
     $url_save = $this->url(array('module'=>'vehicle','controller'=>'model','action'=>'add'));
     $status_view=$this->status_view;
   //  print_r($status_view);exit();
?>
<?php $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
 echo '<title>'. $this->tr->translate("MODEL").'</title>';
?>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
var model_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->all_make));?> );

dojo.ready(function(){
new dijit.form.FilteringSelect({
    store: model_store,
    autoComplete: true,                        
    required: true,
    id: "make",
    name: "make",           
    class: 'fullside',            
    missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​អ្នក​ផ្ញើរ!",            
    onChange: function() {  
    	make_id = dijit.byId('make').get('value');
    	if(make_id==-1){
			dijit.byId('pop_make').show();
	     }           
    }
}, "make");
}); 
</script>
<form  id='add_techer' action="<?php echo $url_save;?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('province_name').get('value')==''){
				 alert('Please Select Province');
                 return false;
                }
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="45%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend align="center" ><strong>Add Model</strong></legend>
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td>Model</td>
							<td><input dojoType="dijit.form.ValidationTextBox" required="true"  class="fullside" id="model" name="model" value="" type="text"></td>
						</tr>
						<tr>
							<td>Make Name</td>
							<td><input id="make" /> </td>
						</tr>
						<tr>
							<td>Status</td>
							<td>
								<select name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true" class="fullside">
								   <?php foreach ($status_view as $r ){?>
                                       <option value="<?php echo $r['key_code'];?>" label="Active"><?php echo $r['name_en']; ?></option>      								         	
								    <?php }?>
								</select>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
											<input type="reset" iconClass="dijitIconClear" label="Clear"dojoType="dijit.form.Button"/>
											<input type="submit" value="save_close" name="save_close" label="Save&Close" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
											<input type="submit" value="save_new" name="save_new" label="Save&New" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_make" >
		<form id='frm_make' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>Make Title</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="txt_make" name="txt_make" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addMake();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<script type="text/javascript">
dojo.require("dijit/Dialog");
var url_make = '<?php echo $this->url(array('module'=>'vehicle','controller'=>'model','action'=>'add-make')); ?>';
function addMake(){
	if(dijit.byId('frm_make').validate()){
		dojo.xhrPost({
			url:url_make,
			form: dojo.byId("frm_make"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
					    name: dijit.byId('txt_make').get('value')
				};			
				addDataToSelectbox(dijit.byId('make'), model_store, Itemmake, data);
				dijit.byId('frm_make').reset();
				dijit.byId("pop_make").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}

</script>
